import type { StorefrontCopy } from "./en";

/** Storefront copy, German. */
export const de: StorefrontCopy = {
  chrome: {
    shop: "Shop",
    currencyLabel: "Währung",
    currencyApply: "Übernehmen",
    basket: "Warenkorb",
    basketWithCount: "Warenkorb ({count})",
    operatedBy: "Betrieben von {client}. Auf Bestellung gefertigt und weltweit versandt.",
    allProducts: "Alle Produkte",
    orderStatus: "Bestellstatus",
    delivery: "Versand",
    help: "Hilfe",
    supportEmailLabel: "E-Mail",
    supportPhoneLabel: "Telefon",
    supportPending: "Kontaktdaten für den Support sind noch nicht hinterlegt.",
    carriersPending: "Versanddienstleister werden eingerichtet",
    pricesShownIn: "Preise in {currency}{tax}.",
    taxIncluded: ", inklusive Steuer",
    taxAtCheckout: ", Steuer wird an der Kasse berechnet",
    legal:
      "© {year} {client}. {client} ist der Verkäufer dieses Shops. Storefront betrieben mit Parcelith.",
  },

  meta: {
    homeTitle: "{store} — Merch auf Bestellung",
    homeDescription:
      "Shoppen Sie bei {store}, dem offiziellen Store von {client}. Auf Bestellung gedruckt und weltweit versandt.",
    shopTitle: "Shop — {store}",
    shopDescription: "Alle Produkte von {store}.",
  },

  home: {
    closedTitle: "Dieser Shop ist geschlossen",
    closedBody:
      "{client} hat {store} archiviert. Bestehende Bestellungen werden weiterhin ausgeliefert und ihre Statusseiten bleiben erreichbar.",
    comingSoonTitle: "{store} ist fast bereit",
    comingSoonBody: "Das Layout des Shops wurde noch nicht veröffentlicht.",
    comingSoonWithProducts: "Die Produkte sind bereits online und können angesehen werden.",
    comingSoonNoProducts: "Schauen Sie bald wieder vorbei.",
    browseProducts: "{count} Produkte ansehen",
  },

  shop: {
    title: "Alles im Shop",
    intro: "Auf Bestellung gefertigt und weltweit versandt. Preise in {currency}{tax}.",
    taxIncluded: ", inklusive Steuer",
    taxAtCheckout: "; die Steuer wird an der Kasse berechnet",
    searchLabel: "Suche",
    searchPlaceholder: "T-Shirt, Hoodie, Tasse …",
    searchSubmit: "Suchen",
    clear: "Zurücksetzen",
    filterByTag: "Nach Schlagwort filtern",
    emptyTitle: "Noch nichts veröffentlicht",
    emptyBody: "Dieser Shop hat noch keine Produkte veröffentlicht. Schauen Sie bald wieder vorbei.",
    noMatchTitle: "Keine Produkte passen zu dieser Suche",
    noMatchBody: "Versuchen Sie einen anderen Suchbegriff oder setzen Sie die Filter zurück.",
    clearFilters: "Filter zurücksetzen",
    personalise: "Personalisierbar",
    previewSoon: "Vorschau folgt in Kürze",
  },

  product: {
    breadcrumb: "Brotkrümelnavigation",
    breadcrumbShop: "Shop",
    about: "Über dieses Produkt",
    madeToOrder: "Auf Bestellung gefertigt",
    producedBy: "Gefertigt von {supplier} in {lead}, anschließend versandt mit {carriers}.",
    defaultSupplier: "unserem Produktionspartner",
    leadDays: "{from}–{to} Tagen",
    leadUnknown: "wenigen Tagen",
    defaultCarrier: "unserem Versanddienstleister",
    carrierJoin: "oder",
    printDetail: "Druckdetails",
    printDetailBody: "{area}, {width} × {height} mm, gedruckt mit mindestens {dpi} DPI.",
    taxAndDelivery: "Steuer und Versand",
    pricesShownIn: "Preise in {currency}{tax}.",
    taxIncluded: " inklusive Steuer",
    taxAtCheckout: "; die Steuer wird an der Kasse berechnet",
    merchantOfRecord: "{client} ist der Verkäufer dieser Bestellung.",
  },

  purchase: {
    addToBasket: "In den Warenkorb",
    adding: "Wird hinzugefügt …",
    viewBasket: "Warenkorb ansehen",
    colour: "Farbe",
    size: "Größe",
    option: "Variante",
    required: "Erforderlich",
    quantity: "Menge",
    lowStock: "wenige",
    noPreview: "Keine Vorschau verfügbar",
    previewAlt: "Vorschau von {name}",
    viewAlt: "Ansicht {view}",
    livePreview:
      "Live-Vorschau. Eine produktionsgenaue Fassung wird beigefügt, sobald Sie den Artikel in den Warenkorb legen.",
    textPlaceholder: "Optional",
    textCounter: "{count}/{max} Zeichen. Wird mit dem Design gedruckt.",
    artworkLabel: "Eigenes Motiv",
    artworkHint:
      "Druck auf {width} × {height} mm, daher sind mindestens {dpi} DPI nötig. {formats} bis {max} MB.",
    artworkHintSimple: "PNG, JPG oder WEBP.",
    uploading: "Ihr Motiv wird hochgeladen …",
    uploadFailed: "Diese Datei konnte nicht hochgeladen werden.",
    fileTooLarge: "Diese Datei ist {size} MB groß. Das Limit liegt bei {limit} MB.",
  },

  basket: {
    title: "Ihr Warenkorb",
    emptyTitle: "Noch nichts im Warenkorb",
    emptyBody:
      "Legen Sie ein Produkt samt Personalisierung hinein — es erscheint hier mit der Vorschau, die Ihrer Bestellung beiliegt.",
    browseShop: "Zum Shop",
    previewAlt: "Vorschau von {name}",
    personalisation: "Personalisierung:",
    artwork: "Motiv: {file}",
    quantity: "Menge",
    update: "Aktualisieren",
    remove: "Entfernen",
    summary: "Zusammenfassung",
    subtotal: "Zwischensumme",
    shipping: "Versand",
    taxRow: "Steuer {rate} %",
    taxIncludedSuffix: "inklusive",
    total: "Gesamt",
    checkout: "Zur Kasse",
    keepShopping: "Weiter einkaufen",
  },

  checkout: {
    title: "Kasse",
    merchantNote:
      "{client} ist der Verkäufer. Die Zahlung geht auf das eigene Stripe-Konto des Shops.",
    unavailableTitle: "Dieser Shop kann noch keine Zahlungen annehmen",
    unavailableBody:
      "Der Shop hat die Verbindung zu seinem Stripe-Konto noch nicht abgeschlossen. Ihr Warenkorb bleibt gespeichert — versuchen Sie es erneut, sobald der Shop live ist.",
    backToBasket: "Zurück zum Warenkorb",
    summaryTitle: "Bestellübersicht",
    shipping: "Versand",
    taxRow: "Steuer {rate} %",
    taxIncludedSuffix: "inklusive",
    total: "Gesamt",
    deliveryDetails: "Lieferdaten",
    fullName: "Vollständiger Name",
    email: "E-Mail",
    emailHint: "Mit dieser Adresse und Ihrem Bestellcode öffnen Sie später Ihre Bestellseite.",
    street: "Straße und Hausnummer",
    city: "Ort",
    postalCode: "Postleitzahl",
    country: "Land",
    countryHint: "Tippen Sie, um Ihr Land zu finden. Die Produktion richtet sich nach dem Zielland.",
    countrySearchPlaceholder: "Länder durchsuchen",
    countryNoMatch: "Kein Land passt zu „{query}“.",
    payIn: "Zahlen in",
    manualRoutingTitle: "Lieferung nach {country} muss manuell zugeteilt werden",
    manualRoutingLine: "{supplier} fertigt {products} und liefert nicht nach {country} ({region}).",
    productJoin: "und",
    manualRoutingBody:
      "Sie können trotzdem bezahlen, doch die Bestellung wird zurückgehalten, bis sie jemand bei einem anderen Produktionspartner aufgibt — das dauert länger als die übliche Lieferzeit. Ein Zielland, das Ihr Hersteller abdeckt, vermeidet die Wartezeit.",
    paymentTitle: "Zahlung",
    paymentNote:
      "Abgerechnet über das eigene Stripe-Konto dieses Shops {account}. Kartendaten werden vom Shop nie gespeichert.",
    cardNumber: "Kartennummer",
    expiry: "Gültig bis (MM/JJ)",
    securityCode: "Prüfziffer",
    testMode: "Stripe-Testmodus",
    submit: "Bezahlen und bestellen",
    pending: "Zahlung wird ausgeführt …",
    cardSucceeds: "Visa — erfolgreich",
    cardDeclined: "Visa — von der Bank abgelehnt",
    cardInsufficient: "Visa — Deckung reicht nicht",
  },

  order: {
    title: "Bestellstatus",
    lookupIntro:
      "Geben Sie Ihren Bestellcode und die E-Mail-Adresse ein, die Sie an der Kasse angegeben haben. Der Link, den Sie beim Bestellen gespeichert haben, öffnet die Bestellung direkt.",
    gateBody:
      "Zum Schutz von Liefer- und Personalisierungsdaten bestätigen Sie bitte die E-Mail-Adresse zur Bestellung {code}, bevor wir sie anzeigen.",
    confirmedTitle: "Vielen Dank — Ihre Bestellung ist bestätigt",
    confirmedBody:
      "Speichern Sie diese Seite oder setzen Sie ein Lesezeichen — hier sehen Sie den Fortschritt Ihrer Bestellung. Der Shop verschickt noch keine Bestätigungs-E-Mails.",
    confirmedFindAgain:
      "Sie finden sie jederzeit über „Bestellstatus“ mit dem Bestellcode {code} und der E-Mail-Adresse {email} wieder.",
    heading: "Bestellung {code}",
    placed: "Aufgegeben am {when}",
    trackWith: "Mit {carrier} verfolgen ↗",
    whatYouOrdered: "Ihre Bestellung",
    variantQuantity: "{variant} · Menge {count}",
    personalisation: "Personalisierung:",
    previewAlt: "Vorschau von {name}",
    subtotal: "Zwischensumme",
    shipping: "Versand",
    taxRow: "Steuer {rate} %",
    paid: "Bezahlt",
    refunded: "Erstattet",
    deliveringTo: "Lieferadresse",
    payment: "Zahlung",
    cardEnding: "Karte endend auf {last4}",
    card: "Karte",
    paidWord: "bezahlt",
    refundedWord: "erstattet",
    merchantOfRecord: "{client} ist der Verkäufer.",
    progress: "Verlauf",
    supportTitle: "Fragen zu dieser Bestellung",
    contactSubject: "Bestellung {code}",
    continueShopping: "Weiter einkaufen",
    contactStore: "Shop kontaktieren",
    orderCode: "Bestellcode",
    orderCodeHint: "Beginnt mit ORD- und steht oben auf Ihrer Bestellseite.",
    emailOnOrder: "E-Mail-Adresse der Bestellung",
    emailHint: "Die Adresse, die Sie an der Kasse angegeben haben.",
    lookupSubmit: "Bestellung anzeigen",
    lookupPending: "Wird geprüft …",
  },

  status: {
    awaitingPayment: "Zahlung ausstehend",
    awaitingPaymentNote: "Für diese Bestellung ist noch keine Zahlung eingegangen.",
    paid: "Zahlung eingegangen",
    paidNote: "Ihre Bestellung wartet auf die Produktion.",
    inProduction: "In Produktion",
    inProductionNote: "Ihr Artikel wird gerade gedruckt und veredelt.",
    shipped: "Versandt",
    shippedNote: "Ihr Paket ist unterwegs. Verfolgen Sie es über den Link unten.",
    delivered: "Zugestellt",
    deliveredNote: "Ihr Paket wurde zugestellt. Viel Freude damit.",
    cancelled: "Storniert",
    cancelledNote: "Diese Bestellung wurde storniert. Bereits gezahlte Beträge wurden erstattet.",
    exception: "Benötigt Aufmerksamkeit",
    exceptionNote:
      "Diese Bestellung ist vorübergehend angehalten. Das Shop-Team kümmert sich darum und meldet sich.",
  },

  actions: {
    storeClosed: "Dieser Shop nimmt derzeit keine Bestellungen an.",
    productGone: "Dieses Produkt ist nicht mehr verfügbar.",
    chooseVariant: "Wählen Sie Größe und Farbe.",
    outOfStock: "{variant} ist ausverkauft. Wählen Sie eine andere Variante.",
    noTextPersonalisation: "Dieses Produkt kann nicht mit Text personalisiert werden.",
    textTooLong: "Halten Sie die Personalisierung auf höchstens {max} Zeichen.",
    noArtworkUpload: "Dieses Produkt nimmt keine hochgeladenen Motive an.",
    productUnavailable: "Dieses Produkt ist vorübergehend nicht verfügbar.",
    fileTooLarge: "Diese Datei ist {size} MB groß. Das Limit liegt bei {limit} MB.",
    basketUnavailable:
      "Ihr Warenkorb konnte nicht geöffnet werden. Erlauben Sie Cookies und versuchen Sie es erneut.",
    addedToBasket: "{product} wurde in Ihren Warenkorb gelegt.",
    basketEmpty: "Ihr Warenkorb ist leer.",
    enterName: "Geben Sie den Namen für die Lieferung an.",
    enterEmail: "Geben Sie eine E-Mail-Adresse an — damit öffnen Sie später Ihre Bestellseite.",
    enterStreet: "Geben Sie Straße und Hausnummer an.",
    enterCity: "Geben Sie den Ort an.",
    enterPostalCode: "Geben Sie die Postleitzahl an.",
    chooseCountry: "Wählen Sie Ihr Lieferland aus der Liste.",
    currencyNotSold: "{currency} gehört nicht zu den Verkaufswährungen dieses Shops.",
    enterOrderCode: "Geben Sie Ihren Bestellcode ein.",
    enterOrderEmail: "Geben Sie die E-Mail-Adresse der Bestellung ein.",
    lookupFailed:
      "Bestellcode und E-Mail-Adresse passen nicht zusammen. Prüfen Sie beides und versuchen Sie es erneut.",
  },

  artwork: {
    lowDpi:
      "Dieses Motiv hat eine zu geringe Druckauflösung. Laden Sie eine Datei mit mindestens {dpi} DPI hoch.",
    badFormat: "{format}-Dateien sind für dieses Produkt nicht zulässig. Laden Sie {formats} hoch.",
    fileTooLarge: "Diese Datei ist {size} MB groß. Das Limit liegt bei {limit} MB.",
    tooManyPixels:
      "Dieses Bild ist zu groß. Verkleinern Sie es auf unter {megapixels} Megapixel und versuchen Sie es erneut.",
    noTransparency:
      "Dieses Produkt braucht ein Motiv mit transparentem Hintergrund. Exportieren Sie es als PNG mit Transparenz.",
    generic: "Dieses Motiv lässt sich auf diesem Produkt nicht drucken. Versuchen Sie eine andere Datei.",
  },

  payment: {
    accountNotReady:
      "Dieser Shop hat die Verbindung zu seinem Stripe-Konto noch nicht abgeschlossen, daher sind Zahlungen nicht möglich.",
    currencyUnsupported: "{currency} gehört nicht zu den Verkaufswährungen dieses Shops.",
    invalidNumber: "Diese Kartennummer ist ungültig. Prüfen Sie die Ziffern und versuchen Sie es erneut.",
    invalidExpiry: "Das Ablaufdatum liegt in der Vergangenheit oder ist falsch formatiert. Nutzen Sie MM/JJ.",
    invalidCvc: "Die Prüfziffer muss 3 oder 4 Stellen haben.",
    declined: "Ihre Karte wurde von der ausgebenden Bank abgelehnt.",
    insufficientFunds: "Ihre Karte weist keine ausreichende Deckung auf.",
    expiredCard: "Ihre Karte ist abgelaufen.",
  },

  sections: {
    viewAll: "Alle ansehen",
    noProducts:
      "In diesem Shop sind noch keine Produkte veröffentlicht. Veröffentlichte Produkte erscheinen hier automatisch.",
    previewSoon: "Vorschau folgt in Kürze",
    imagePlaceholder: "Fügen Sie in den Abschnittseinstellungen eine Bild-URL hinzu",
    newsletterEmail: "E-Mail-Adresse",
    notifyMe: "Benachrichtigen",
    welcome: "Willkommen",
  },

  fallback: {
    notFoundTitle: "Diese Seite gibt es nicht mehr",
    notFoundBody:
      "Der Link ist womöglich veraltet oder das Produkt wird nicht mehr verkauft. Alles, was {store} heute anbietet, ist nur einen Klick entfernt.",
    browseProducts: "Alle Produkte ansehen",
    errorTitle: "Da ist bei uns etwas schiefgelaufen",
    errorBody:
      "Diese Seite konnte nicht geladen werden. Ihr Warenkorb ist unverändert — versuchen Sie es erneut und schauen Sie in ein paar Minuten wieder vorbei, falls es weiterhin nicht klappt.",
    errorRetry: "Erneut versuchen",
    errorHome: "Zurück zu {store}",
    errorReference: "Referenz {digest}",
  },
};
