import type { StorefrontCopy } from "./en";

/** Storefront copy, Spanish. */
export const es: StorefrontCopy = {
  chrome: {
    shop: "Tienda",
    currencyLabel: "Moneda",
    currencyApply: "Aplicar",
    basket: "Cesta",
    basketWithCount: "Cesta ({count})",
    operatedBy: "Gestionada por {client}. Fabricado bajo pedido y enviado a todo el mundo.",
    allProducts: "Todos los productos",
    orderStatus: "Estado del pedido",
    delivery: "Envío",
    help: "Ayuda",
    supportEmailLabel: "Correo electrónico",
    supportPhoneLabel: "Teléfono",
    supportPending: "Los datos de contacto de atención al cliente aún no están publicados.",
    carriersPending: "Configuración de transportistas en curso",
    pricesShownIn: "Precios en {currency}{tax}.",
    taxIncluded: ", impuestos incluidos",
    taxAtCheckout: ", impuestos añadidos al pagar",
    legal:
      "© {year} {client}. {client} es el vendedor oficial de esta tienda. Tienda impulsada por Parcelith.",
  },

  meta: {
    homeTitle: "{store} — productos fabricados bajo pedido",
    homeDescription:
      "Compra en {store}, la tienda oficial de {client}. Impreso bajo demanda y enviado a todo el mundo.",
    taglineDescription:
      "{tagline} Compra en {store}, la tienda oficial de {client}.",
    shopTitle: "Tienda",
    shopDescription: "Todos los productos disponibles en {store}.",
  },

  home: {
    closedTitle: "Esta tienda está cerrada",
    closedBody:
      "{client} ha archivado {store}. Los pedidos existentes se siguen preparando y sus páginas de estado continúan disponibles.",
    comingSoonTitle: "{store} está casi lista",
    comingSoonBody: "El diseño de la tienda todavía no se ha publicado.",
    comingSoonWithProducts: "Los productos ya están publicados y se pueden ver mientras tanto.",
    comingSoonNoProducts: "Vuelve dentro de poco.",
    browseProducts: "Ver {count} productos",
  },

  shop: {
    title: "Todo en la tienda",
    intro: "Fabricado bajo pedido y enviado a todo el mundo. Precios en {currency}{tax}.",
    taxIncluded: ", impuestos incluidos",
    taxAtCheckout: "; los impuestos se añaden al pagar",
    searchLabel: "Buscar",
    searchPlaceholder: "Camiseta, sudadera, taza…",
    searchSubmit: "Buscar",
    clear: "Limpiar",
    filterByTag: "Filtrar por etiqueta",
    emptyTitle: "Todavía no hay nada publicado",
    emptyBody: "Esta tienda aún no ha publicado ningún producto. Vuelve pronto.",
    noMatchTitle: "Ningún producto coincide con esa búsqueda",
    noMatchBody: "Prueba otro término de búsqueda o quita los filtros.",
    clearFilters: "Quitar filtros",
    personalise: "Personalizable",
    previewSoon: "Vista previa muy pronto",
  },

  product: {
    breadcrumb: "Ruta de navegación",
    breadcrumbShop: "Tienda",
    about: "Sobre este producto",
    madeToOrder: "Fabricado bajo pedido",
    producedBy: "Fabricado por {supplier} en {lead} y enviado con {carriers}.",
    defaultSupplier: "nuestro socio de producción",
    leadDays: "{from}–{to} días",
    leadUnknown: "unos días",
    defaultCarrier: "nuestro transportista",
    carrierJoin: "o",
    printDetail: "Detalle de impresión",
    printDetailBody: "{area}, {width} × {height} mm, impreso a un mínimo de {dpi} DPI.",
    taxAndDelivery: "Impuestos y envío",
    pricesShownIn: "Precios en {currency}{tax}.",
    taxIncluded: " con impuestos incluidos",
    taxAtCheckout: "; los impuestos se calculan al pagar",
    merchantOfRecord: "{client} es el vendedor oficial de este pedido.",
  },

  purchase: {
    addToBasket: "Añadir a la cesta",
    adding: "Añadiendo…",
    viewBasket: "Ver la cesta",
    colour: "Color",
    size: "Talla",
    option: "Opción",
    required: "Obligatorio",
    quantity: "Cantidad",
    lowStock: "pocas",
    noPreview: "No hay vista previa disponible",
    previewAlt: "Vista previa de {name}",
    viewAlt: "Vista {view}",
    livePreview:
      "Vista previa en directo. Al añadirlo a la cesta se adjunta una versión fiel a la producción.",
    textPlaceholder: "Opcional",
    textCounter: "{count}/{max} caracteres. Se imprime junto al diseño.",
    artworkLabel: "Tu propio diseño",
    artworkHint:
      "Se imprime a {width} × {height} mm, así que necesitamos al menos {dpi} DPI. {formats} hasta {max} MB.",
    artworkHintSimple: "PNG, JPG o WEBP.",
    uploading: "Subiendo tu diseño…",
    uploadFailed: "No se ha podido subir ese archivo.",
    fileTooLarge: "Ese archivo ocupa {size} MB. El límite es de {limit} MB.",
    artworkPlacementTitle: "Coloca tu diseño",
    artworkPlacementHelp:
      "Arrastra el diseño sobre la vista previa o usa los controles de abajo. La vista previa y la resolución de impresión se actualizan al momento.",
    artworkGrabLabel:
      "Posición de {file}. Arrastra para moverlo o usa las flechas; + y − cambian el tamaño.",
    artworkSize: "Tamaño",
    artworkRotation: "Rotación",
    artworkResolution: "Resolución de impresión",
    artworkRecentre: "Volver a centrar",
    artworkRemove: "Quitar el diseño",
    artworkChecksPass: "Este diseño está listo para imprimirse a este tamaño.",
    artworkChecksFail: "Corrige esto antes de añadirlo a la cesta",
    artworkWhatToDo: "Qué hacer: {fix}",
    artworkBlocked: "Corrige el diseño de arriba, o quítalo, para añadir este artículo a la cesta.",
  },

  basket: {
    title: "Tu cesta",
    emptyTitle: "Todavía no hay nada en la cesta",
    emptyBody:
      "Añade un producto con su personalización y aparecerá aquí, con la vista previa que acompañará a tu pedido.",
    browseShop: "Ir a la tienda",
    previewAlt: "Vista previa de {name}",
    personalisation: "Personalización:",
    artwork: "Diseño: {file}",
    quantity: "Cantidad",
    update: "Actualizar",
    remove: "Quitar",
    summary: "Resumen",
    subtotal: "Subtotal",
    shipping: "Envío",
    taxRow: "Impuestos {rate} %",
    taxIncludedSuffix: "incluidos",
    total: "Total",
    checkout: "Pagar",
    keepShopping: "Seguir comprando",
  },

  checkout: {
    title: "Pago",
    merchantNote:
      "{client} es el vendedor oficial. El pago se liquida en su propia cuenta de Stripe.",
    unavailableTitle: "Esta tienda todavía no puede aceptar pagos",
    unavailableBody:
      "La tienda no ha terminado de conectar su cuenta de Stripe. Tu cesta se conserva: inténtalo de nuevo cuando la tienda esté activa.",
    backToBasket: "Volver a la cesta",
    summaryTitle: "Resumen del pedido",
    shipping: "Envío",
    taxRow: "Impuestos {rate} %",
    taxIncludedSuffix: "incluidos",
    total: "Total",
    deliveryDetails: "Datos de envío",
    fullName: "Nombre completo",
    email: "Correo electrónico",
    emailHint: "Con esta dirección y tu código de pedido podrás volver a abrir la página del pedido.",
    street: "Dirección",
    city: "Población o ciudad",
    postalCode: "Código postal",
    country: "País",
    countryHint: "Empieza a escribir para encontrar tu país. La producción se asigna según el destino.",
    countrySearchPlaceholder: "Buscar países",
    countryNoMatch: "Ningún país coincide con «{query}».",
    payIn: "Pagar en",
    manualRoutingTitle: "El envío a {country} necesita asignación manual",
    manualRoutingLine: "{supplier} fabrica {products} y no realiza envíos a {country} ({region}).",
    productJoin: "y",
    manualRoutingBody:
      "Puedes pagar igualmente, pero el pedido quedará retenido para que una persona lo curse con otro socio de producción, así que tardará más de lo habitual. Elegir un país de entrega cubierto por tu proveedor evita la espera.",
    paymentTitle: "Pago",
    paymentNote:
      "Se cobra a través de la cuenta de Stripe de esta tienda {account}. La tienda nunca guarda los datos de la tarjeta.",
    cardNumber: "Número de tarjeta",
    expiry: "Caducidad (MM/AA)",
    securityCode: "Código de seguridad",
    testMode: "Modo de prueba de Stripe",
    submit: "Pagar y realizar el pedido",
    pending: "Procesando el pago…",
    cardSucceeds: "Visa — aceptada",
    cardDeclined: "Visa — rechazada por el banco",
    cardInsufficient: "Visa — saldo insuficiente",
  },

  order: {
    title: "Estado del pedido",
    lookupIntro:
      "Introduce tu código de pedido y el correo electrónico que indicaste al pagar. El enlace que guardaste al hacer el pedido lo abre directamente.",
    gateBody:
      "Para proteger los datos de envío y personalización, confirma el correo electrónico del pedido {code} antes de mostrarlo.",
    confirmedTitle: "Gracias: tu pedido está confirmado",
    confirmedBody:
      "Guarda esta página o añádela a favoritos: aquí se muestra el avance de tu pedido. La tienda todavía no envía correos de confirmación.",
    confirmedFindAgain:
      "También puedes volver a abrirla desde «Estado del pedido» con el código {code} y el correo electrónico {email}.",
    heading: "Pedido {code}",
    placed: "Realizado el {when}",
    trackWith: "Seguir con {carrier} ↗",
    whatYouOrdered: "Tu pedido",
    variantQuantity: "{variant} · cantidad {count}",
    personalisation: "Personalización:",
    previewAlt: "Vista previa de {name}",
    subtotal: "Subtotal",
    shipping: "Envío",
    taxRow: "Impuestos {rate} %",
    paid: "Pagado",
    refunded: "Reembolsado",
    deliveringTo: "Se entrega a",
    payment: "Pago",
    cardEnding: "Tarjeta terminada en {last4}",
    card: "Tarjeta",
    paidWord: "pagado",
    refundedWord: "reembolsado",
    merchantOfRecord: "{client} es el vendedor oficial.",
    progress: "Seguimiento",
    supportTitle: "¿Dudas sobre este pedido?",
    contactSubject: "Pedido {code}",
    continueShopping: "Seguir comprando",
    contactStore: "Contactar con la tienda",
    orderCode: "Código de pedido",
    orderCodeHint: "Empieza por ORD- y aparece arriba en la página de tu pedido.",
    emailOnOrder: "Correo del pedido",
    emailHint: "La dirección que indicaste al pagar.",
    lookupSubmit: "Ver mi pedido",
    lookupPending: "Comprobando…",
  },

  status: {
    awaitingPayment: "Pendiente de pago",
    awaitingPaymentNote: "Todavía no hemos recibido el pago de este pedido.",
    paid: "Pago recibido",
    paidNote: "Tu pedido está en cola para producción.",
    inProduction: "En producción",
    inProductionNote: "Tu artículo se está imprimiendo y acabando.",
    shipped: "Enviado",
    shippedNote: "Tu paquete está en camino. Síguelo con el enlace de abajo.",
    delivered: "Entregado",
    deliveredNote: "Tu paquete se ha entregado. Que lo disfrutes.",
    cancelled: "Cancelado",
    cancelledNote: "Este pedido se canceló. Cualquier pago se ha reembolsado.",
    exception: "Requiere atención",
    exceptionNote:
      "Este pedido está retenido. El equipo de la tienda se está ocupando y se pondrá en contacto contigo.",
  },

  actions: {
    storeClosed: "Esta tienda no está aceptando pedidos en este momento.",
    productGone: "Ese producto ya no está disponible.",
    chooseVariant: "Elige una talla y un color.",
    outOfStock: "{variant} está agotado. Elige otra opción.",
    noTextPersonalisation: "Este producto no se puede personalizar con texto.",
    textTooLong: "Limita la personalización a {max} caracteres como máximo.",
    noArtworkUpload: "Este producto no admite diseños subidos.",
    productUnavailable: "Este producto no está disponible temporalmente.",
    fileTooLarge: "Ese archivo ocupa {size} MB. El límite es de {limit} MB.",
    basketUnavailable: "No se ha podido abrir tu cesta. Activa las cookies e inténtalo de nuevo.",
    addedToBasket: "{product} se ha añadido a tu cesta.",
    basketEmpty: "Tu cesta está vacía.",
    enterName: "Indica el nombre para la entrega.",
    enterEmail: "Indica un correo electrónico: es con lo que volverás a abrir tu pedido.",
    enterStreet: "Indica la dirección.",
    enterCity: "Indica la población o ciudad.",
    enterPostalCode: "Indica el código postal.",
    chooseCountry: "Elige tu país de entrega en la lista.",
    currencyNotSold: "{currency} no es una de las monedas de venta de esta tienda.",
    enterOrderCode: "Introduce tu código de pedido.",
    enterOrderEmail: "Introduce el correo electrónico del pedido.",
    lookupFailed:
      "No hemos podido relacionar ese código de pedido con ese correo. Revisa ambos e inténtalo de nuevo.",
  },

  artwork: {
    lowDpi: "Esta imagen se imprimirá a {dpi} DPI, por debajo de los {required} DPI que necesita este producto.",
    lowDpiFix:
      "Sube una de al menos {pixels} píxeles de ancho, o reduce el diseño: este archivo se ve nítido hasta {width} mm de ancho.",
    badFormat: "Los archivos {format} no se admiten en este producto.",
    badFormatFix: "Guarda el diseño como {formats} y vuelve a seleccionarlo.",
    unreadableFormat: "Los archivos {format} no se pueden medir ni previsualizar aquí.",
    unreadableFormatFix: "Guarda el diseño como {formats} y vuelve a seleccionarlo.",
    fileTooLarge: "Ese archivo ocupa {size} MB. El límite es de {limit} MB.",
    fileTooLargeFix: "Guárdalo con menos tamaño o calidad y vuelve a seleccionarlo.",
    tooManyPixels: "Esa imagen es demasiado grande. El límite es de {megapixels} megapíxeles.",
    tooManyPixelsFix: "Redimensiónala en tu editor de fotos y vuelve a seleccionarla.",
    noTransparency:
      "Este producto se imprime directamente sobre la tela, así que el diseño necesita fondo transparente.",
    noTransparencyFix: "Quita el fondo y guárdalo como PNG con transparencia.",
    outsideArea: "Parte del diseño queda fuera del área imprimible y se cortaría.",
    outsideAreaFix:
      "Arrástralo dentro del recuadro discontinuo, o hazlo más pequeño para que quepa en {width} × {height} mm.",
    dpiTight: "Esta imagen se imprimirá a {dpi} DPI, justo por encima del mínimo de {required} DPI.",
    dpiTightFix:
      "Las líneas finas pueden verse suaves. Un archivo más grande, o un diseño algo menor, imprime más nítido.",
    verySmall: "El diseño ocupa menos del 15 % del ancho imprimible.",
    verySmallFix: "Sube el control de tamaño si va a ser el gráfico principal.",
    generic: "Ese diseño no se puede imprimir en este producto.",
    genericFix: "Prueba con otro archivo.",
  },

  payment: {
    accountNotReady:
      "Esta tienda no ha terminado de conectar su cuenta de Stripe, así que los pagos no están disponibles.",
    currencyUnsupported: "{currency} no es una de las monedas de venta de esta tienda.",
    invalidNumber: "Ese número de tarjeta no es válido. Revisa los dígitos e inténtalo de nuevo.",
    invalidExpiry: "La fecha de caducidad ya pasó o tiene un formato incorrecto. Usa MM/AA.",
    invalidCvc: "El código de seguridad debe tener 3 o 4 dígitos.",
    declined: "El banco emisor ha rechazado tu tarjeta.",
    insufficientFunds: "Tu tarjeta no tiene saldo suficiente.",
    expiredCard: "Tu tarjeta ha caducado.",
  },

  sections: {
    viewAll: "Ver todo",
    noProducts:
      "Todavía no hay productos publicados en esta tienda. Los productos publicados aparecen aquí automáticamente.",
    previewSoon: "Vista previa muy pronto",
    imagePlaceholder: "Añade la URL de una imagen en los ajustes de la sección",
    newsletterEmail: "Correo electrónico",
    notifyMe: "Avisadme",
    welcome: "Bienvenido",
  },

  fallback: {
    notFoundTitle: "No encontramos esa página",
    notFoundBody:
      "Puede que el enlace esté desactualizado o que el producto ya no esté a la venta. Todo lo que {store} vende hoy sigue a un clic.",
    browseProducts: "Ver todos los productos",
    errorTitle: "Algo ha fallado por nuestra parte",
    errorBody:
      "No se ha podido cargar esta página. Tu cesta sigue intacta: inténtalo de nuevo y, si el problema continúa, vuelve dentro de unos minutos.",
    errorRetry: "Reintentar",
    errorHome: "Volver a {store}",
    errorReference: "Referencia {digest}",
  },
};
