import type { StorefrontCopy } from "./en";

/** Storefront copy, Spanish. */
export const es: StorefrontCopy = {
  chrome: {
    shop: "Tienda",
    currencyLabel: "Moneda",
    currencyApply: "Aplicar",
    basket: "Cesta",
    basketWithCount: "Cesta ({count})",
    operatedBy: "Gestionada por {client}. Fabricado bajo pedido y enviado a todo el mundo.",
    allProducts: "Todos los productos",
    orderStatus: "Estado del pedido",
    delivery: "Envío",
    help: "Ayuda",
    supportEmailLabel: "Correo electrónico",
    supportPhoneLabel: "Teléfono",
    supportPending: "Los datos de contacto de atención al cliente aún no están publicados.",
    carriersPending: "Configuración de transportistas en curso",
    pricesShownIn: "Precios en {currency}{tax}.",
    taxIncluded: ", impuestos incluidos",
    taxAtCheckout: ", impuestos añadidos al pagar",
    legal:
      "© {year} {client}. {client} es el vendedor oficial de esta tienda. Tienda impulsada por Parcelith.",
  },

  meta: {
    homeTitle: "{store} — productos fabricados bajo pedido",
    homeDescription:
      "Compra en {store}, la tienda oficial de {client}. Impreso bajo demanda y enviado a todo el mundo.",
    taglineDescription:
      "{tagline} Compra en {store}, la tienda oficial de {client}.",
    shopTitle: "Tienda",
    shopDescription: "Todos los productos disponibles en {store}.",
  },

  home: {
    closedTitle: "Esta tienda está cerrada",
    closedBody:
      "{client} ha archivado {store}. Los pedidos existentes se siguen preparando y sus páginas de estado continúan disponibles.",
    comingSoonTitle: "{store} está casi lista",
    comingSoonBody: "El diseño de la tienda todavía no se ha publicado.",
    comingSoonWithProducts: "Los productos ya están publicados y se pueden ver mientras tanto.",
    comingSoonNoProducts: "Vuelve dentro de poco.",
    browseProducts: "Ver {count} productos",
  },

  shop: {
    title: "Todo en la tienda",
    intro: "Fabricado bajo pedido y enviado a todo el mundo. Precios en {currency}{tax}.",
    taxIncluded: ", impuestos incluidos",
    taxAtCheckout: "; los impuestos se añaden al pagar",
    searchLabel: "Buscar",
    searchPlaceholder: "Camiseta, sudadera, taza…",
    searchSubmit: "Buscar",
    clear: "Limpiar",
    filterByTag: "Filtrar por etiqueta",
    emptyTitle: "Todavía no hay nada publicado",
    emptyBody: "Esta tienda aún no ha publicado ningún producto. Vuelve pronto.",
    noMatchTitle: "Ningún producto coincide con esa búsqueda",
    noMatchBody: "Prueba otro término de búsqueda o quita los filtros.",
    clearFilters: "Quitar filtros",
    personalise: "Personalizable",
    previewSoon: "Vista previa muy pronto",
  },

  product: {
    breadcrumb: "Ruta de navegación",
    breadcrumbShop: "Tienda",
    about: "Sobre este producto",
    madeToOrder: "Fabricado bajo pedido",
    producedBy: "Fabricado por {supplier} en {lead} y enviado con {carriers}.",
    defaultSupplier: "nuestro socio de producción",
    leadDays: "{from}–{to} días",
    leadUnknown: "unos días",
    defaultCarrier: "nuestro transportista",
    carrierJoin: "o",
    printDetail: "Detalle de impresión",
    printDetailBody: "{area}, {width} × {height} mm, impreso a un mínimo de {dpi} DPI.",
    taxAndDelivery: "Impuestos y envío",
    pricesShownIn: "Precios en {currency}{tax}.",
    taxIncluded: " con impuestos incluidos",
    taxAtCheckout: "; los impuestos se calculan al pagar",
    merchantOfRecord: "{client} es el vendedor oficial de este pedido.",
  },

  purchase: {
    addToBasket: "Añadir a la cesta",
    adding: "Añadiendo…",
    viewBasket: "Ver la cesta",
    colour: "Color",
    size: "Talla",
    option: "Opción",
    required: "Obligatorio",
    quantity: "Cantidad",
    lowStock: "pocas",
    noPreview: "No hay vista previa disponible",
    previewAlt: "Vista previa de {name}",
    viewAlt: "Vista {view}",
    livePreview:
      "Vista previa en directo. Al añadirlo a la cesta se adjunta una versión fiel a la producción.",
    textPlaceholder: "Opcional",
    textCounter: "{count}/{max} caracteres. Se imprime junto al diseño.",
    artworkLabel: "Tu propio diseño",
    artworkHint:
      "Se imprime a {width} × {height} mm, así que necesitamos al menos {dpi} DPI. {formats} hasta {max} MB.",
    artworkHintSimple: "PNG, JPG o WEBP.",
    uploading: "Subiendo tu diseño…",
    uploadFailed: "No se ha podido subir ese archivo.",
    fileTooLarge: "Ese archivo ocupa {size} MB. El límite es de {limit} MB.",
    artworkPlacementTitle: "Coloca tu diseño",
    artworkPlacementHelp:
      "Arrastra el diseño sobre la vista previa o usa los controles de abajo. La vista previa y la resolución de impresión se actualizan al momento.",
    artworkGrabLabel:
      "Posición de {file}. Arrastra para moverlo o usa las flechas; + y − cambian el tamaño.",
    artworkSize: "Tamaño",
    artworkRotation: "Rotación",
    artworkResolution: "Resolución de impresión",
    artworkRecentre: "Volver a centrar",
    artworkRemove: "Quitar el diseño",
    artworkChecksPass: "Este diseño está listo para imprimirse a este tamaño.",
    artworkChecksFail: "Corrige esto antes de añadirlo a la cesta",
    artworkWhatToDo: "Qué hacer: {fix}",
    artworkBlocked: "Corrige el diseño de arriba, o quítalo, para añadir este artículo a la cesta.",
  },

  basket: {
    title: "Tu cesta",
    emptyTitle: "Todavía no hay nada en la cesta",
    emptyBody:
      "Añade un producto con su personalización y aparecerá aquí, con la vista previa que acompañará a tu pedido.",
    browseShop: "Ir a la tienda",
    previewAlt: "Vista previa de {name}",
    personalisation: "Personalización:",
    artwork: "Diseño: {file}",
    quantity: "Cantidad",
    update: "Actualizar",
    remove: "Quitar",
    summary: "Resumen",
    subtotal: "Subtotal",
    shipping: "Envío",
    taxRow: "Impuestos {rate} %",
    taxIncludedSuffix: "incluidos",
    total: "Total",
    checkout: "Pagar",
    keepShopping: "Seguir comprando",
    viewBasket: "Ver la cesta",
    drawerIntro: "Un vistazo rápido a tu cesta. Las cantidades y los códigos de descuento están en la página completa de la cesta.",
  },

  discount: {
    title: "Código de descuento",
    label: "Código",
    placeholder: "SPRING10",
    apply: "Aplicar",
    applying: "Aplicando…",
    remove: "Quitar",
    row: "Descuento ({code})",
    applied: "Código {code} aplicado: {amount} de descuento.",
    removed: "Se ha quitado el código de descuento.",
    enterCode: "Introduce un código de descuento.",
    unknown: "No reconocemos ese código.",
    inactive: "Ese código ya no está activo.",
    expired: "Ese código ha caducado.",
    limitReached: "Ese código ya se ha usado el máximo de veces.",
    belowMinimum: "Ese código necesita una cesta de al menos {amount}.",
    dropped:
      "El código {code} ya no se aplica a esta cesta, así que se ha quitado. Revisa tu total antes de pagar.",
  },

  checkout: {
    title: "Pago",
    merchantNote:
      "{client} es el vendedor oficial. El pago se liquida en su propia cuenta de Stripe.",
    unavailableTitle: "Esta tienda todavía no puede aceptar pagos",
    unavailableBody:
      "La tienda no ha terminado de conectar su cuenta de Stripe. Tu cesta se conserva: inténtalo de nuevo cuando la tienda esté activa.",
    backToBasket: "Volver a la cesta",
    summaryTitle: "Resumen del pedido",
    shipping: "Envío",
    taxRow: "Impuestos {rate} %",
    taxIncludedSuffix: "incluidos",
    total: "Total",
    deliveryDetails: "Datos de envío",
    fullName: "Nombre completo",
    email: "Correo electrónico",
    emailHint: "Con esta dirección y tu código de pedido podrás volver a abrir la página del pedido.",
    street: "Dirección",
    city: "Población o ciudad",
    postalCode: "Código postal",
    country: "País",
    countryHint: "Empieza a escribir para encontrar tu país. La producción se asigna según el destino.",
    countrySearchPlaceholder: "Buscar países",
    countryNoMatch: "Ningún país coincide con «{query}».",
    payIn: "Pagar en",
    manualRoutingTitle: "El envío a {country} necesita asignación manual",
    manualRoutingLine: "{supplier} fabrica {products} y no realiza envíos a {country} ({region}).",
    productJoin: "y",
    manualRoutingBody:
      "Puedes pagar igualmente, pero el pedido quedará retenido para que una persona lo curse con otro socio de producción, así que tardará más de lo habitual. Elegir un país de entrega cubierto por tu proveedor evita la espera.",
    paymentTitle: "Pago",
    paymentNote:
      "Se cobra a través de la cuenta de Stripe de esta tienda {account}. La tienda nunca guarda los datos de la tarjeta.",
    cardNumber: "Número de tarjeta",
    expiry: "Caducidad (MM/AA)",
    securityCode: "Código de seguridad",
    testMode: "Modo de prueba de Stripe",
    submit: "Pagar y realizar el pedido",
    pending: "Procesando el pago…",
    cardSucceeds: "Visa — aceptada",
    cardDeclined: "Visa — rechazada por el banco",
    cardInsufficient: "Visa — saldo insuficiente",
  },

  order: {
    title: "Estado del pedido",
    lookupIntro:
      "Introduce tu código de pedido y el correo electrónico que indicaste al pagar. El enlace que guardaste al hacer el pedido lo abre directamente.",
    gateBody:
      "Para proteger los datos de envío y personalización, confirma el correo electrónico del pedido {code} antes de mostrarlo.",
    confirmedTitle: "Gracias: tu pedido está confirmado",
    confirmedBody:
      "Guarda esta página o añádela a favoritos: aquí se muestra el avance de tu pedido. Te hemos enviado un correo de confirmación con este enlace.",
    confirmedFindAgain:
      "También puedes volver a abrirla desde «Estado del pedido» con el código {code} y el correo electrónico {email}.",
    heading: "Pedido {code}",
    placed: "Realizado el {when}",
    trackWith: "Seguir con {carrier} ↗",
    whatYouOrdered: "Tu pedido",
    variantQuantity: "{variant} · cantidad {count}",
    personalisation: "Personalización:",
    previewAlt: "Vista previa de {name}",
    subtotal: "Subtotal",
    shipping: "Envío",
    taxRow: "Impuestos {rate} %",
    paid: "Pagado",
    refunded: "Reembolsado",
    deliveringTo: "Se entrega a",
    payment: "Pago",
    cardEnding: "Tarjeta terminada en {last4}",
    card: "Tarjeta",
    paidWord: "pagado",
    refundedWord: "reembolsado",
    merchantOfRecord: "{client} es el vendedor oficial.",
    progress: "Seguimiento",
    supportTitle: "¿Dudas sobre este pedido?",
    contactSubject: "Pedido {code}",
    continueShopping: "Seguir comprando",
    contactStore: "Contactar con la tienda",
    orderCode: "Código de pedido",
    orderCodeHint: "Empieza por ORD- y aparece arriba en la página de tu pedido.",
    emailOnOrder: "Correo del pedido",
    emailHint: "La dirección que indicaste al pagar.",
    lookupSubmit: "Ver mi pedido",
    lookupPending: "Comprobando…",
  },

  status: {
    awaitingPayment: "Pendiente de pago",
    awaitingPaymentNote: "Todavía no hemos recibido el pago de este pedido.",
    paid: "Pago recibido",
    paidNote: "Tu pedido está en cola para producción.",
    inProduction: "En producción",
    inProductionNote: "Tu artículo se está imprimiendo y acabando.",
    shipped: "Enviado",
    shippedNote: "Tu paquete está en camino. Síguelo con el enlace de abajo.",
    delivered: "Entregado",
    deliveredNote: "Tu paquete se ha entregado. Que lo disfrutes.",
    cancelled: "Cancelado",
    cancelledNote: "Este pedido se canceló. Cualquier pago se ha reembolsado.",
    exception: "Requiere atención",
    exceptionNote:
      "Este pedido está retenido. El equipo de la tienda se está ocupando y se pondrá en contacto contigo.",
  },

  actions: {
    storeClosed: "Esta tienda no está aceptando pedidos en este momento.",
    productGone: "Ese producto ya no está disponible.",
    chooseVariant: "Elige una talla y un color.",
    outOfStock: "{variant} está agotado. Elige otra opción.",
    noTextPersonalisation: "Este producto no se puede personalizar con texto.",
    textTooLong: "Limita la personalización a {max} caracteres como máximo.",
    noArtworkUpload: "Este producto no admite diseños subidos.",
    productUnavailable: "Este producto no está disponible temporalmente.",
    fileTooLarge: "Ese archivo ocupa {size} MB. El límite es de {limit} MB.",
    basketUnavailable: "No se ha podido abrir tu cesta. Activa las cookies e inténtalo de nuevo.",
    addedToBasket: "{product} se ha añadido a tu cesta.",
    basketEmpty: "Tu cesta está vacía.",
    enterName: "Indica el nombre para la entrega.",
    enterEmail: "Indica un correo electrónico: es con lo que volverás a abrir tu pedido.",
    enterStreet: "Indica la dirección.",
    enterCity: "Indica la población o ciudad.",
    enterPostalCode: "Indica el código postal.",
    chooseCountry: "Elige tu país de entrega en la lista.",
    currencyNotSold: "{currency} no es una de las monedas de venta de esta tienda.",
    enterOrderCode: "Introduce tu código de pedido.",
    enterOrderEmail: "Introduce el correo electrónico del pedido.",
    lookupFailed:
      "No hemos podido relacionar ese código de pedido con ese correo. Revisa ambos e inténtalo de nuevo.",
  },

  artwork: {
    lowDpi: "Esta imagen se imprimirá a {dpi} DPI, por debajo de los {required} DPI que necesita este producto.",
    lowDpiFix:
      "Sube una de al menos {pixels} píxeles de ancho, o reduce el diseño: este archivo se ve nítido hasta {width} mm de ancho.",
    badFormat: "Los archivos {format} no se admiten en este producto.",
    badFormatFix: "Guarda el diseño como {formats} y vuelve a seleccionarlo.",
    unreadableFormat: "Los archivos {format} no se pueden medir ni previsualizar aquí.",
    unreadableFormatFix: "Guarda el diseño como {formats} y vuelve a seleccionarlo.",
    fileTooLarge: "Ese archivo ocupa {size} MB. El límite es de {limit} MB.",
    fileTooLargeFix: "Guárdalo con menos tamaño o calidad y vuelve a seleccionarlo.",
    tooManyPixels: "Esa imagen es demasiado grande. El límite es de {megapixels} megapíxeles.",
    tooManyPixelsFix: "Redimensiónala en tu editor de fotos y vuelve a seleccionarla.",
    noTransparency:
      "Este producto se imprime directamente sobre la tela, así que el diseño necesita fondo transparente.",
    noTransparencyFix: "Quita el fondo y guárdalo como PNG con transparencia.",
    outsideArea: "Parte del diseño queda fuera del área imprimible y se cortaría.",
    outsideAreaFix:
      "Arrástralo dentro del recuadro discontinuo, o hazlo más pequeño para que quepa en {width} × {height} mm.",
    dpiTight: "Esta imagen se imprimirá a {dpi} DPI, justo por encima del mínimo de {required} DPI.",
    dpiTightFix:
      "Las líneas finas pueden verse suaves. Un archivo más grande, o un diseño algo menor, imprime más nítido.",
    verySmall: "El diseño ocupa menos del 15 % del ancho imprimible.",
    verySmallFix: "Sube el control de tamaño si va a ser el gráfico principal.",
    generic: "Ese diseño no se puede imprimir en este producto.",
    genericFix: "Prueba con otro archivo.",
  },

  payment: {
    accountNotReady:
      "Esta tienda no ha terminado de conectar su cuenta de Stripe, así que los pagos no están disponibles.",
    currencyUnsupported: "{currency} no es una de las monedas de venta de esta tienda.",
    invalidNumber: "Ese número de tarjeta no es válido. Revisa los dígitos e inténtalo de nuevo.",
    invalidExpiry: "La fecha de caducidad ya pasó o tiene un formato incorrecto. Usa MM/AA.",
    invalidCvc: "El código de seguridad debe tener 3 o 4 dígitos.",
    declined: "El banco emisor ha rechazado tu tarjeta.",
    insufficientFunds: "Tu tarjeta no tiene saldo suficiente.",
    expiredCard: "Tu tarjeta ha caducado.",
  },

  sections: {
    viewAll: "Ver todo",
    noProducts:
      "Todavía no hay productos publicados en esta tienda. Los productos publicados aparecen aquí automáticamente.",
    previewSoon: "Vista previa muy pronto",
    imagePlaceholder: "Añade la URL de una imagen en los ajustes de la sección",
    newsletterEmail: "Correo electrónico",
    notifyMe: "Avisadme",
    welcome: "Bienvenido",
  },

  email: {
    logoAlt: "{store}",
    greeting: "Hola {name}:",
    footer: "{client} es el comerciante responsable de esta tienda. Enviado por {store}.",
    support: "¿Dudas? Escríbenos a {email}.",
    orderSubject: "Pedido {code} confirmado — {store}",
    orderHeading: "Gracias por tu pedido",
    orderBody:
      "Hemos recibido tu pedido {code} y el pago se ha completado. El enlace de abajo abre su seguimiento en cualquier momento: guárdalo.",
    orderCta: "Ver mi pedido",
    orderTotalLabel: "Total pagado",
    orderDeliveryLabel: "Envío a",
    shippedSubject: "El pedido {code} está en camino — {store}",
    shippedHeading: "Tu paquete está en camino",
    shippedBody: "El pedido {code} se ha entregado a {carrier}.",
    shippedTrackingLabel: "Número de seguimiento",
    shippedCta: "Seguir el paquete",
    inviteSubject: "{inviter} te ha invitado a {store}",
    inviteHeading: "Te han invitado a {store}",
    inviteBody:
      "{inviter} te invita a trabajar en {store} como {role}. Al abrir el enlace de abajo se crea tu cuenta y se activa tu acceso. Funciona una sola vez.",
    inviteCta: "Aceptar la invitación",
    approvalSubject: "La campaña de regalos {code} necesita tu aprobación — {store}",
    approvalHeading: "Una campaña de regalos espera tu aprobación",
    approvalBody:
      "{buyer} ha enviado «{campaign}» para {company}. No se cobra nada hasta que apruebes la lista.",
    approvalRecipientsLabel: "Destinatarios",
    approvalTotalLabel: "Total",
    approvalCta: "Revisar la lista",
  },

  gift: {
    chromeSubtitle: "Catálogo de regalos · {store}",
    private: "Privado",
    operatedBy:
      "Gestionado por {client}, que es el comerciante responsable. Los regalos se fabrican por encargo y se envían individualmente a cada destinatario.",
    supportTitle: "¿Dudas sobre una campaña?",
    supportPending: "{client} aún no ha publicado datos de contacto de soporte.",
    legal: "© {year} {client}. Regalos corporativos con tecnología de Parcelith.",

    closedTitle: "Este catálogo está cerrado",
    closedBody:
      "El programa de regalos de {company} está en pausa. Quien lo gestione puede reabrirlo; las campañas ya realizadas no se ven afectadas.",

    privateBadge: "Catálogo privado",
    inviteBody:
      "El catálogo de regalos de {company} está abierto a las personas invitadas. Confirme la dirección a la que se envió y entrará directamente.",
    linkOnlyBody:
      "Este catálogo se abre con el enlace privado que compartió la persona responsable del programa de {company}. Vuelva a usar ese enlace o pídale uno nuevo: los enlaces se renuevan cada vez que el programa cambia de manos.",
    gateEmail: "Correo de trabajo",
    gateEmailHint: "Tiene que ser una de las direcciones que invitó la persona responsable del programa.",
    gateSubmit: "Abrir el catálogo",
    gatePending: "Comprobando…",

    introFallback:
      "Regalos para {company}, fabricados por encargo y entregados individualmente a cada destinatario.",
    startOrder: "Iniciar un pedido masivo",
    spendLimitLabel: "Límite de gasto por destinatario",
    noLimit: "Sin límite",
    approvalLabel: "Aprobación",
    approvalRequired: "Obligatoria",
    approvalNotRequired: "No necesaria",
    recipientsLabel: "Destinatarios por campaña",
    recipientsUpTo: "Hasta {count}",
    emptyTitle: "Ahora mismo no hay regalos disponibles",
    emptyBody:
      "Nada de este catálogo está en producción en este momento. Quien gestione el programa sabrá cuándo vuelve a estar disponible.",
    giftsTitle: "Regalos de este catálogo",
    previewSoon: "Vista previa disponible en breve",
    overLimit: "Por encima del límite",
    sizes: "Tallas: {sizes}",
    oneSize: "Talla única",
    overLimitTitle: "Algunos regalos superan su límite de gasto",
    overLimitBody:
      "Un destinatario asignado a uno de ellos se rechaza al leer la lista, de modo que la fila puede corregirse antes de pedir una aprobación.",
    howItWorks: "Cómo funciona una campaña",
    step1Title: "Elija el regalo",
    step1Body:
      "Todo lo que aparece aquí ya se produce para este programa, en las tallas entre las que puede elegir su equipo.",
    step2Title: "Añada su lista de destinatarios",
    step2Body:
      "Péguela desde una hoja de cálculo o suba un CSV: nombres, direcciones, tallas y un mensaje opcional.",
    step3Title: "Aprobación",
    step3Body:
      "La lista llega con su total a quien debe aprobarla antes de pagar nada.",
    step4Title: "Un pago, un paquete para cada uno",
    step4Body:
      "Se le cobra una sola vez. Cada destinatario recibe su propio paquete y su propio seguimiento.",

    orderTitle: "Pedido masivo de regalos",
    campaignTitle: "Campaña de regalos",
    orderIntro:
      "Añada a todas las personas a las que envía, con la dirección de entrega y la talla que usan. Revise la lista tantas veces como quiera: no se crea nada hasta que la envíe{approval}.",
    orderIntroApproval: " para su aprobación",
    paymentPendingTitle: "Esta tienda todavía no tiene los pagos activados",
    paymentPendingBody:
      "Aún puede preparar una campaña y enviarla para su aprobación. No podrá pagarse hasta que {client} termine de conectar su cuenta de pagos.",
    yourApprover: "la persona que aprueba",

    buyerTitle: "Quién hace el pedido",
    campaignName: "Nombre de la campaña",
    campaignNamePlaceholder: "Regalos de clientes del T4",
    buyerName: "Su nombre",
    orderingAs:
      "Pedido como {email}. Guarde el enlace de la campaña al que llegará a continuación: no se envía ningún correo y es en esa página donde aparecen la aprobación y el recibo.",
    buyerEmail: "Su correo de trabajo",
    buyerEmailHint:
      "Se registra en la campaña como comprador. Guarde el enlace de la campaña al que llegará a continuación: no se envía ningún correo y es en esa página donde aparecen la aprobación y el recibo.",
    giftTitle: "El regalo",
    giftHint: "Se usa en cada fila que no indique un producto propio.",
    giftHintLimit: "Por cada destinatario se pueden gastar hasta {amount}.",
    giftHintNoLimit: "Este programa no tiene límite de gasto.",
    listTitle: "Destinatarios",
    listHintLead: "Una persona por línea, hasta {max}. Columnas:",
    listHintTail:
      "La fila de encabezado se detecta automáticamente, y {product} y {note} son opcionales.",
    uploadCsv: "Subir un CSV",
    pasteExample: "Pegar el ejemplo",
    fileLoaded: "{file} cargado",
    fileTooLarge: "{file} tiene {size} KB. Las listas de destinatarios no llegan a {limit} KB.",
    fileUnreadable: "No se ha podido leer ese archivo. Guárdelo como CSV e inténtelo de nuevo.",
    listLabel: "Lista de destinatarios",
    checkList: "Revisar la lista",
    checkPending: "Leyendo la lista…",
    sendForApproval: "Enviar para aprobación",
    checkAndSend: "Revisar y enviar",
    sendPending: "Procesando…",
    previewRecipients: "{count} destinatarios",
    previewToFix: "{count} por corregir",
    previewTotal: "{amount} en total",
    previewOverflow: "{count} filas por encima del límite no se han leído",
    columnLine: "Línea",
    columnRecipient: "Destinatario",
    columnGift: "Regalo",
    columnDelivered: "Entregado",
    columnDelivery: "Entrega",
    columnValue: "Valor",
    noName: "Sin nombre",
    subtotal: "Regalos",
    shipping: "Envío",
    tax: "Impuestos",
    taxRow: "Impuestos {rate} %",
    total: "Total",
    approvalNote:
      "Al enviarla, la campaña pasa a {approver}. No se cobra nada hasta que se apruebe y usted pague.",
    noApprovalNote:
      "Este programa no necesita aprobación, así que pasará directamente al pago cuando la lista esté correcta.",

    linkInvalidTitle: "Este enlace de campaña no es válido",
    linkInvalidBody:
      "Los enlaces de campaña son personales: uno para el comprador y otro para quien aprueba. Pida que le reenvíen el suyo, o abra el catálogo y empiece un pedido nuevo.",
    backToCatalogue: "Volver al catálogo",
    campaignSubmitted: "{count} destinatarios · enviada por {buyer} el {when}",
    waitingTitle: "Pendiente de aprobación",
    waitingBody:
      "{approver} tiene la lista y su total. Podrá pagar en cuanto la apruebe: todavía no se ha cobrado nada.",
    decisionTitle: "Su decisión queda registrada",
    decisionBody: "{decision} por {who} el {when}.",
    decisionCanPay: "{buyer} ya puede pagarla: a usted no se le ha cobrado nada.",
    decisionApproved: "Aprobada",
    decisionDeclined: "Rechazada",
    declinedNoReason: "No se indicó ningún motivo.",
    declinedBody:
      "Empiece un pedido nuevo desde el catálogo con los cambios que le ha pedido quien aprueba.",
    orderedTitle: "Pagada y en producción",
    orderedBody:
      "Se han creado {count} pedidos, uno por destinatario, cada uno con su entrega y su seguimiento. Puede seguirlos abajo.",
    unpayableTitle: "Aprobada, pero la tienda aún no puede aceptar pagos",
    unpayableBody:
      "{client} no ha terminado de conectar su cuenta de pagos. Su campaña está guardada y podrá pagarse en cuanto lo haga.",
    recipientsTitle: "Destinatarios",
    track: "Seguir {code}",
    historyTitle: "Historial",
    totalsTitle: "Total de la campaña",
    spendLimitNote: "Límite de gasto de {amount} por destinatario.",
    noSpendLimitNote: "Este programa no tiene límite de gasto.",
    decisionFormTitle: "Su decisión",
    paymentTitle: "Pago",
    approvalIntro:
      "{buyer} necesita su visto bueno antes de poder pagar esta campaña. Aprobarla no cobra nada: el comprador paga en su propia pantalla.",
    noteLabel: "Nota (obligatoria para rechazar)",
    notePlaceholder: "Aprobada con cargo al presupuesto de marketing del T4.",
    approve: "Aprobar {total}",
    approvePending: "Registrando su decisión…",
    decline: "Rechazar",
    declinePending: "Registrando…",
    paymentIntro:
      "Un único pago por toda la campaña, cobrado a través de la cuenta de Stripe de la tienda {account}. Después, cada destinatario se convierte en su propio pedido con su propio seguimiento.",
    pay: "Pagar {total}",
    payPending: "Procesando el pago…",
    withdraw: "Retirar esta campaña",
    withdrawConfirm: "Retirar la campaña",
    withdrawQuestion: "La lista se retira y no se cobra a nadie.",
    withdrawPending: "Procesando…",
    cancel: "Cancelar",

    statusAwaitingApproval: "Pendiente de aprobación",
    statusApproved: "Aprobada, pendiente de pago",
    statusDeclined: "Rechazada",
    statusOrdered: "Pedida",
    statusCancelled: "Cancelada",

    eyebrow: "Portal de regalos",
    notFoundTitle: "No encontramos esa página",
    notFoundBody:
      "Puede que la dirección esté mal escrita, o que la campaña o el producto al que apuntaba se haya cerrado desde que se envió el enlace. El catálogo sigue abierto.",
    notFoundBoundaryBody:
      "Puede que el enlace haya caducado o que la empresa que creó el catálogo de regalos lo haya cerrado. Si alguien le envió este enlace, pídale uno actual.",
    errorTitle: "Algo ha ido mal por nuestra parte",
    errorBody:
      "No se ha podido cargar esta página. Nada de lo que ha enviado se ha perdido: inténtelo de nuevo y, si sigue ocurriendo, vuelva en unos minutos.",
    errorRetry: "Intentarlo de nuevo",
    errorReference: "Referencia {digest}",
    goToParcelith: "Ir a Parcelith",
  },

  fallback: {
    notFoundTitle: "No encontramos esa página",
    notFoundBody:
      "Puede que el enlace esté desactualizado o que el producto ya no esté a la venta. Todo lo que {store} vende hoy sigue a un clic.",
    browseProducts: "Ver todos los productos",
    errorTitle: "Algo ha fallado por nuestra parte",
    errorBody:
      "No se ha podido cargar esta página. Tu cesta sigue intacta: inténtalo de nuevo y, si el problema continúa, vuelve dentro de unos minutos.",
    errorRetry: "Reintentar",
    errorHome: "Volver a {store}",
    errorReference: "Referencia {digest}",
  },
};
