import type { StorefrontCopy } from "./en";

/** Storefront copy, French. */
export const fr: StorefrontCopy = {
  chrome: {
    shop: "Boutique",
    currencyLabel: "Devise",
    currencyApply: "Appliquer",
    basket: "Panier",
    basketWithCount: "Panier ({count})",
    operatedBy: "Exploité par {client}. Fabriqué à la commande et expédié dans le monde entier.",
    allProducts: "Tous les produits",
    orderStatus: "Suivi de commande",
    delivery: "Livraison",
    help: "Aide",
    supportEmailLabel: "E-mail",
    supportPhoneLabel: "Téléphone",
    supportPending: "Les coordonnées du service client ne sont pas encore publiées.",
    carriersPending: "Configuration des transporteurs en cours",
    pricesShownIn: "Prix affichés en {currency}{tax}.",
    taxIncluded: ", taxes comprises",
    taxAtCheckout: ", taxes ajoutées au paiement",
    legal:
      "© {year} {client}. {client} est le vendeur officiel de cette boutique. Boutique propulsée par Parcelith.",
  },

  meta: {
    homeTitle: "{store} — articles fabriqués à la commande",
    homeDescription:
      "Découvrez {store}, la boutique officielle de {client}. Imprimé à la demande et expédié dans le monde entier.",
    shopTitle: "Boutique — {store}",
    shopDescription: "Tous les produits disponibles chez {store}.",
  },

  home: {
    closedTitle: "Cette boutique est fermée",
    closedBody:
      "{client} a archivé {store}. Les commandes en cours sont toujours honorées et leurs pages de suivi restent accessibles.",
    comingSoonTitle: "{store} est presque prête",
    comingSoonBody: "La mise en page de la boutique n’a pas encore été publiée.",
    comingSoonWithProducts: "Les produits sont en ligne et peuvent déjà être consultés.",
    comingSoonNoProducts: "Revenez très bientôt.",
    browseProducts: "Voir les {count} produits",
  },

  shop: {
    title: "Toute la boutique",
    intro: "Fabriqué à la commande et expédié dans le monde entier. Prix en {currency}{tax}.",
    taxIncluded: ", taxes comprises",
    taxAtCheckout: " ; les taxes sont ajoutées au paiement",
    searchLabel: "Recherche",
    searchPlaceholder: "T-shirt, sweat, mug…",
    searchSubmit: "Rechercher",
    clear: "Effacer",
    filterByTag: "Filtrer par mot-clé",
    emptyTitle: "Rien de publié pour l’instant",
    emptyBody: "Cette boutique n’a encore publié aucun produit. Revenez bientôt.",
    noMatchTitle: "Aucun produit ne correspond à cette recherche",
    noMatchBody: "Essayez un autre terme ou effacez les filtres.",
    clearFilters: "Effacer les filtres",
    personalise: "Personnalisable",
    previewSoon: "Aperçu bientôt disponible",
  },

  product: {
    breadcrumb: "Fil d’Ariane",
    breadcrumbShop: "Boutique",
    about: "À propos de ce produit",
    madeToOrder: "Fabriqué à la commande",
    producedBy: "Fabriqué par {supplier} en {lead}, puis expédié avec {carriers}.",
    defaultSupplier: "notre partenaire de production",
    leadDays: "{from} à {to} jours",
    leadUnknown: "quelques jours",
    defaultCarrier: "notre transporteur",
    carrierJoin: "ou",
    printDetail: "Détail d’impression",
    printDetailBody: "{area}, {width} × {height} mm, imprimé à {dpi} DPI au minimum.",
    taxAndDelivery: "Taxes et livraison",
    pricesShownIn: "Prix affichés en {currency}{tax}.",
    taxIncluded: ", taxes comprises",
    taxAtCheckout: " ; les taxes sont calculées au paiement",
    merchantOfRecord: "{client} est le vendeur officiel de cette commande.",
  },

  purchase: {
    addToBasket: "Ajouter au panier",
    adding: "Ajout en cours…",
    viewBasket: "Voir le panier",
    colour: "Couleur",
    size: "Taille",
    option: "Option",
    required: "Obligatoire",
    quantity: "Quantité",
    lowStock: "stock faible",
    noPreview: "Aucun aperçu disponible",
    previewAlt: "Aperçu de {name}",
    viewAlt: "Vue {view}",
    livePreview:
      "Aperçu en direct. Une version fidèle à la production est jointe lorsque vous ajoutez l’article au panier.",
    textPlaceholder: "Facultatif",
    textCounter: "{count}/{max} caractères. Imprimé avec le motif.",
    artworkLabel: "Votre propre visuel",
    artworkHint:
      "Imprimé sur {width} × {height} mm, il faut donc au moins {dpi} DPI. {formats} jusqu’à {max} Mo.",
    artworkHintSimple: "PNG, JPG ou WEBP.",
    uploading: "Envoi de votre visuel…",
    uploadFailed: "Ce fichier n’a pas pu être envoyé.",
    fileTooLarge: "Ce fichier fait {size} Mo. La limite est de {limit} Mo.",
  },

  basket: {
    title: "Votre panier",
    emptyTitle: "Votre panier est vide",
    emptyBody:
      "Ajoutez un produit et sa personnalisation : il apparaîtra ici avec l’aperçu joint à votre commande.",
    browseShop: "Parcourir la boutique",
    previewAlt: "Aperçu de {name}",
    personalisation: "Personnalisation :",
    artwork: "Visuel : {file}",
    quantity: "Quantité",
    update: "Mettre à jour",
    remove: "Retirer",
    summary: "Récapitulatif",
    subtotal: "Sous-total",
    shipping: "Livraison",
    taxRow: "Taxes {rate} %",
    taxIncludedSuffix: "comprises",
    total: "Total",
    checkout: "Passer au paiement",
    keepShopping: "Continuer mes achats",
  },

  checkout: {
    title: "Paiement",
    merchantNote:
      "{client} est le vendeur officiel. Le paiement est versé sur son propre compte Stripe.",
    unavailableTitle: "Cette boutique ne peut pas encore encaisser de paiements",
    unavailableBody:
      "La boutique n’a pas terminé la connexion de son compte Stripe. Votre panier est conservé — réessayez dès que la boutique sera en ligne.",
    backToBasket: "Retour au panier",
    summaryTitle: "Récapitulatif de la commande",
    shipping: "Livraison",
    taxRow: "Taxes {rate} %",
    taxIncludedSuffix: "comprises",
    total: "Total",
    deliveryDetails: "Coordonnées de livraison",
    fullName: "Nom complet",
    email: "E-mail",
    emailHint: "Cette adresse et votre code de commande servent à rouvrir la page de votre commande.",
    street: "Adresse",
    city: "Ville",
    postalCode: "Code postal",
    country: "Pays",
    countryHint: "Commencez à saisir pour trouver votre pays. La production dépend de la destination.",
    countrySearchPlaceholder: "Rechercher un pays",
    countryNoMatch: "Aucun pays ne correspond à « {query} ».",
    payIn: "Payer en",
    manualRoutingTitle: "La livraison vers {country} demande un traitement manuel",
    manualRoutingLine: "{supplier} fabrique {products} et ne livre pas vers {country} ({region}).",
    productJoin: "et",
    manualRoutingBody:
      "Vous pouvez payer malgré tout, mais la commande sera mise en attente afin qu’une personne la passe auprès d’un autre partenaire de production : le délai sera donc plus long que d’habitude. Choisir un pays couvert par votre fabricant évite cette attente.",
    paymentTitle: "Paiement",
    paymentNote:
      "Débité via le compte Stripe de cette boutique {account}. Les données de carte ne sont jamais conservées par la boutique.",
    cardNumber: "Numéro de carte",
    expiry: "Expiration (MM/AA)",
    securityCode: "Code de sécurité",
    testMode: "Mode test Stripe",
    submit: "Payer et commander",
    pending: "Paiement en cours…",
    cardSucceeds: "Visa — acceptée",
    cardDeclined: "Visa — refusée par la banque",
    cardInsufficient: "Visa — provision insuffisante",
  },

  order: {
    title: "Suivi de commande",
    lookupIntro:
      "Saisissez votre code de commande et l’adresse e-mail indiquée au paiement. Le lien enregistré au moment de la commande l’ouvre directement.",
    gateBody:
      "Pour protéger les détails de livraison et de personnalisation, confirmez l’adresse e-mail de la commande {code} avant que nous l’affichions.",
    confirmedTitle: "Merci — votre commande est confirmée",
    confirmedBody:
      "Enregistrez cette page ou mettez-la en favori : c’est ici qu’apparaît l’avancement de votre commande. La boutique n’envoie pas encore d’e-mail de confirmation.",
    confirmedFindAgain:
      "Vous pouvez aussi la retrouver depuis « Suivi de commande » avec le code {code} et l’adresse e-mail {email}.",
    heading: "Commande {code}",
    placed: "Passée le {when}",
    trackWith: "Suivre avec {carrier} ↗",
    whatYouOrdered: "Votre commande",
    variantQuantity: "{variant} · quantité {count}",
    personalisation: "Personnalisation :",
    previewAlt: "Aperçu de {name}",
    subtotal: "Sous-total",
    shipping: "Livraison",
    taxRow: "Taxes {rate} %",
    paid: "Payé",
    refunded: "Remboursé",
    deliveringTo: "Livraison à",
    payment: "Paiement",
    cardEnding: "Carte se terminant par {last4}",
    card: "Carte",
    paidWord: "payée",
    refundedWord: "remboursée",
    merchantOfRecord: "{client} est le vendeur officiel.",
    progress: "Suivi",
    supportTitle: "Une question sur cette commande ?",
    contactSubject: "Commande {code}",
    continueShopping: "Continuer mes achats",
    contactStore: "Contacter la boutique",
    orderCode: "Code de commande",
    orderCodeHint: "Commence par ORD- et figure en haut de la page de votre commande.",
    emailOnOrder: "E-mail de la commande",
    emailHint: "L’adresse indiquée au moment du paiement.",
    lookupSubmit: "Afficher ma commande",
    lookupPending: "Vérification…",
  },

  status: {
    awaitingPayment: "En attente de paiement",
    awaitingPaymentNote: "Nous n’avons pas encore reçu le paiement de cette commande.",
    paid: "Paiement reçu",
    paidNote: "Votre commande est en file d’attente pour la production.",
    inProduction: "En production",
    inProductionNote: "Votre article est en cours d’impression et de finition.",
    shipped: "Expédiée",
    shippedNote: "Votre colis est en route. Suivez-le avec le lien ci-dessous.",
    delivered: "Livrée",
    deliveredNote: "Votre colis a été livré. Profitez-en bien.",
    cancelled: "Annulée",
    cancelledNote: "Cette commande a été annulée. Tout paiement a été remboursé.",
    exception: "Nécessite une intervention",
    exceptionNote:
      "Cette commande est bloquée. L’équipe de la boutique s’en occupe et vous recontactera.",
  },

  actions: {
    storeClosed: "Cette boutique ne prend pas de commandes actuellement.",
    productGone: "Ce produit n’est plus disponible.",
    chooseVariant: "Choisissez une taille et une couleur.",
    outOfStock: "{variant} est en rupture de stock. Choisissez une autre option.",
    noTextPersonalisation: "Ce produit ne peut pas être personnalisé avec du texte.",
    textTooLong: "Limitez la personnalisation à {max} caractères au maximum.",
    noArtworkUpload: "Ce produit n’accepte pas de visuel envoyé.",
    productUnavailable: "Ce produit est temporairement indisponible.",
    fileTooLarge: "Ce fichier fait {size} Mo. La limite est de {limit} Mo.",
    basketUnavailable: "Votre panier n’a pas pu être ouvert. Activez les cookies et réessayez.",
    addedToBasket: "{product} a été ajouté à votre panier.",
    basketEmpty: "Votre panier est vide.",
    enterName: "Indiquez le nom pour la livraison.",
    enterEmail: "Indiquez une adresse e-mail : c’est avec elle que vous rouvrirez votre commande.",
    enterStreet: "Indiquez l’adresse.",
    enterCity: "Indiquez la ville.",
    enterPostalCode: "Indiquez le code postal.",
    chooseCountry: "Choisissez votre pays de livraison dans la liste.",
    currencyNotSold: "{currency} ne fait pas partie des devises de vente de cette boutique.",
    enterOrderCode: "Saisissez votre code de commande.",
    enterOrderEmail: "Saisissez l’adresse e-mail de la commande.",
    lookupFailed:
      "Le code de commande et l’adresse e-mail ne correspondent pas. Vérifiez les deux et réessayez.",
  },

  artwork: {
    lowDpi:
      "Ce visuel s’imprime à une résolution trop faible. Envoyez un fichier d’au moins {dpi} DPI.",
    badFormat: "Les fichiers {format} ne sont pas acceptés pour ce produit. Envoyez plutôt {formats}.",
    fileTooLarge: "Ce fichier fait {size} Mo. La limite est de {limit} Mo.",
    tooManyPixels:
      "Cette image est trop grande. Réduisez-la sous {megapixels} mégapixels et réessayez.",
    noTransparency:
      "Ce produit demande un visuel sur fond transparent. Exportez-le en PNG avec transparence.",
    generic: "Ce visuel ne peut pas être imprimé sur ce produit. Essayez un autre fichier.",
  },

  payment: {
    accountNotReady:
      "Cette boutique n’a pas terminé la connexion de son compte Stripe, les paiements sont donc indisponibles.",
    currencyUnsupported: "{currency} ne fait pas partie des devises de vente de cette boutique.",
    invalidNumber: "Ce numéro de carte n’est pas valide. Vérifiez les chiffres et réessayez.",
    invalidExpiry: "La date d’expiration est passée ou mal formatée. Utilisez MM/AA.",
    invalidCvc: "Le code de sécurité doit comporter 3 ou 4 chiffres.",
    declined: "Votre carte a été refusée par la banque émettrice.",
    insufficientFunds: "Votre carte ne dispose pas d’une provision suffisante.",
    expiredCard: "Votre carte a expiré.",
  },

  sections: {
    viewAll: "Tout voir",
    noProducts:
      "Aucun produit n’est encore publié dans cette boutique. Les produits publiés apparaissent ici automatiquement.",
    previewSoon: "Aperçu bientôt disponible",
    imagePlaceholder: "Ajoutez une URL d’image dans les réglages de la section",
    newsletterEmail: "Adresse e-mail",
    notifyMe: "Me prévenir",
    welcome: "Bienvenue",
  },

  fallback: {
    notFoundTitle: "Cette page est introuvable",
    notFoundBody:
      "Le lien est peut-être obsolète ou le produit n’est plus en vente. Tout ce que {store} propose aujourd’hui reste à portée de clic.",
    browseProducts: "Voir tous les produits",
    errorTitle: "Un problème est survenu de notre côté",
    errorBody:
      "Cette page n’a pas pu être chargée. Votre panier est intact — réessayez, et si cela persiste revenez dans quelques minutes.",
    errorRetry: "Réessayer",
    errorHome: "Retour à {store}",
    errorReference: "Référence {digest}",
  },
};
