import type { StorefrontCopy } from "./en";

/** Storefront copy, French. */
export const fr: StorefrontCopy = {
  chrome: {
    shop: "Boutique",
    currencyLabel: "Devise",
    currencyApply: "Appliquer",
    basket: "Panier",
    basketWithCount: "Panier ({count})",
    basketClose: "Fermer le panier",
    operatedBy: "Exploité par {client}. Fabriqué à la commande et expédié dans le monde entier.",
    allProducts: "Tous les produits",
    orderStatus: "Suivi de commande",
    delivery: "Livraison",
    help: "Aide",
    supportEmailLabel: "E-mail",
    supportPhoneLabel: "Téléphone",
    supportPending: "Les coordonnées du service client ne sont pas encore publiées.",
    carriersPending: "Configuration des transporteurs en cours",
    pricesShownIn: "Prix affichés en {currency}{tax}.",
    taxIncluded: ", taxes comprises",
    taxAtCheckout: ", taxes ajoutées au paiement",
    legal:
      "© {year} {client}. {client} est le vendeur officiel de cette boutique. Boutique propulsée par Parcelith.",
  },

  meta: {
    homeTitle: "{store} — articles fabriqués à la commande",
    homeDescription:
      "Découvrez {store}, la boutique officielle de {client}. Imprimé à la demande et expédié dans le monde entier.",
    taglineDescription:
      "{tagline} Découvrez {store}, la boutique officielle de {client}.",
    shopTitle: "Boutique",
    shopDescription: "Tous les produits disponibles chez {store}.",
  },

  home: {
    closedTitle: "Cette boutique est fermée",
    closedBody:
      "{client} a archivé {store}. Les commandes en cours sont toujours honorées et leurs pages de suivi restent accessibles.",
    comingSoonTitle: "{store} est presque prête",
    comingSoonBody: "La mise en page de la boutique n’a pas encore été publiée.",
    comingSoonWithProducts: "Les produits sont en ligne et peuvent déjà être consultés.",
    comingSoonNoProducts: "Revenez très bientôt.",
    browseProducts: "Voir les {count} produits",
  },

  shop: {
    title: "Toute la boutique",
    intro: "Fabriqué à la commande et expédié dans le monde entier. Prix en {currency}{tax}.",
    taxIncluded: ", taxes comprises",
    taxAtCheckout: " ; les taxes sont ajoutées au paiement",
    searchLabel: "Recherche",
    searchPlaceholder: "T-shirt, sweat, mug…",
    searchSubmit: "Rechercher",
    clear: "Effacer",
    filterByTag: "Filtrer par mot-clé",
    emptyTitle: "Rien de publié pour l’instant",
    emptyBody: "Cette boutique n’a encore publié aucun produit. Revenez bientôt.",
    noMatchTitle: "Aucun produit ne correspond à cette recherche",
    noMatchBody: "Essayez un autre terme ou effacez les filtres.",
    clearFilters: "Effacer les filtres",
    personalise: "Personnalisable",
    previewSoon: "Aperçu bientôt disponible",
  },

  product: {
    breadcrumb: "Fil d’Ariane",
    breadcrumbShop: "Boutique",
    about: "À propos de ce produit",
    madeToOrder: "Fabriqué à la commande",
    producedBy: "Fabriqué par {supplier} en {lead}, puis expédié avec {carriers}.",
    defaultSupplier: "notre partenaire de production",
    leadDays: "{from} à {to} jours",
    leadUnknown: "quelques jours",
    defaultCarrier: "notre transporteur",
    carrierJoin: "ou",
    printDetail: "Détail d’impression",
    printDetailBody: "{area}, {width} × {height} mm, imprimé à {dpi} DPI au minimum.",
    taxAndDelivery: "Taxes et livraison",
    pricesShownIn: "Prix affichés en {currency}{tax}.",
    taxIncluded: ", taxes comprises",
    taxAtCheckout: " ; les taxes sont calculées au paiement",
    merchantOfRecord: "{client} est le vendeur officiel de cette commande.",
  },

  purchase: {
    addToBasket: "Ajouter au panier",
    adding: "Ajout en cours…",
    viewBasket: "Voir le panier",
    colour: "Couleur",
    size: "Taille",
    option: "Option",
    required: "Obligatoire",
    quantity: "Quantité",
    lowStock: "stock faible",
    noPreview: "Aucun aperçu disponible",
    previewAlt: "Aperçu de {name}",
    viewAlt: "Vue {view}",
    livePreview:
      "Aperçu en direct. Une version fidèle à la production est jointe lorsque vous ajoutez l’article au panier.",
    textPlaceholder: "Facultatif",
    textCounter: "{count}/{max} caractères. Imprimé avec le motif.",
    artworkLabel: "Votre propre visuel",
    artworkHint:
      "Imprimé sur {width} × {height} mm, il faut donc au moins {dpi} DPI. {formats} jusqu’à {max} Mo.",
    artworkHintSimple: "PNG, JPG ou WEBP.",
    uploading: "Envoi de votre visuel…",
    uploadFailed: "Ce fichier n’a pas pu être envoyé.",
    fileTooLarge: "Ce fichier fait {size} Mo. La limite est de {limit} Mo.",
    artworkPlacementTitle: "Positionnez votre visuel",
    artworkPlacementHelp:
      "Faites glisser le visuel sur l’aperçu ou utilisez les réglages ci-dessous. L’aperçu et la résolution d’impression suivent chaque changement.",
    artworkGrabLabel:
      "Position de {file}. Faites glisser pour déplacer ou utilisez les flèches ; + et − redimensionnent.",
    artworkSize: "Taille",
    artworkRotation: "Rotation",
    artworkResolution: "Résolution d’impression",
    artworkRecentre: "Recentrer",
    artworkRemove: "Retirer le visuel",
    artworkChecksPass: "Ce visuel est prêt à être imprimé à cette taille.",
    artworkChecksFail: "À corriger avant l’ajout au panier",
    artworkWhatToDo: "À faire : {fix}",
    artworkBlocked:
      "Corrigez le visuel ci-dessus, ou retirez-le, pour ajouter cet article au panier.",
  },

  basket: {
    title: "Votre panier",
    emptyTitle: "Votre panier est vide",
    emptyBody:
      "Ajoutez un produit et sa personnalisation : il apparaîtra ici avec l’aperçu joint à votre commande.",
    browseShop: "Parcourir la boutique",
    previewAlt: "Aperçu de {name}",
    personalisation: "Personnalisation :",
    artwork: "Visuel : {file}",
    quantity: "Quantité",
    update: "Mettre à jour",
    remove: "Retirer",
    summary: "Récapitulatif",
    subtotal: "Sous-total",
    shipping: "Livraison",
    taxRow: "Taxes {rate} %",
    taxIncludedSuffix: "comprises",
    total: "Total",
    checkout: "Passer au paiement",
    keepShopping: "Continuer mes achats",
  },

  discount: {
    title: "Code de réduction",
    label: "Code",
    placeholder: "SPRING10",
    apply: "Appliquer",
    applying: "Application…",
    remove: "Retirer",
    row: "Réduction ({code})",
    applied: "Code {code} appliqué — {amount} de remise.",
    removed: "Le code de réduction a été retiré.",
    enterCode: "Saisissez un code de réduction.",
    unknown: "Nous ne reconnaissons pas ce code.",
    inactive: "Ce code n’est plus actif.",
    expired: "Ce code a expiré.",
    limitReached: "Ce code a déjà été utilisé le nombre maximal de fois.",
    belowMinimum: "Ce code exige un panier d’au moins {amount}.",
    dropped:
      "Le code {code} ne s’applique plus à ce panier et a été retiré. Vérifiez votre total avant de payer.",
  },

  checkout: {
    title: "Paiement",
    merchantNote:
      "{client} est le vendeur officiel. Le paiement est versé sur son propre compte Stripe.",
    unavailableTitle: "Cette boutique ne peut pas encore encaisser de paiements",
    unavailableBody:
      "La boutique n’a pas terminé la connexion de son compte Stripe. Votre panier est conservé — réessayez dès que la boutique sera en ligne.",
    backToBasket: "Retour au panier",
    summaryTitle: "Récapitulatif de la commande",
    shipping: "Livraison",
    taxRow: "Taxes {rate} %",
    taxIncludedSuffix: "comprises",
    total: "Total",
    deliveryDetails: "Coordonnées de livraison",
    fullName: "Nom complet",
    email: "E-mail",
    emailHint: "Cette adresse et votre code de commande servent à rouvrir la page de votre commande.",
    street: "Adresse",
    city: "Ville",
    postalCode: "Code postal",
    country: "Pays",
    countryHint: "Commencez à saisir pour trouver votre pays. La production dépend de la destination.",
    countrySearchPlaceholder: "Rechercher un pays",
    countryNoMatch: "Aucun pays ne correspond à « {query} ».",
    payIn: "Payer en",
    manualRoutingTitle: "La livraison vers {country} demande un traitement manuel",
    manualRoutingLine: "{supplier} fabrique {products} et ne livre pas vers {country} ({region}).",
    productJoin: "et",
    manualRoutingBody:
      "Vous pouvez payer malgré tout, mais la commande sera mise en attente afin qu’une personne la passe auprès d’un autre partenaire de production : le délai sera donc plus long que d’habitude. Choisir un pays couvert par votre fabricant évite cette attente.",
    paymentTitle: "Paiement",
    paymentNote:
      "Débité via le compte Stripe de cette boutique {account}. Les données de carte ne sont jamais conservées par la boutique.",
    cardNumber: "Numéro de carte",
    expiry: "Expiration (MM/AA)",
    securityCode: "Code de sécurité",
    testMode: "Mode test Stripe",
    submit: "Payer et commander",
    pending: "Paiement en cours…",
    cardSucceeds: "Visa — acceptée",
    cardDeclined: "Visa — refusée par la banque",
    cardInsufficient: "Visa — provision insuffisante",
  },

  order: {
    title: "Suivi de commande",
    lookupIntro:
      "Saisissez votre code de commande et l’adresse e-mail indiquée au paiement. Le lien enregistré au moment de la commande l’ouvre directement.",
    gateBody:
      "Pour protéger les détails de livraison et de personnalisation, confirmez l’adresse e-mail de la commande {code} avant que nous l’affichions.",
    confirmedTitle: "Merci — votre commande est confirmée",
    confirmedBody:
      "Enregistrez cette page ou mettez-la en favori : c’est ici qu’apparaît l’avancement de votre commande. Un e-mail de confirmation contenant ce lien vous a été envoyé.",
    confirmedFindAgain:
      "Vous pouvez aussi la retrouver depuis « Suivi de commande » avec le code {code} et l’adresse e-mail {email}.",
    heading: "Commande {code}",
    placed: "Passée le {when}",
    trackWith: "Suivre avec {carrier} ↗",
    whatYouOrdered: "Votre commande",
    variantQuantity: "{variant} · quantité {count}",
    personalisation: "Personnalisation :",
    previewAlt: "Aperçu de {name}",
    subtotal: "Sous-total",
    shipping: "Livraison",
    taxRow: "Taxes {rate} %",
    paid: "Payé",
    refunded: "Remboursé",
    deliveringTo: "Livraison à",
    payment: "Paiement",
    cardEnding: "Carte se terminant par {last4}",
    card: "Carte",
    paidWord: "payée",
    refundedWord: "remboursée",
    merchantOfRecord: "{client} est le vendeur officiel.",
    progress: "Suivi",
    supportTitle: "Une question sur cette commande ?",
    contactSubject: "Commande {code}",
    continueShopping: "Continuer mes achats",
    contactStore: "Contacter la boutique",
    orderCode: "Code de commande",
    orderCodeHint: "Commence par ORD- et figure en haut de la page de votre commande.",
    emailOnOrder: "E-mail de la commande",
    emailHint: "L’adresse indiquée au moment du paiement.",
    lookupSubmit: "Afficher ma commande",
    lookupPending: "Vérification…",
  },

  status: {
    awaitingPayment: "En attente de paiement",
    awaitingPaymentNote: "Nous n’avons pas encore reçu le paiement de cette commande.",
    paid: "Paiement reçu",
    paidNote: "Votre commande est en file d’attente pour la production.",
    inProduction: "En production",
    inProductionNote: "Votre article est en cours d’impression et de finition.",
    shipped: "Expédiée",
    shippedNote: "Votre colis est en route. Suivez-le avec le lien ci-dessous.",
    delivered: "Livrée",
    deliveredNote: "Votre colis a été livré. Profitez-en bien.",
    cancelled: "Annulée",
    cancelledNote: "Cette commande a été annulée. Tout paiement a été remboursé.",
    exception: "Nécessite une intervention",
    exceptionNote:
      "Cette commande est bloquée. L’équipe de la boutique s’en occupe et vous recontactera.",
  },

  actions: {
    storeClosed: "Cette boutique ne prend pas de commandes actuellement.",
    productGone: "Ce produit n’est plus disponible.",
    chooseVariant: "Choisissez une taille et une couleur.",
    outOfStock: "{variant} est en rupture de stock. Choisissez une autre option.",
    noTextPersonalisation: "Ce produit ne peut pas être personnalisé avec du texte.",
    textTooLong: "Limitez la personnalisation à {max} caractères au maximum.",
    noArtworkUpload: "Ce produit n’accepte pas de visuel envoyé.",
    productUnavailable: "Ce produit est temporairement indisponible.",
    fileTooLarge: "Ce fichier fait {size} Mo. La limite est de {limit} Mo.",
    basketUnavailable: "Votre panier n’a pas pu être ouvert. Activez les cookies et réessayez.",
    addedToBasket: "{product} a été ajouté à votre panier.",
    basketEmpty: "Votre panier est vide.",
    enterName: "Indiquez le nom pour la livraison.",
    enterEmail: "Indiquez une adresse e-mail : c’est avec elle que vous rouvrirez votre commande.",
    enterStreet: "Indiquez l’adresse.",
    enterCity: "Indiquez la ville.",
    enterPostalCode: "Indiquez le code postal.",
    chooseCountry: "Choisissez votre pays de livraison dans la liste.",
    currencyNotSold: "{currency} ne fait pas partie des devises de vente de cette boutique.",
    enterOrderCode: "Saisissez votre code de commande.",
    enterOrderEmail: "Saisissez l’adresse e-mail de la commande.",
    lookupFailed:
      "Le code de commande et l’adresse e-mail ne correspondent pas. Vérifiez les deux et réessayez.",
  },

  artwork: {
    lowDpi: "Ce visuel s’imprimera à {dpi} DPI, en dessous des {required} DPI exigés par ce produit.",
    lowDpiFix:
      "Envoyez un fichier d’au moins {pixels} pixels de large, ou réduisez le visuel — ce fichier reste net jusqu’à {width} mm de large.",
    badFormat: "Les fichiers {format} ne sont pas acceptés pour ce produit.",
    badFormatFix: "Enregistrez le visuel en {formats} et sélectionnez-le à nouveau.",
    unreadableFormat: "Les fichiers {format} ne peuvent être ni mesurés ni prévisualisés ici.",
    unreadableFormatFix: "Enregistrez le visuel en {formats} et sélectionnez-le à nouveau.",
    fileTooLarge: "Ce fichier fait {size} Mo. La limite est de {limit} Mo.",
    fileTooLargeFix:
      "Enregistrez-le dans une taille ou une qualité inférieure, puis sélectionnez-le à nouveau.",
    tooManyPixels: "Cette image est trop grande. La limite est de {megapixels} mégapixels.",
    tooManyPixelsFix: "Redimensionnez-la dans votre éditeur photo et sélectionnez-la à nouveau.",
    noTransparency:
      "Ce produit est imprimé directement sur le tissu : le visuel doit avoir un fond transparent.",
    noTransparencyFix: "Supprimez le fond et enregistrez-le en PNG avec transparence.",
    outsideArea: "Une partie du visuel dépasse de la zone imprimable et serait coupée.",
    outsideAreaFix:
      "Ramenez-le à l’intérieur du cadre en pointillés, ou réduisez-le pour tenir dans {width} × {height} mm.",
    dpiTight: "Ce visuel s’imprimera à {dpi} DPI, tout juste au-dessus du minimum de {required} DPI.",
    dpiTightFix:
      "Les traits fins risquent d’être flous. Un fichier plus grand, ou un visuel un peu plus petit, sera plus net.",
    verySmall: "Le visuel couvre moins de 15 % de la largeur imprimable.",
    verySmallFix: "Augmentez la taille s’il doit être le graphisme principal.",
    generic: "Ce visuel ne peut pas être imprimé sur ce produit.",
    genericFix: "Essayez un autre fichier.",
  },

  payment: {
    accountNotReady:
      "Cette boutique n’a pas terminé la connexion de son compte Stripe, les paiements sont donc indisponibles.",
    currencyUnsupported: "{currency} ne fait pas partie des devises de vente de cette boutique.",
    invalidNumber: "Ce numéro de carte n’est pas valide. Vérifiez les chiffres et réessayez.",
    invalidExpiry: "La date d’expiration est passée ou mal formatée. Utilisez MM/AA.",
    invalidCvc: "Le code de sécurité doit comporter 3 ou 4 chiffres.",
    declined: "Votre carte a été refusée par la banque émettrice.",
    insufficientFunds: "Votre carte ne dispose pas d’une provision suffisante.",
    expiredCard: "Votre carte a expiré.",
  },

  sections: {
    viewAll: "Tout voir",
    noProducts:
      "Aucun produit n’est encore publié dans cette boutique. Les produits publiés apparaissent ici automatiquement.",
    previewSoon: "Aperçu bientôt disponible",
    imagePlaceholder: "Ajoutez une URL d’image dans les réglages de la section",
    newsletterEmail: "Adresse e-mail",
    notifyMe: "Me prévenir",
    welcome: "Bienvenue",
  },

  email: {
    logoAlt: "{store}",
    greeting: "Bonjour {name},",
    footer: "{client} est le marchand officiel de cette boutique. Envoyé par {store}.",
    support: "Une question ? Écrivez-nous à {email}.",
    orderSubject: "Commande {code} confirmée — {store}",
    orderHeading: "Merci pour votre commande",
    orderBody:
      "Nous avons bien reçu votre commande {code} et votre paiement a été accepté. Le lien ci-dessous ouvre son suivi à tout moment — conservez-le.",
    orderCta: "Voir ma commande",
    orderTotalLabel: "Total payé",
    orderDeliveryLabel: "Livraison à",
    shippedSubject: "La commande {code} est en route — {store}",
    shippedHeading: "Votre colis est en route",
    shippedBody: "La commande {code} a été remise à {carrier}.",
    shippedTrackingLabel: "Numéro de suivi",
    shippedCta: "Suivre mon colis",
    inviteSubject: "{inviter} vous a invité·e sur {store}",
    inviteHeading: "Vous êtes invité·e sur {store}",
    inviteBody:
      "{inviter} vous invite à travailler sur {store} en tant que {role}. Le lien ci-dessous crée votre compte et active votre accès. Il ne fonctionne qu’une fois.",
    inviteCta: "Accepter l’invitation",
    approvalSubject: "La campagne cadeaux {code} attend votre validation — {store}",
    approvalHeading: "Une campagne cadeaux attend votre validation",
    approvalBody:
      "{buyer} a soumis « {campaign} » pour {company}. Rien n’est débité tant que vous n’avez pas validé la liste.",
    approvalRecipientsLabel: "Destinataires",
    approvalTotalLabel: "Total",
    approvalCta: "Examiner la liste",
  },

  gift: {
    chromeSubtitle: "Catalogue cadeaux · {store}",
    private: "Privé",
    operatedBy:
      "Exploité par {client}, qui est le marchand officiel. Les cadeaux sont fabriqués à la commande et expédiés individuellement à chaque destinataire.",
    supportTitle: "Une question sur une campagne :",
    supportPending: "{client} n’a pas encore publié de coordonnées d’assistance.",
    legal: "© {year} {client}. Cadeaux d’entreprise propulsés par Parcelith.",

    closedTitle: "Ce catalogue est fermé",
    closedBody:
      "Le programme de cadeaux de {company} est en pause. La personne qui le gère pour vous peut le réouvrir — les campagnes déjà passées ne sont pas affectées.",

    privateBadge: "Catalogue privé",
    inviteBody:
      "Le catalogue cadeaux de {company} est ouvert aux collègues invités. Confirmez l’adresse à laquelle l’invitation a été envoyée et vous entrerez directement.",
    linkOnlyBody:
      "Ce catalogue s’ouvre avec le lien privé partagé par la personne qui gère le programme de {company}. Réutilisez ce lien, ou demandez-lui un nouveau — les liens sont renouvelés dès que le programme change de mains.",
    gateEmail: "E-mail professionnel",
    gateEmailHint: "Ce doit être l’une des adresses invitées par la personne qui gère votre programme.",
    gateSubmit: "Ouvrir le catalogue",
    gatePending: "Vérification…",

    introFallback:
      "Des cadeaux pour {company}, fabriqués à la commande et livrés individuellement à chaque destinataire.",
    startOrder: "Lancer une commande groupée",
    spendLimitLabel: "Budget par destinataire",
    noLimit: "Aucune limite",
    approvalLabel: "Validation",
    approvalRequired: "Requise",
    approvalNotRequired: "Non requise",
    recipientsLabel: "Destinataires par campagne",
    recipientsUpTo: "Jusqu’à {count}",
    emptyTitle: "Aucun cadeau disponible pour le moment",
    emptyBody:
      "Rien dans ce catalogue n’est actuellement en production. La personne qui gère le programme pour vous saura quand ce sera de retour.",
    giftsTitle: "Les cadeaux de ce catalogue",
    previewSoon: "Aperçu bientôt disponible",
    overLimit: "Au-dessus du budget",
    sizes: "Tailles : {sizes}",
    oneSize: "Taille unique",
    overLimitTitle: "Certains cadeaux dépassent votre budget",
    overLimitBody:
      "Un destinataire associé à l’un d’eux est refusé à la lecture de la liste, afin que la ligne puisse être corrigée avant de demander une validation.",
    howItWorks: "Comment se déroule une campagne",
    step1Title: "Choisissez le cadeau",
    step1Body:
      "Tout ce qui figure ici est déjà produit pour ce programme, dans les tailles que vos équipes peuvent choisir.",
    step2Title: "Ajoutez votre liste de destinataires",
    step2Body:
      "Collez-la depuis un tableur ou importez un CSV — noms, adresses, tailles et un message facultatif.",
    step3Title: "Validation",
    step3Body:
      "La liste part avec son total vers la personne qui valide, avant tout paiement.",
    step4Title: "Un paiement, un colis chacun",
    step4Body:
      "Vous êtes débité une seule fois. Chaque destinataire reçoit son propre colis et son propre suivi.",

    orderTitle: "Commande groupée de cadeaux",
    campaignTitle: "Campagne cadeaux",
    orderIntro:
      "Ajoutez toutes les personnes à qui vous envoyez, avec l’adresse de livraison et la taille portée. Vérifiez la liste autant de fois que vous le souhaitez — rien n’est créé avant l’envoi{approval}.",
    orderIntroApproval: " pour validation",
    paymentPendingTitle: "Les paiements ne sont pas encore activés pour cette boutique",
    paymentPendingBody:
      "Vous pouvez tout de même préparer une campagne et l’envoyer pour validation. Elle ne pourra être payée qu’une fois que {client} aura terminé la configuration de son compte de paiement.",
    yourApprover: "la personne qui valide",

    buyerTitle: "Qui commande",
    campaignName: "Nom de la campagne",
    campaignNamePlaceholder: "Cadeaux clients T4",
    buyerName: "Votre nom",
    orderingAs:
      "Vous commandez en tant que {email}. Conservez le lien de campagne sur lequel vous arriverez — aucun e-mail n’est envoyé, et c’est sur cette page qu’apparaissent la validation et le reçu.",
    buyerEmail: "Votre e-mail professionnel",
    buyerEmailHint:
      "Enregistré sur la campagne comme acheteur. Conservez le lien de campagne sur lequel vous arriverez — aucun e-mail n’est envoyé, et c’est sur cette page qu’apparaissent la validation et le reçu.",
    giftTitle: "Le cadeau",
    giftHint: "Utilisé pour chaque ligne qui ne nomme pas son propre produit.",
    giftHintLimit: "Chaque destinataire peut recevoir jusqu’à {amount}.",
    giftHintNoLimit: "Ce programme n’a aucune limite de budget.",
    listTitle: "Destinataires",
    listHintLead: "Une personne par ligne, jusqu’à {max}. Colonnes :",
    listHintTail:
      "Une ligne d’en-tête est détectée automatiquement, et {product} et {note} sont facultatives.",
    uploadCsv: "Importer un CSV",
    pasteExample: "Coller l’exemple",
    fileLoaded: "{file} chargé",
    fileTooLarge: "{file} pèse {size} Ko. Les listes de destinataires font moins de {limit} Ko.",
    fileUnreadable: "Ce fichier n’a pas pu être lu. Enregistrez-le en CSV et réessayez.",
    listLabel: "Liste de destinataires",
    checkList: "Vérifier la liste",
    checkPending: "Lecture de la liste…",
    sendForApproval: "Envoyer pour validation",
    checkAndSend: "Vérifier et envoyer",
    sendPending: "Traitement…",
    previewRecipients: "{count} destinataires",
    previewToFix: "{count} à corriger",
    previewTotal: "{amount} au total",
    previewOverflow: "{count} lignes au-delà de la limite n’ont pas été lues",
    columnLine: "Ligne",
    columnRecipient: "Destinataire",
    columnGift: "Cadeau",
    columnDelivered: "Livré",
    columnDelivery: "Livraison",
    columnValue: "Valeur",
    noName: "Sans nom",
    subtotal: "Cadeaux",
    shipping: "Livraison",
    tax: "Taxes",
    taxRow: "Taxes {rate} %",
    total: "Total",
    approvalNote:
      "L’envoi place la campagne devant {approver}. Rien n’est débité avant sa validation et votre paiement.",
    noApprovalNote:
      "Ce programme ne demande aucune validation : vous passez directement au paiement dès que la liste est correcte.",

    linkInvalidTitle: "Ce lien de campagne n’est pas valide",
    linkInvalidBody:
      "Les liens de campagne sont personnels : un pour l’acheteur, un pour la personne qui valide. Demandez que le vôtre soit renvoyé, ou ouvrez le catalogue et lancez une nouvelle commande.",
    backToCatalogue: "Retour au catalogue",
    campaignSubmitted: "{count} destinataires · envoyée par {buyer} le {when}",
    waitingTitle: "En attente de validation",
    waitingBody:
      "{approver} a la liste et son total. Vous pourrez payer dès la validation — rien n’a été débité.",
    decisionTitle: "Votre décision est enregistrée",
    decisionBody: "{decision} par {who} le {when}.",
    decisionCanPay: "{buyer} peut maintenant payer — rien ne vous a été débité.",
    decisionApproved: "Validée",
    decisionDeclined: "Refusée",
    declinedNoReason: "Aucun motif n’a été donné.",
    declinedBody:
      "Lancez une nouvelle commande depuis le catalogue avec les changements demandés par la personne qui valide.",
    orderedTitle: "Payée et en production",
    orderedBody:
      "{count} commandes ont été créées, une par destinataire, chacune avec sa livraison et son suivi. Suivez-les ci-dessous.",
    unpayableTitle: "Validée, mais la boutique ne peut pas encore encaisser",
    unpayableBody:
      "{client} n’a pas terminé la configuration de son compte de paiement. Votre campagne est enregistrée et pourra être payée dès que ce sera fait.",
    recipientsTitle: "Destinataires",
    track: "Suivre {code}",
    historyTitle: "Historique",
    totalsTitle: "Total de la campagne",
    spendLimitNote: "Budget de {amount} par destinataire.",
    noSpendLimitNote: "Aucune limite de budget sur ce programme.",
    decisionFormTitle: "Votre décision",
    paymentTitle: "Paiement",
    approvalIntro:
      "{buyer} a besoin de votre accord avant que cette campagne puisse être payée. Valider ne débite rien — l’acheteur paie depuis son propre écran.",
    noteLabel: "Note (obligatoire pour refuser)",
    notePlaceholder: "Validé sur le budget marketing du T4.",
    approve: "Valider {total}",
    approvePending: "Enregistrement de votre décision…",
    decline: "Refuser",
    declinePending: "Enregistrement…",
    paymentIntro:
      "Un seul paiement pour toute la campagne, encaissé via le compte Stripe de la boutique {account}. Chaque destinataire devient ensuite sa propre commande avec son propre suivi.",
    pay: "Payer {total}",
    payPending: "Paiement en cours…",
    withdraw: "Retirer cette campagne",
    withdrawConfirm: "Retirer la campagne",
    withdrawQuestion: "La liste est retirée et personne n’est débité.",
    withdrawPending: "Traitement…",
    cancel: "Annuler",

    statusAwaitingApproval: "En attente de validation",
    statusApproved: "Validée, paiement en attente",
    statusDeclined: "Refusée",
    statusOrdered: "Commandée",
    statusCancelled: "Annulée",

    eyebrow: "Portail cadeaux",
    notFoundTitle: "Cette page est introuvable",
    notFoundBody:
      "L’adresse est peut-être mal saisie, ou la campagne ou le produit visé a été fermé depuis l’envoi du lien. Le catalogue lui-même est toujours ouvert.",
    notFoundBoundaryBody:
      "Le lien a peut-être expiré, ou le catalogue cadeaux a été fermé par l’entreprise qui l’a mis en place. Si quelqu’un vous a envoyé ce lien, demandez-lui-en un à jour.",
    errorTitle: "Quelque chose s’est mal passé de notre côté",
    errorBody:
      "Cette page n’a pas pu être chargée. Rien de ce que vous avez envoyé n’a été perdu — réessayez, et si cela persiste revenez dans quelques minutes.",
    errorRetry: "Réessayer",
    errorReference: "Référence {digest}",
    goToParcelith: "Aller sur Parcelith",
  },

  fallback: {
    notFoundTitle: "Cette page est introuvable",
    notFoundBody:
      "Le lien est peut-être obsolète ou le produit n’est plus en vente. Tout ce que {store} propose aujourd’hui reste à portée de clic.",
    browseProducts: "Voir tous les produits",
    errorTitle: "Un problème est survenu de notre côté",
    errorBody:
      "Cette page n’a pas pu être chargée. Votre panier est intact — réessayez, et si cela persiste revenez dans quelques minutes.",
    errorRetry: "Réessayer",
    errorHome: "Retour à {store}",
    errorReference: "Référence {digest}",
  },
};
