import type { StorefrontCopy } from "./en";

/** Storefront copy, Italian. */
export const it: StorefrontCopy = {
  chrome: {
    shop: "Negozio",
    currencyLabel: "Valuta",
    currencyApply: "Applica",
    basket: "Carrello",
    basketWithCount: "Carrello ({count})",
    operatedBy: "Gestito da {client}. Prodotto su ordinazione e spedito in tutto il mondo.",
    allProducts: "Tutti i prodotti",
    orderStatus: "Stato dell’ordine",
    delivery: "Spedizione",
    carriersPending: "Configurazione dei corrieri in corso",
    pricesShownIn: "Prezzi in {currency}{tax}.",
    taxIncluded: ", imposte incluse",
    taxAtCheckout: ", imposte aggiunte al pagamento",
    legal:
      "© {year} {client}. {client} è il venditore di questo negozio. Vetrina realizzata con Parcelith.",
  },

  meta: {
    homeTitle: "{store} — articoli prodotti su ordinazione",
    homeDescription:
      "Acquista da {store}, il negozio ufficiale di {client}. Stampato su richiesta e spedito in tutto il mondo.",
    shopTitle: "Negozio — {store}",
    shopDescription: "Tutti i prodotti disponibili da {store}.",
  },

  home: {
    closedTitle: "Questo negozio è chiuso",
    closedBody:
      "{client} ha archiviato {store}. Gli ordini già effettuati vengono comunque evasi e le relative pagine di stato restano disponibili.",
    comingSoonTitle: "{store} è quasi pronto",
    comingSoonBody: "Il layout della vetrina non è ancora stato pubblicato.",
    comingSoonWithProducts: "I prodotti sono già online e possono essere sfogliati nel frattempo.",
    comingSoonNoProducts: "Torna a trovarci a breve.",
    browseProducts: "Sfoglia {count} prodotti",
  },

  shop: {
    title: "Tutto il negozio",
    intro: "Prodotto su ordinazione e spedito in tutto il mondo. Prezzi in {currency}{tax}.",
    taxIncluded: ", imposte incluse",
    taxAtCheckout: "; le imposte vengono aggiunte al pagamento",
    searchLabel: "Cerca",
    searchPlaceholder: "T-shirt, felpa, tazza…",
    searchSubmit: "Cerca",
    clear: "Azzera",
    filterByTag: "Filtra per tag",
    emptyTitle: "Ancora nulla di pubblicato",
    emptyBody: "Questo negozio non ha ancora pubblicato prodotti. Torna presto.",
    noMatchTitle: "Nessun prodotto corrisponde alla ricerca",
    noMatchBody: "Prova un altro termine di ricerca oppure azzera i filtri.",
    clearFilters: "Azzera i filtri",
    personalise: "Personalizzabile",
    previewSoon: "Anteprima in arrivo",
  },

  product: {
    breadcrumb: "Percorso di navigazione",
    breadcrumbShop: "Negozio",
    about: "Informazioni sul prodotto",
    madeToOrder: "Prodotto su ordinazione",
    producedBy: "Prodotto da {supplier} in {lead}, poi spedito con {carriers}.",
    defaultSupplier: "il nostro partner di produzione",
    leadDays: "{from}–{to} giorni",
    leadUnknown: "pochi giorni",
    defaultCarrier: "il nostro corriere",
    carrierJoin: "o",
    printDetail: "Dettagli di stampa",
    printDetailBody: "{area}, {width} × {height} mm, stampato ad almeno {dpi} DPI.",
    taxAndDelivery: "Imposte e spedizione",
    pricesShownIn: "Prezzi in {currency}{tax}.",
    taxIncluded: " con imposte incluse",
    taxAtCheckout: "; le imposte vengono calcolate al pagamento",
    merchantOfRecord: "{client} è il venditore di questo ordine.",
  },

  purchase: {
    addToBasket: "Aggiungi al carrello",
    adding: "Aggiunta in corso…",
    viewBasket: "Vedi il carrello",
    colour: "Colore",
    size: "Taglia",
    option: "Opzione",
    required: "Obbligatorio",
    quantity: "Quantità",
    lowStock: "scorte basse",
    noPreview: "Nessuna anteprima disponibile",
    previewAlt: "Anteprima di {name}",
    viewAlt: "Vista {view}",
    livePreview:
      "Anteprima dal vivo. Aggiungendo l’articolo al carrello viene allegata una versione fedele alla produzione.",
    textPlaceholder: "Facoltativo",
    textCounter: "{count}/{max} caratteri. Stampati insieme alla grafica.",
    artworkLabel: "La tua grafica",
    artworkHint:
      "Stampata su {width} × {height} mm, quindi servono almeno {dpi} DPI. {formats} fino a {max} MB.",
    artworkHintSimple: "PNG, JPG o WEBP.",
    uploading: "Caricamento della grafica…",
    uploadFailed: "Non è stato possibile caricare il file.",
    fileTooLarge: "Il file pesa {size} MB. Il limite è di {limit} MB.",
  },

  basket: {
    title: "Il tuo carrello",
    emptyTitle: "Il carrello è ancora vuoto",
    emptyBody:
      "Aggiungi un prodotto con la sua personalizzazione: comparirà qui con l’anteprima allegata al tuo ordine.",
    browseShop: "Vai al negozio",
    previewAlt: "Anteprima di {name}",
    personalisation: "Personalizzazione:",
    artwork: "Grafica: {file}",
    quantity: "Quantità",
    update: "Aggiorna",
    remove: "Rimuovi",
    summary: "Riepilogo",
    subtotal: "Subtotale",
    shipping: "Spedizione",
    taxRow: "Imposte {rate} %",
    taxIncludedSuffix: "incluse",
    total: "Totale",
    checkout: "Vai al pagamento",
    keepShopping: "Continua gli acquisti",
  },

  checkout: {
    title: "Pagamento",
    merchantNote:
      "{client} è il venditore. Il pagamento viene accreditato sul suo conto Stripe.",
    unavailableTitle: "Questo negozio non può ancora accettare pagamenti",
    unavailableBody:
      "Il negozio non ha completato il collegamento del suo conto Stripe. Il carrello resta salvato: riprova quando il negozio sarà attivo.",
    backToBasket: "Torna al carrello",
    summaryTitle: "Riepilogo dell’ordine",
    shipping: "Spedizione",
    taxRow: "Imposte {rate} %",
    taxIncludedSuffix: "incluse",
    total: "Totale",
    deliveryDetails: "Dati di consegna",
    fullName: "Nome e cognome",
    email: "E-mail",
    emailHint: "Qui arrivano la conferma d’ordine e gli aggiornamenti sulla consegna.",
    street: "Indirizzo",
    city: "Città",
    postalCode: "CAP",
    country: "Paese",
    countryHint: "Inizia a digitare per trovare il tuo paese. La produzione dipende dalla destinazione.",
    countrySearchPlaceholder: "Cerca un paese",
    countryNoMatch: "Nessun paese corrisponde a «{query}».",
    payIn: "Paga in",
    manualRoutingTitle: "La consegna in {country} richiede un instradamento manuale",
    manualRoutingLine: "{supplier} produce {products} e non spedisce in {country} ({region}).",
    productJoin: "e",
    manualRoutingBody:
      "Puoi comunque pagare, ma l’ordine resterà in sospeso finché una persona non lo affiderà a un altro partner di produzione: i tempi saranno più lunghi del solito. Scegliere un paese coperto dal tuo fornitore evita l’attesa.",
    paymentTitle: "Pagamento",
    paymentNote:
      "Addebitato tramite il conto Stripe di questo negozio {account}. I dati della carta non vengono mai conservati dal negozio.",
    cardNumber: "Numero della carta",
    expiry: "Scadenza (MM/AA)",
    securityCode: "Codice di sicurezza",
    testMode: "Modalità test di Stripe",
    submit: "Paga e ordina",
    pending: "Pagamento in corso…",
    cardSucceeds: "Visa — accettata",
    cardDeclined: "Visa — rifiutata dalla banca",
    cardInsufficient: "Visa — fondi insufficienti",
  },

  order: {
    title: "Stato dell’ordine",
    lookupIntro:
      "Inserisci il codice ordine riportato nella conferma e l’indirizzo e-mail associato. Il link nella conferma apre l’ordine direttamente.",
    gateBody:
      "Per proteggere i dati di consegna e personalizzazione, conferma l’indirizzo e-mail dell’ordine {code} prima di visualizzarlo.",
    confirmedTitle: "Grazie: il tuo ordine è confermato",
    confirmedBody:
      "Abbiamo inviato una conferma a {email}. Aggiungi questa pagina ai preferiti per seguire produzione e consegna.",
    heading: "Ordine {code}",
    placed: "Effettuato il {when}",
    trackWith: "Traccia con {carrier} ↗",
    whatYouOrdered: "Il tuo ordine",
    variantQuantity: "{variant} · quantità {count}",
    personalisation: "Personalizzazione:",
    previewAlt: "Anteprima di {name}",
    subtotal: "Subtotale",
    shipping: "Spedizione",
    taxRow: "Imposte {rate} %",
    paid: "Pagato",
    refunded: "Rimborsato",
    deliveringTo: "Consegna a",
    payment: "Pagamento",
    cardEnding: "Carta con finale {last4}",
    card: "Carta",
    paidWord: "pagato",
    refundedWord: "rimborsato",
    merchantOfRecord: "{client} è il venditore.",
    progress: "Avanzamento",
    continueShopping: "Continua gli acquisti",
    contactStore: "Contatta il negozio",
    orderCode: "Codice ordine",
    orderCodeHint: "È sulla conferma d’ordine e inizia con ORD-.",
    emailOnOrder: "E-mail dell’ordine",
    emailHint: "L’indirizzo a cui è stata inviata la conferma.",
    lookupSubmit: "Mostra il mio ordine",
    lookupPending: "Verifica in corso…",
  },

  status: {
    awaitingPayment: "In attesa di pagamento",
    awaitingPaymentNote: "Non abbiamo ancora ricevuto il pagamento di questo ordine.",
    paid: "Pagamento ricevuto",
    paidNote: "Il tuo ordine è in coda per la produzione.",
    inProduction: "In produzione",
    inProductionNote: "Il tuo articolo è in fase di stampa e finitura.",
    shipped: "Spedito",
    shippedNote: "Il tuo pacco è in viaggio. Seguilo con il link qui sotto.",
    delivered: "Consegnato",
    deliveredNote: "Il tuo pacco è stato consegnato. Buon divertimento.",
    cancelled: "Annullato",
    cancelledNote: "Questo ordine è stato annullato. Eventuali pagamenti sono stati rimborsati.",
    exception: "Richiede attenzione",
    exceptionNote:
      "Questo ordine è momentaneamente bloccato. Il team del negozio se ne sta occupando e ti contatterà.",
  },

  actions: {
    storeClosed: "Questo negozio al momento non accetta ordini.",
    productGone: "Questo prodotto non è più disponibile.",
    chooseVariant: "Scegli taglia e colore.",
    outOfStock: "{variant} è esaurito. Scegli un’altra opzione.",
    noTextPersonalisation: "Questo prodotto non può essere personalizzato con del testo.",
    textTooLong: "Contieni la personalizzazione entro {max} caratteri.",
    noArtworkUpload: "Questo prodotto non accetta grafiche caricate.",
    productUnavailable: "Questo prodotto è temporaneamente non disponibile.",
    fileTooLarge: "Il file pesa {size} MB. Il limite è di {limit} MB.",
    basketUnavailable: "Non è stato possibile aprire il carrello. Abilita i cookie e riprova.",
    addedToBasket: "{product} è stato aggiunto al carrello.",
    basketEmpty: "Il tuo carrello è vuoto.",
    enterName: "Indica il nome per la consegna.",
    enterEmail: "Indica un indirizzo e-mail per ricevere gli aggiornamenti sull’ordine.",
    enterStreet: "Indica l’indirizzo.",
    enterCity: "Indica la città.",
    enterPostalCode: "Indica il CAP.",
    chooseCountry: "Scegli il paese di consegna dall’elenco.",
    currencyNotSold: "{currency} non è una delle valute di vendita di questo negozio.",
    enterOrderCode: "Inserisci il codice ordine.",
    enterOrderEmail: "Inserisci l’indirizzo e-mail dell’ordine.",
    lookupFailed:
      "Codice ordine e indirizzo e-mail non corrispondono. Controlla entrambi e riprova.",
  },

  artwork: {
    lowDpi:
      "Questa grafica viene stampata a una risoluzione troppo bassa. Carica un file di almeno {dpi} DPI.",
    badFormat: "I file {format} non sono accettati per questo prodotto. Carica {formats}.",
    fileTooLarge: "Il file pesa {size} MB. Il limite è di {limit} MB.",
    tooManyPixels:
      "Questa immagine è troppo grande. Riducila sotto {megapixels} megapixel e riprova.",
    noTransparency:
      "Questo prodotto richiede una grafica con sfondo trasparente. Esportala come PNG con trasparenza.",
    generic: "Questa grafica non può essere stampata su questo prodotto. Prova con un altro file.",
  },

  payment: {
    accountNotReady:
      "Questo negozio non ha completato il collegamento del conto Stripe, quindi i pagamenti non sono disponibili.",
    currencyUnsupported: "{currency} non è una delle valute di vendita di questo negozio.",
    invalidNumber: "Questo numero di carta non è valido. Controlla le cifre e riprova.",
    invalidExpiry: "La data di scadenza è passata o non è nel formato giusto. Usa MM/AA.",
    invalidCvc: "Il codice di sicurezza deve avere 3 o 4 cifre.",
    declined: "La tua carta è stata rifiutata dalla banca emittente.",
    insufficientFunds: "La tua carta non ha fondi sufficienti.",
    expiredCard: "La tua carta è scaduta.",
  },

  sections: {
    viewAll: "Vedi tutto",
    noProducts:
      "In questo negozio non ci sono ancora prodotti pubblicati. I prodotti pubblicati compaiono qui automaticamente.",
    previewSoon: "Anteprima in arrivo",
    imagePlaceholder: "Aggiungi l’URL di un’immagine nelle impostazioni della sezione",
    newsletterEmail: "Indirizzo e-mail",
    notifyMe: "Avvisami",
    welcome: "Benvenuto",
  },
};
