import type { StorefrontCopy } from "./en";

/** Storefront copy, Italian. */
export const it: StorefrontCopy = {
  chrome: {
    shop: "Negozio",
    currencyLabel: "Valuta",
    currencyApply: "Applica",
    basket: "Carrello",
    basketWithCount: "Carrello ({count})",
    operatedBy: "Gestito da {client}. Prodotto su ordinazione e spedito in tutto il mondo.",
    allProducts: "Tutti i prodotti",
    orderStatus: "Stato dell’ordine",
    delivery: "Spedizione",
    help: "Assistenza",
    supportEmailLabel: "E-mail",
    supportPhoneLabel: "Telefono",
    supportPending: "I contatti dell’assistenza non sono ancora stati pubblicati.",
    carriersPending: "Configurazione dei corrieri in corso",
    pricesShownIn: "Prezzi in {currency}{tax}.",
    taxIncluded: ", imposte incluse",
    taxAtCheckout: ", imposte aggiunte al pagamento",
    legal:
      "© {year} {client}. {client} è il venditore di questo negozio. Vetrina realizzata con Parcelith.",
  },

  meta: {
    homeTitle: "{store} — articoli prodotti su ordinazione",
    homeDescription:
      "Acquista da {store}, il negozio ufficiale di {client}. Stampato su richiesta e spedito in tutto il mondo.",
    taglineDescription:
      "{tagline} Acquista da {store}, il negozio ufficiale di {client}.",
    shopTitle: "Negozio",
    shopDescription: "Tutti i prodotti disponibili da {store}.",
  },

  home: {
    closedTitle: "Questo negozio è chiuso",
    closedBody:
      "{client} ha archiviato {store}. Gli ordini già effettuati vengono comunque evasi e le relative pagine di stato restano disponibili.",
    comingSoonTitle: "{store} è quasi pronto",
    comingSoonBody: "Il layout della vetrina non è ancora stato pubblicato.",
    comingSoonWithProducts: "I prodotti sono già online e possono essere sfogliati nel frattempo.",
    comingSoonNoProducts: "Torna a trovarci a breve.",
    browseProducts: "Sfoglia {count} prodotti",
  },

  shop: {
    title: "Tutto il negozio",
    intro: "Prodotto su ordinazione e spedito in tutto il mondo. Prezzi in {currency}{tax}.",
    taxIncluded: ", imposte incluse",
    taxAtCheckout: "; le imposte vengono aggiunte al pagamento",
    searchLabel: "Cerca",
    searchPlaceholder: "T-shirt, felpa, tazza…",
    searchSubmit: "Cerca",
    clear: "Azzera",
    filterByTag: "Filtra per tag",
    emptyTitle: "Ancora nulla di pubblicato",
    emptyBody: "Questo negozio non ha ancora pubblicato prodotti. Torna presto.",
    noMatchTitle: "Nessun prodotto corrisponde alla ricerca",
    noMatchBody: "Prova un altro termine di ricerca oppure azzera i filtri.",
    clearFilters: "Azzera i filtri",
    personalise: "Personalizzabile",
    previewSoon: "Anteprima in arrivo",
  },

  product: {
    breadcrumb: "Percorso di navigazione",
    breadcrumbShop: "Negozio",
    about: "Informazioni sul prodotto",
    madeToOrder: "Prodotto su ordinazione",
    producedBy: "Prodotto da {supplier} in {lead}, poi spedito con {carriers}.",
    defaultSupplier: "il nostro partner di produzione",
    leadDays: "{from}–{to} giorni",
    leadUnknown: "pochi giorni",
    defaultCarrier: "il nostro corriere",
    carrierJoin: "o",
    printDetail: "Dettagli di stampa",
    printDetailBody: "{area}, {width} × {height} mm, stampato ad almeno {dpi} DPI.",
    taxAndDelivery: "Imposte e spedizione",
    pricesShownIn: "Prezzi in {currency}{tax}.",
    taxIncluded: " con imposte incluse",
    taxAtCheckout: "; le imposte vengono calcolate al pagamento",
    merchantOfRecord: "{client} è il venditore di questo ordine.",
  },

  purchase: {
    addToBasket: "Aggiungi al carrello",
    adding: "Aggiunta in corso…",
    viewBasket: "Vedi il carrello",
    colour: "Colore",
    size: "Taglia",
    option: "Opzione",
    required: "Obbligatorio",
    quantity: "Quantità",
    lowStock: "scorte basse",
    noPreview: "Nessuna anteprima disponibile",
    previewAlt: "Anteprima di {name}",
    viewAlt: "Vista {view}",
    livePreview:
      "Anteprima dal vivo. Aggiungendo l’articolo al carrello viene allegata una versione fedele alla produzione.",
    textPlaceholder: "Facoltativo",
    textCounter: "{count}/{max} caratteri. Stampati insieme alla grafica.",
    artworkLabel: "La tua grafica",
    artworkHint:
      "Stampata su {width} × {height} mm, quindi servono almeno {dpi} DPI. {formats} fino a {max} MB.",
    artworkHintSimple: "PNG, JPG o WEBP.",
    uploading: "Caricamento della grafica…",
    uploadFailed: "Non è stato possibile caricare il file.",
    fileTooLarge: "Il file pesa {size} MB. Il limite è di {limit} MB.",
    artworkPlacementTitle: "Posiziona la grafica",
    artworkPlacementHelp:
      "Trascina la grafica sull’anteprima oppure usa i comandi qui sotto. Anteprima e risoluzione di stampa si aggiornano a ogni modifica.",
    artworkGrabLabel:
      "Posizione di {file}. Trascina per spostarla o usa le frecce; + e − la ridimensionano.",
    artworkSize: "Dimensione",
    artworkRotation: "Rotazione",
    artworkResolution: "Risoluzione di stampa",
    artworkRecentre: "Rimetti al centro",
    artworkRemove: "Rimuovi la grafica",
    artworkChecksPass: "Questa grafica è pronta per la stampa a questa dimensione.",
    artworkChecksFail: "Da sistemare prima di aggiungere al carrello",
    artworkWhatToDo: "Cosa fare: {fix}",
    artworkBlocked:
      "Sistema la grafica qui sopra, oppure rimuovila, per aggiungere l’articolo al carrello.",
  },

  basket: {
    title: "Il tuo carrello",
    emptyTitle: "Il carrello è ancora vuoto",
    emptyBody:
      "Aggiungi un prodotto con la sua personalizzazione: comparirà qui con l’anteprima allegata al tuo ordine.",
    browseShop: "Vai al negozio",
    previewAlt: "Anteprima di {name}",
    personalisation: "Personalizzazione:",
    artwork: "Grafica: {file}",
    quantity: "Quantità",
    update: "Aggiorna",
    remove: "Rimuovi",
    summary: "Riepilogo",
    subtotal: "Subtotale",
    shipping: "Spedizione",
    taxRow: "Imposte {rate} %",
    taxIncludedSuffix: "incluse",
    total: "Totale",
    checkout: "Vai al pagamento",
    keepShopping: "Continua gli acquisti",
  },

  discount: {
    title: "Codice sconto",
    label: "Codice",
    placeholder: "SPRING10",
    apply: "Applica",
    applying: "Applicazione…",
    remove: "Rimuovi",
    row: "Sconto ({code})",
    applied: "Codice {code} applicato: {amount} di sconto.",
    removed: "Il codice sconto è stato rimosso.",
    enterCode: "Inserisci un codice sconto.",
    unknown: "Non riconosciamo questo codice.",
    inactive: "Questo codice non è più attivo.",
    expired: "Questo codice è scaduto.",
    limitReached: "Questo codice è già stato usato il numero massimo di volte.",
    belowMinimum: "Questo codice richiede un carrello di almeno {amount}.",
    dropped:
      "Il codice {code} non vale più per questo carrello ed è stato rimosso. Controlla il totale prima di pagare.",
  },

  checkout: {
    title: "Pagamento",
    merchantNote:
      "{client} è il venditore. Il pagamento viene accreditato sul suo conto Stripe.",
    unavailableTitle: "Questo negozio non può ancora accettare pagamenti",
    unavailableBody:
      "Il negozio non ha completato il collegamento del suo conto Stripe. Il carrello resta salvato: riprova quando il negozio sarà attivo.",
    backToBasket: "Torna al carrello",
    summaryTitle: "Riepilogo dell’ordine",
    shipping: "Spedizione",
    taxRow: "Imposte {rate} %",
    taxIncludedSuffix: "incluse",
    total: "Totale",
    deliveryDetails: "Dati di consegna",
    fullName: "Nome e cognome",
    email: "E-mail",
    emailHint: "Con questo indirizzo e il codice ordine riapri la pagina del tuo ordine.",
    street: "Indirizzo",
    city: "Città",
    postalCode: "CAP",
    country: "Paese",
    countryHint: "Inizia a digitare per trovare il tuo paese. La produzione dipende dalla destinazione.",
    countrySearchPlaceholder: "Cerca un paese",
    countryNoMatch: "Nessun paese corrisponde a «{query}».",
    payIn: "Paga in",
    manualRoutingTitle: "La consegna in {country} richiede un instradamento manuale",
    manualRoutingLine: "{supplier} produce {products} e non spedisce in {country} ({region}).",
    productJoin: "e",
    manualRoutingBody:
      "Puoi comunque pagare, ma l’ordine resterà in sospeso finché una persona non lo affiderà a un altro partner di produzione: i tempi saranno più lunghi del solito. Scegliere un paese coperto dal tuo fornitore evita l’attesa.",
    paymentTitle: "Pagamento",
    paymentNote:
      "Addebitato tramite il conto Stripe di questo negozio {account}. I dati della carta non vengono mai conservati dal negozio.",
    cardNumber: "Numero della carta",
    expiry: "Scadenza (MM/AA)",
    securityCode: "Codice di sicurezza",
    testMode: "Modalità test di Stripe",
    submit: "Paga e ordina",
    pending: "Pagamento in corso…",
    cardSucceeds: "Visa — accettata",
    cardDeclined: "Visa — rifiutata dalla banca",
    cardInsufficient: "Visa — fondi insufficienti",
  },

  order: {
    title: "Stato dell’ordine",
    lookupIntro:
      "Inserisci il codice ordine e l’indirizzo e-mail indicato al pagamento. Il link salvato al momento dell’ordine lo apre direttamente.",
    gateBody:
      "Per proteggere i dati di consegna e personalizzazione, conferma l’indirizzo e-mail dell’ordine {code} prima di visualizzarlo.",
    confirmedTitle: "Grazie: il tuo ordine è confermato",
    confirmedBody:
      "Salva questa pagina o aggiungila ai preferiti: è qui che compare l’avanzamento del tuo ordine. Ti abbiamo inviato un’e-mail di conferma con questo link.",
    confirmedFindAgain:
      "Puoi ritrovarla anche da «Stato dell’ordine» con il codice {code} e l’indirizzo e-mail {email}.",
    heading: "Ordine {code}",
    placed: "Effettuato il {when}",
    trackWith: "Traccia con {carrier} ↗",
    whatYouOrdered: "Il tuo ordine",
    variantQuantity: "{variant} · quantità {count}",
    personalisation: "Personalizzazione:",
    previewAlt: "Anteprima di {name}",
    subtotal: "Subtotale",
    shipping: "Spedizione",
    taxRow: "Imposte {rate} %",
    paid: "Pagato",
    refunded: "Rimborsato",
    deliveringTo: "Consegna a",
    payment: "Pagamento",
    cardEnding: "Carta con finale {last4}",
    card: "Carta",
    paidWord: "pagato",
    refundedWord: "rimborsato",
    merchantOfRecord: "{client} è il venditore.",
    progress: "Avanzamento",
    supportTitle: "Domande su questo ordine",
    contactSubject: "Ordine {code}",
    continueShopping: "Continua gli acquisti",
    contactStore: "Contatta il negozio",
    orderCode: "Codice ordine",
    orderCodeHint: "Inizia con ORD- ed è indicato in alto nella pagina del tuo ordine.",
    emailOnOrder: "E-mail dell’ordine",
    emailHint: "L’indirizzo indicato al momento del pagamento.",
    lookupSubmit: "Mostra il mio ordine",
    lookupPending: "Verifica in corso…",
  },

  status: {
    awaitingPayment: "In attesa di pagamento",
    awaitingPaymentNote: "Non abbiamo ancora ricevuto il pagamento di questo ordine.",
    paid: "Pagamento ricevuto",
    paidNote: "Il tuo ordine è in coda per la produzione.",
    inProduction: "In produzione",
    inProductionNote: "Il tuo articolo è in fase di stampa e finitura.",
    shipped: "Spedito",
    shippedNote: "Il tuo pacco è in viaggio. Seguilo con il link qui sotto.",
    delivered: "Consegnato",
    deliveredNote: "Il tuo pacco è stato consegnato. Buon divertimento.",
    cancelled: "Annullato",
    cancelledNote: "Questo ordine è stato annullato. Eventuali pagamenti sono stati rimborsati.",
    exception: "Richiede attenzione",
    exceptionNote:
      "Questo ordine è momentaneamente bloccato. Il team del negozio se ne sta occupando e ti contatterà.",
  },

  actions: {
    storeClosed: "Questo negozio al momento non accetta ordini.",
    productGone: "Questo prodotto non è più disponibile.",
    chooseVariant: "Scegli taglia e colore.",
    outOfStock: "{variant} è esaurito. Scegli un’altra opzione.",
    noTextPersonalisation: "Questo prodotto non può essere personalizzato con del testo.",
    textTooLong: "Contieni la personalizzazione entro {max} caratteri.",
    noArtworkUpload: "Questo prodotto non accetta grafiche caricate.",
    productUnavailable: "Questo prodotto è temporaneamente non disponibile.",
    fileTooLarge: "Il file pesa {size} MB. Il limite è di {limit} MB.",
    basketUnavailable: "Non è stato possibile aprire il carrello. Abilita i cookie e riprova.",
    addedToBasket: "{product} è stato aggiunto al carrello.",
    basketEmpty: "Il tuo carrello è vuoto.",
    enterName: "Indica il nome per la consegna.",
    enterEmail: "Indica un indirizzo e-mail: è con quello che riaprirai il tuo ordine.",
    enterStreet: "Indica l’indirizzo.",
    enterCity: "Indica la città.",
    enterPostalCode: "Indica il CAP.",
    chooseCountry: "Scegli il paese di consegna dall’elenco.",
    currencyNotSold: "{currency} non è una delle valute di vendita di questo negozio.",
    enterOrderCode: "Inserisci il codice ordine.",
    enterOrderEmail: "Inserisci l’indirizzo e-mail dell’ordine.",
    lookupFailed:
      "Codice ordine e indirizzo e-mail non corrispondono. Controlla entrambi e riprova.",
  },

  artwork: {
    lowDpi: "Questa immagine verrà stampata a {dpi} DPI, sotto i {required} DPI richiesti da questo prodotto.",
    lowDpiFix:
      "Carica un file largo almeno {pixels} pixel, oppure riduci la grafica: questo file resta nitido fino a {width} mm di larghezza.",
    badFormat: "I file {format} non sono accettati per questo prodotto.",
    badFormatFix: "Salva la grafica come {formats} e selezionala di nuovo.",
    unreadableFormat: "I file {format} non possono essere misurati né visualizzati qui.",
    unreadableFormatFix: "Salva la grafica come {formats} e selezionala di nuovo.",
    fileTooLarge: "Il file pesa {size} MB. Il limite è di {limit} MB.",
    fileTooLargeFix: "Salvalo con dimensioni o qualità inferiori e selezionalo di nuovo.",
    tooManyPixels: "Questa immagine è troppo grande. Il limite è di {megapixels} megapixel.",
    tooManyPixelsFix: "Ridimensionala nel tuo editor di foto e selezionala di nuovo.",
    noTransparency:
      "Questo prodotto viene stampato direttamente sul tessuto, quindi la grafica deve avere lo sfondo trasparente.",
    noTransparencyFix: "Rimuovi lo sfondo e salvala come PNG con trasparenza.",
    outsideArea: "Una parte della grafica esce dall’area di stampa e verrebbe tagliata.",
    outsideAreaFix:
      "Trascinala dentro il riquadro tratteggiato, oppure riducila fino a {width} × {height} mm.",
    dpiTight: "Questa immagine verrà stampata a {dpi} DPI, appena sopra il minimo di {required} DPI.",
    dpiTightFix:
      "Le linee sottili possono risultare morbide. Un file più grande, o una grafica un po’ più piccola, stampa meglio.",
    verySmall: "La grafica copre meno del 15% della larghezza stampabile.",
    verySmallFix: "Aumenta la dimensione se deve essere la grafica principale.",
    generic: "Questa grafica non può essere stampata su questo prodotto.",
    genericFix: "Prova con un altro file.",
  },

  payment: {
    accountNotReady:
      "Questo negozio non ha completato il collegamento del conto Stripe, quindi i pagamenti non sono disponibili.",
    currencyUnsupported: "{currency} non è una delle valute di vendita di questo negozio.",
    invalidNumber: "Questo numero di carta non è valido. Controlla le cifre e riprova.",
    invalidExpiry: "La data di scadenza è passata o non è nel formato giusto. Usa MM/AA.",
    invalidCvc: "Il codice di sicurezza deve avere 3 o 4 cifre.",
    declined: "La tua carta è stata rifiutata dalla banca emittente.",
    insufficientFunds: "La tua carta non ha fondi sufficienti.",
    expiredCard: "La tua carta è scaduta.",
  },

  sections: {
    viewAll: "Vedi tutto",
    noProducts:
      "In questo negozio non ci sono ancora prodotti pubblicati. I prodotti pubblicati compaiono qui automaticamente.",
    previewSoon: "Anteprima in arrivo",
    imagePlaceholder: "Aggiungi l’URL di un’immagine nelle impostazioni della sezione",
    newsletterEmail: "Indirizzo e-mail",
    notifyMe: "Avvisami",
    welcome: "Benvenuto",
  },

  email: {
    logoAlt: "{store}",
    greeting: "Ciao {name},",
    footer: "{client} è il venditore ufficiale di questo negozio. Inviato da {store}.",
    support: "Domande? Scrivici a {email}.",
    orderSubject: "Ordine {code} confermato — {store}",
    orderHeading: "Grazie per il tuo ordine",
    orderBody:
      "Abbiamo ricevuto l’ordine {code} e il pagamento è andato a buon fine. Il link qui sotto apre la pagina di avanzamento in qualsiasi momento: conservalo.",
    orderCta: "Vedi il tuo ordine",
    orderTotalLabel: "Totale pagato",
    orderDeliveryLabel: "Consegna a",
    shippedSubject: "L’ordine {code} è in viaggio — {store}",
    shippedHeading: "Il tuo pacco è in viaggio",
    shippedBody: "L’ordine {code} è stato affidato a {carrier}.",
    shippedTrackingLabel: "Numero di tracciamento",
    shippedCta: "Traccia il pacco",
    inviteSubject: "{inviter} ti ha invitato su {store}",
    inviteHeading: "Sei stato invitato su {store}",
    inviteBody:
      "{inviter} ti invita a lavorare su {store} come {role}. Aprendo il link qui sotto viene creato il tuo account e attivato l’accesso. Funziona una volta sola.",
    inviteCta: "Accetta l’invito",
    approvalSubject: "La campagna regali {code} attende la tua approvazione — {store}",
    approvalHeading: "Una campagna regali attende la tua approvazione",
    approvalBody:
      "{buyer} ha inviato «{campaign}» per {company}. Nulla viene addebitato finché non approvi l’elenco.",
    approvalRecipientsLabel: "Destinatari",
    approvalTotalLabel: "Totale",
    approvalCta: "Controlla l’elenco",
  },

  gift: {
    chromeSubtitle: "Catalogo regali · {store}",
    private: "Privato",
    operatedBy:
      "Gestito da {client}, che è il venditore responsabile. I regali sono realizzati su ordinazione e spediti singolarmente a ciascun destinatario.",
    supportTitle: "Domande su una campagna:",
    supportPending: "{client} non ha ancora pubblicato i contatti dell’assistenza.",
    legal: "© {year} {client}. Regali aziendali con tecnologia Parcelith.",

    closedTitle: "Questo catalogo è chiuso",
    closedBody:
      "Il programma regali di {company} è in pausa. Chi lo gestisce per voi può riaprirlo: le campagne già inviate non sono interessate.",

    privateBadge: "Catalogo privato",
    inviteBody:
      "Il catalogo regali di {company} è aperto ai colleghi invitati. Confermate l’indirizzo a cui è stato inviato e entrerete subito.",
    linkOnlyBody:
      "Questo catalogo si apre con il link privato condiviso da chi gestisce il programma di {company}. Usate di nuovo quel link oppure chiedetene uno nuovo: i link vengono rinnovati ogni volta che il programma passa di mano.",
    gateEmail: "E-mail di lavoro",
    gateEmailHint: "Deve essere uno degli indirizzi invitati da chi gestisce il programma.",
    gateSubmit: "Apri il catalogo",
    gatePending: "Verifica in corso…",

    introFallback:
      "Regali per {company}, prodotti su ordinazione e consegnati singolarmente a ciascun destinatario.",
    startOrder: "Avvia un ordine multiplo",
    spendLimitLabel: "Limite di spesa per destinatario",
    noLimit: "Nessun limite",
    approvalLabel: "Approvazione",
    approvalRequired: "Necessaria",
    approvalNotRequired: "Non necessaria",
    recipientsLabel: "Destinatari per campagna",
    recipientsUpTo: "Fino a {count}",
    emptyTitle: "Nessun regalo disponibile al momento",
    emptyBody:
      "Nulla in questo catalogo è attualmente in produzione. Chi gestisce il programma saprà quando tornerà disponibile.",
    giftsTitle: "I regali di questo catalogo",
    previewSoon: "Anteprima disponibile a breve",
    overLimit: "Oltre il limite",
    sizes: "Taglie: {sizes}",
    oneSize: "Taglia unica",
    overLimitTitle: "Alcuni regali superano il vostro limite di spesa",
    overLimitBody:
      "Un destinatario abbinato a uno di questi viene rifiutato alla lettura della lista, così la riga può essere corretta prima di chiedere un’approvazione.",
    howItWorks: "Come funziona una campagna",
    step1Title: "Scegliete il regalo",
    step1Body:
      "Tutto quello che vedete qui è già prodotto per questo programma, nelle taglie tra cui le vostre persone possono scegliere.",
    step2Title: "Aggiungete la lista dei destinatari",
    step2Body:
      "Incollatela da un foglio di calcolo o caricate un CSV: nomi, indirizzi, taglie e un messaggio facoltativo.",
    step3Title: "Approvazione",
    step3Body:
      "La lista arriva con il suo totale a chi deve approvarla, prima di qualsiasi pagamento.",
    step4Title: "Un pagamento, un pacco a testa",
    step4Body:
      "Pagate una sola volta. Ogni destinatario riceve il proprio pacco e il proprio tracciamento.",

    orderTitle: "Ordine multiplo di regali",
    campaignTitle: "Campagna regali",
    orderIntro:
      "Aggiungete tutte le persone a cui spedite, con l’indirizzo di consegna e la taglia che indossano. Controllate la lista quante volte volete: non viene creato nulla finché non la inviate{approval}.",
    orderIntroApproval: " per l’approvazione",
    paymentPendingTitle: "I pagamenti non sono ancora attivi per questo negozio",
    paymentPendingBody:
      "Potete comunque preparare una campagna e inviarla per l’approvazione. Non potrà essere pagata finché {client} non avrà completato il collegamento del proprio account di pagamento.",
    yourApprover: "chi approva",

    buyerTitle: "Chi ordina",
    campaignName: "Nome della campagna",
    campaignNamePlaceholder: "Regali clienti Q4",
    buyerName: "Il vostro nome",
    orderingAs:
      "Ordinate come {email}. Conservate il link della campagna su cui arriverete: non viene inviata alcuna e-mail ed è su quella pagina che compaiono l’approvazione e la ricevuta.",
    buyerEmail: "La vostra e-mail di lavoro",
    buyerEmailHint:
      "Registrata sulla campagna come acquirente. Conservate il link della campagna su cui arriverete: non viene inviata alcuna e-mail ed è su quella pagina che compaiono l’approvazione e la ricevuta.",
    giftTitle: "Il regalo",
    giftHint: "Usato per ogni riga che non indica un prodotto proprio.",
    giftHintLimit: "Per ogni destinatario si possono spendere fino a {amount}.",
    giftHintNoLimit: "Questo programma non ha limiti di spesa.",
    listTitle: "Destinatari",
    listHintLead: "Una persona per riga, fino a {max}. Colonne:",
    listHintTail:
      "La riga di intestazione viene rilevata automaticamente e {product} e {note} sono facoltative.",
    uploadCsv: "Carica un CSV",
    pasteExample: "Incolla l’esempio",
    fileLoaded: "{file} caricato",
    fileTooLarge: "{file} è di {size} KB. Le liste di destinatari stanno sotto i {limit} KB.",
    fileUnreadable: "Non è stato possibile leggere il file. Salvatelo come CSV e riprovate.",
    listLabel: "Lista dei destinatari",
    checkList: "Controlla la lista",
    checkPending: "Lettura della lista…",
    sendForApproval: "Invia per approvazione",
    checkAndSend: "Controlla e invia",
    sendPending: "Elaborazione…",
    previewRecipients: "{count} destinatari",
    previewToFix: "{count} da correggere",
    previewTotal: "{amount} in totale",
    previewOverflow: "{count} righe oltre il limite non sono state lette",
    columnLine: "Riga",
    columnRecipient: "Destinatario",
    columnGift: "Regalo",
    columnDelivered: "Consegnato",
    columnDelivery: "Consegna",
    columnValue: "Valore",
    noName: "Senza nome",
    subtotal: "Regali",
    shipping: "Spedizione",
    tax: "Imposte",
    taxRow: "Imposte {rate} %",
    total: "Totale",
    approvalNote:
      "Con l’invio la campagna passa a {approver}. Nulla viene addebitato prima dell’approvazione e del vostro pagamento.",
    noApprovalNote:
      "Questo programma non richiede approvazione: si passa direttamente al pagamento appena la lista è corretta.",

    linkInvalidTitle: "Questo link di campagna non è valido",
    linkInvalidBody:
      "I link delle campagne sono personali: uno per l’acquirente, uno per chi approva. Chiedete che il vostro venga inviato di nuovo, oppure aprite il catalogo e avviate un nuovo ordine.",
    backToCatalogue: "Torna al catalogo",
    campaignSubmitted: "{count} destinatari · inviata da {buyer} il {when}",
    waitingTitle: "In attesa di approvazione",
    waitingBody:
      "{approver} ha la lista e il suo totale. Potrete pagare appena la approva: non è stato addebitato nulla.",
    decisionTitle: "La vostra decisione è registrata",
    decisionBody: "{decision} da {who} il {when}.",
    decisionCanPay: "{buyer} può ora pagarla: a voi non è stato addebitato nulla.",
    decisionApproved: "Approvata",
    decisionDeclined: "Rifiutata",
    declinedNoReason: "Non è stata indicata alcuna motivazione.",
    declinedBody:
      "Avviate un nuovo ordine dal catalogo con le modifiche richieste da chi approva.",
    orderedTitle: "Pagata e in produzione",
    orderedBody:
      "Sono stati creati {count} ordini, uno per destinatario, ciascuno con la propria consegna e il proprio tracciamento. Seguiteli qui sotto.",
    unpayableTitle: "Approvata, ma il negozio non può ancora incassare",
    unpayableBody:
      "{client} non ha completato il collegamento del proprio account di pagamento. La campagna è salvata e potrà essere pagata appena sarà pronto.",
    recipientsTitle: "Destinatari",
    track: "Segui {code}",
    historyTitle: "Cronologia",
    totalsTitle: "Totale della campagna",
    spendLimitNote: "Limite di spesa di {amount} per destinatario.",
    noSpendLimitNote: "Nessun limite di spesa su questo programma.",
    decisionFormTitle: "La vostra decisione",
    paymentTitle: "Pagamento",
    approvalIntro:
      "{buyer} ha bisogno della vostra approvazione prima che la campagna possa essere pagata. Approvare non comporta alcun addebito: l’acquirente paga dalla propria schermata.",
    noteLabel: "Nota (obbligatoria per rifiutare)",
    notePlaceholder: "Approvata sul budget marketing Q4.",
    approve: "Approva {total}",
    approvePending: "Registrazione della decisione…",
    decline: "Rifiuta",
    declinePending: "Registrazione…",
    paymentIntro:
      "Un solo pagamento per l’intera campagna, addebitato tramite l’account Stripe del negozio {account}. Ogni destinatario diventa poi un ordine a sé con il proprio tracciamento.",
    pay: "Paga {total}",
    payPending: "Pagamento in corso…",
    withdraw: "Ritira questa campagna",
    withdrawConfirm: "Ritira la campagna",
    withdrawQuestion: "La lista viene ritirata e nessuno viene addebitato.",
    withdrawPending: "Elaborazione…",
    cancel: "Annulla",

    statusAwaitingApproval: "In attesa di approvazione",
    statusApproved: "Approvata, in attesa di pagamento",
    statusDeclined: "Rifiutata",
    statusOrdered: "Ordinata",
    statusCancelled: "Annullata",

    eyebrow: "Portale regali",
    notFoundTitle: "Non riusciamo a trovare questa pagina",
    notFoundBody:
      "L’indirizzo potrebbe essere errato, oppure la campagna o il prodotto a cui puntava è stato chiuso da quando il link è stato inviato. Il catalogo è comunque aperto.",
    notFoundBoundaryBody:
      "Il link potrebbe essere scaduto, oppure il catalogo regali può essere stato chiuso dall’azienda che lo ha creato. Se qualcuno vi ha inviato questo link, chiedetene uno aggiornato.",
    errorTitle: "Qualcosa è andato storto da parte nostra",
    errorBody:
      "Questa pagina non è stata caricata. Nulla di quanto avete inviato è andato perduto: riprovate e, se continua, tornate tra qualche minuto.",
    errorRetry: "Riprova",
    errorReference: "Riferimento {digest}",
    goToParcelith: "Vai su Parcelith",
  },

  fallback: {
    notFoundTitle: "Non troviamo questa pagina",
    notFoundBody:
      "Il link potrebbe non essere più valido oppure il prodotto non è più in vendita. Tutto ciò che {store} offre oggi è a portata di clic.",
    browseProducts: "Vedi tutti i prodotti",
    errorTitle: "Qualcosa è andato storto da parte nostra",
    errorBody:
      "Non è stato possibile caricare questa pagina. Il tuo carrello è intatto: riprova e, se il problema persiste, torna tra qualche minuto.",
    errorRetry: "Riprova",
    errorHome: "Torna a {store}",
    errorReference: "Riferimento {digest}",
  },
};
