import type { StorefrontCopy } from "./en";

/** Storefront copy, Japanese. */
export const ja: StorefrontCopy = {
  chrome: {
    shop: "ショップ",
    currencyLabel: "通貨",
    currencyApply: "適用",
    basket: "カート",
    basketWithCount: "カート（{count}）",
    basketClose: "カートを閉じる",
    operatedBy: "運営：{client}。受注生産で世界中へお届けします。",
    allProducts: "すべての商品",
    orderStatus: "注文状況",
    delivery: "配送",
    help: "お問い合わせ",
    supportEmailLabel: "メール",
    supportPhoneLabel: "電話",
    supportPending: "サポートの連絡先はまだ公開されていません。",
    carriersPending: "配送業者を設定中です",
    pricesShownIn: "表示価格の通貨は {currency}{tax}。",
    taxIncluded: "（税込）",
    taxAtCheckout: "（税は購入手続きで加算されます）",
    legal:
      "© {year} {client}。本ストアの販売者は {client} です。ストアフロントの提供は Parcelith。",
  },

  meta: {
    homeTitle: "{store} — 受注生産のオリジナルグッズ",
    homeDescription:
      "{client} の公式ストア {store}。受注生産で世界中へお届けします。",
    taglineDescription:
      "{tagline} {client} の公式ストア {store}。",
    shopTitle: "ショップ",
    shopDescription: "{store} で取り扱っているすべての商品。",
  },

  home: {
    closedTitle: "このストアは閉店しました",
    closedBody:
      "{client} は {store} をアーカイブしました。既存のご注文は引き続き出荷され、注文状況ページもご利用いただけます。",
    comingSoonTitle: "{store} はまもなく公開されます",
    comingSoonBody: "ストアフロントのレイアウトはまだ公開されていません。",
    comingSoonWithProducts: "商品は公開済みで、今すぐご覧いただけます。",
    comingSoonNoProducts: "しばらくしてからもう一度ご覧ください。",
    browseProducts: "{count} 点の商品を見る",
  },

  shop: {
    title: "ショップの全商品",
    intro: "受注生産で世界中へお届けします。価格の通貨は {currency}{tax}。",
    taxIncluded: "（税込）",
    taxAtCheckout: "（税は購入手続きで加算されます）",
    searchLabel: "検索",
    searchPlaceholder: "Tシャツ、パーカー、マグ…",
    searchSubmit: "検索",
    clear: "クリア",
    filterByTag: "タグで絞り込む",
    emptyTitle: "まだ公開された商品はありません",
    emptyBody: "このストアはまだ商品を公開していません。またのぞいてみてください。",
    noMatchTitle: "条件に一致する商品はありません",
    noMatchBody: "別のキーワードで検索するか、絞り込みを解除してください。",
    clearFilters: "絞り込みを解除",
    personalise: "カスタマイズ可",
    previewSoon: "プレビューは近日公開",
  },

  product: {
    breadcrumb: "パンくずリスト",
    breadcrumbShop: "ショップ",
    about: "この商品について",
    madeToOrder: "受注生産",
    producedBy: "{supplier} が{lead}で製作し、{carriers}で発送します。",
    defaultSupplier: "当社の製造パートナー",
    leadDays: "{from}〜{to} 日",
    leadUnknown: "数日",
    defaultCarrier: "当社の配送業者",
    carrierJoin: "または",
    printDetail: "プリント仕様",
    printDetailBody: "{area}、{width} × {height} mm、最低 {dpi} DPI でプリントします。",
    taxAndDelivery: "税と配送",
    pricesShownIn: "表示価格の通貨は {currency}{tax}。",
    taxIncluded: "（税込）",
    taxAtCheckout: "（税は購入手続きで計算されます）",
    merchantOfRecord: "このご注文の販売者は {client} です。",
  },

  purchase: {
    addToBasket: "カートに入れる",
    adding: "追加中…",
    viewBasket: "カートを見る",
    colour: "カラー",
    size: "サイズ",
    option: "オプション",
    required: "必須",
    quantity: "数量",
    lowStock: "残りわずか",
    noPreview: "プレビューはありません",
    previewAlt: "{name} のプレビュー",
    viewAlt: "{view} のビュー",
    livePreview:
      "リアルタイムのプレビューです。カートに入れると、実際の製作に合わせたプレビューが添付されます。",
    textPlaceholder: "任意",
    textCounter: "{count}/{max} 文字。デザインと一緒にプリントされます。",
    artworkLabel: "お手持ちのデザイン",
    artworkHint:
      "{width} × {height} mm にプリントするため、{dpi} DPI 以上が必要です。{formats}、{max} MB まで。",
    artworkHintSimple: "PNG、JPG、WEBP に対応しています。",
    uploading: "デザインをアップロードしています…",
    uploadFailed: "このファイルはアップロードできませんでした。",
    fileTooLarge: "このファイルは {size} MB です。上限は {limit} MB です。",
    artworkPlacementTitle: "デザインの配置",
    artworkPlacementHelp:
      "プレビュー上でデザインをドラッグするか、下のコントロールで調整してください。プレビューとプリント解像度はその都度更新されます。",
    artworkGrabLabel:
      "{file} の配置です。ドラッグまたは矢印キーで移動、+ と − で拡大縮小できます。",
    artworkSize: "サイズ",
    artworkRotation: "回転",
    artworkResolution: "プリント解像度",
    artworkRecentre: "中央に戻す",
    artworkRemove: "デザインを削除",
    artworkChecksPass: "このサイズでプリントできるデザインです。",
    artworkChecksFail: "カートに入れる前にご対応ください",
    artworkWhatToDo: "対処方法: {fix}",
    artworkBlocked: "上のデザインを修正するか削除すると、カートに追加できます。",
  },

  basket: {
    title: "カート",
    emptyTitle: "カートはまだ空です",
    emptyBody:
      "商品とカスタマイズを追加すると、ご注文に添付されるプレビューとともにここに表示されます。",
    browseShop: "ショップを見る",
    previewAlt: "{name} のプレビュー",
    personalisation: "カスタマイズ：",
    artwork: "デザイン：{file}",
    quantity: "数量",
    update: "更新",
    remove: "削除",
    summary: "ご注文内容",
    subtotal: "小計",
    shipping: "送料",
    taxRow: "税 {rate}%",
    taxIncludedSuffix: "（込）",
    total: "合計",
    checkout: "購入手続きへ",
    keepShopping: "買い物を続ける",
  },

  discount: {
    title: "割引コード",
    label: "コード",
    placeholder: "SPRING10",
    apply: "適用",
    applying: "適用中…",
    remove: "削除",
    row: "割引（{code}）",
    applied: "コード {code} を適用しました（{amount} 引き）。",
    removed: "割引コードを削除しました。",
    enterCode: "割引コードをご入力ください。",
    unknown: "そのコードは確認できません。",
    inactive: "そのコードは現在ご利用いただけません。",
    expired: "そのコードは有効期限が切れています。",
    limitReached: "そのコードは利用上限に達しています。",
    belowMinimum: "そのコードは {amount} 以上のご購入で利用できます。",
    dropped:
      "コード {code} はこのカートには適用できなくなったため、削除しました。お支払いの前に合計をご確認ください。",
  },

  checkout: {
    title: "購入手続き",
    merchantNote: "販売者は {client} です。お支払いは {client} 自身の Stripe アカウントに入金されます。",
    unavailableTitle: "このストアはまだお支払いを受け付けられません",
    unavailableBody:
      "ストアの Stripe アカウント接続が完了していません。カートの内容は保存されています。ストアが公開されたら、あらためてお試しください。",
    backToBasket: "カートに戻る",
    summaryTitle: "ご注文内容",
    shipping: "送料",
    taxRow: "税 {rate}%",
    taxIncludedSuffix: "（込）",
    total: "合計",
    deliveryDetails: "お届け先",
    fullName: "お名前",
    email: "メールアドレス",
    emailHint: "このアドレスと注文コードで、あとから注文ページを開けます。",
    street: "住所",
    city: "市区町村",
    postalCode: "郵便番号",
    country: "国",
    countryHint: "入力すると国を絞り込めます。製造拠点はお届け先によって決まります。",
    countrySearchPlaceholder: "国を検索",
    countryNoMatch: "「{query}」に一致する国はありません。",
    payIn: "お支払い通貨",
    manualRoutingTitle: "{country} へのお届けは手動での手配が必要です",
    manualRoutingLine: "{supplier} は {products} を製作していますが、{country}（{region}）には配送していません。",
    productJoin: "と",
    manualRoutingBody:
      "そのままお支払いいただけますが、ご注文は担当者が別の製造パートナーへ手配するまで保留となるため、通常より日数がかかります。ご利用の製造パートナーが対応している国を選ぶと、この待ち時間を避けられます。",
    paymentTitle: "お支払い",
    paymentNote:
      "このストア自身の Stripe アカウント {account} で決済されます。カード情報がストアに保存されることはありません。",
    cardNumber: "カード番号",
    expiry: "有効期限（MM/YY）",
    securityCode: "セキュリティコード",
    testMode: "Stripe テストモード",
    submit: "支払って注文する",
    pending: "決済処理中…",
    cardSucceeds: "Visa — 成功",
    cardDeclined: "Visa — カード会社により拒否",
    cardInsufficient: "Visa — 残高不足",
  },

  order: {
    title: "注文状況",
    lookupIntro:
      "注文コードと、購入手続きでご入力いただいたメールアドレスを入力してください。ご注文時に保存したリンクからは直接開けます。",
    gateBody:
      "お届け先とカスタマイズの内容を保護するため、注文 {code} のメールアドレスをご確認のうえ表示します。",
    confirmedTitle: "ありがとうございます — ご注文を承りました",
    confirmedBody:
      "このページを保存するかブックマークしてください。ご注文の進み具合はここに表示されます。このリンクを記載した確認メールをお送りしました。",
    confirmedFindAgain:
      "「注文状況」から、注文コード {code} とメールアドレス {email} を入力しても開けます。",
    heading: "注文 {code}",
    placed: "注文日時：{when}",
    trackWith: "{carrier} で追跡する ↗",
    whatYouOrdered: "ご注文の内容",
    variantQuantity: "{variant}・数量 {count}",
    personalisation: "カスタマイズ：",
    previewAlt: "{name} のプレビュー",
    subtotal: "小計",
    shipping: "送料",
    taxRow: "税 {rate}%",
    paid: "お支払い額",
    refunded: "返金額",
    deliveringTo: "お届け先",
    payment: "お支払い",
    cardEnding: "下4桁 {last4} のカード",
    card: "カード",
    paidWord: "支払い済み",
    refundedWord: "返金済み",
    merchantOfRecord: "販売者は {client} です。",
    progress: "進捗",
    supportTitle: "このご注文についてのお問い合わせ",
    contactSubject: "注文 {code}",
    continueShopping: "買い物を続ける",
    contactStore: "ストアに問い合わせる",
    orderCode: "注文コード",
    orderCodeHint: "ORD- で始まり、注文ページの上部に表示されています。",
    emailOnOrder: "ご注文時のメールアドレス",
    emailHint: "購入手続きでご入力いただいたアドレスです。",
    lookupSubmit: "注文を表示する",
    lookupPending: "確認中…",
  },

  status: {
    awaitingPayment: "お支払い待ち",
    awaitingPaymentNote: "このご注文のお支払いはまだ確認できていません。",
    paid: "お支払いを確認しました",
    paidNote: "ご注文は製作の順番待ちです。",
    inProduction: "製作中",
    inProductionNote: "商品をプリントし、仕上げているところです。",
    shipped: "発送済み",
    shippedNote: "お荷物は配送中です。下のリンクから追跡できます。",
    delivered: "お届け済み",
    deliveredNote: "お荷物をお届けしました。どうぞお楽しみください。",
    cancelled: "キャンセル済み",
    cancelledNote: "このご注文はキャンセルされました。お支払い分は返金済みです。",
    exception: "対応が必要です",
    exceptionNote: "このご注文は保留になっています。ストアの担当者が対応し、追ってご連絡します。",
  },

  actions: {
    storeClosed: "このストアは現在ご注文を受け付けていません。",
    productGone: "この商品は現在お取り扱いがありません。",
    chooseVariant: "サイズとカラーをお選びください。",
    outOfStock: "{variant} は在庫切れです。別のオプションをお選びください。",
    noTextPersonalisation: "この商品にはテキストのカスタマイズができません。",
    textTooLong: "カスタマイズは {max} 文字以内にしてください。",
    noArtworkUpload: "この商品はデザインのアップロードに対応していません。",
    productUnavailable: "この商品は一時的にご利用いただけません。",
    fileTooLarge: "このファイルは {size} MB です。上限は {limit} MB です。",
    basketUnavailable: "カートを開けませんでした。Cookie を有効にして、もう一度お試しください。",
    addedToBasket: "{product} をカートに追加しました。",
    basketEmpty: "カートは空です。",
    enterName: "お届け先のお名前をご入力ください。",
    enterEmail: "メールアドレスをご入力ください。あとから注文ページを開くために使います。",
    enterStreet: "住所をご入力ください。",
    enterCity: "市区町村をご入力ください。",
    enterPostalCode: "郵便番号をご入力ください。",
    chooseCountry: "お届け先の国を一覧からお選びください。",
    currencyNotSold: "{currency} はこのストアの販売通貨ではありません。",
    enterOrderCode: "注文コードをご入力ください。",
    enterOrderEmail: "ご注文時のメールアドレスをご入力ください。",
    lookupFailed:
      "注文コードとメールアドレスが一致しませんでした。両方をご確認のうえ、もう一度お試しください。",
  },

  artwork: {
    lowDpi: "この画像は {dpi} DPI でプリントされ、この商品に必要な {required} DPI を下回ります。",
    lowDpiFix:
      "幅 {pixels} ピクセル以上のファイルをアップロードするか、デザインを小さくしてください。このファイルは幅 {width} mm まで鮮明です。",
    badFormat: "{format} ファイルはこの商品では使用できません。",
    badFormatFix: "{formats} で保存して、もう一度選択してください。",
    unreadableFormat: "{format} ファイルはここでは計測もプレビューもできません。",
    unreadableFormatFix: "{formats} で保存して、もう一度選択してください。",
    fileTooLarge: "このファイルは {size} MB です。上限は {limit} MB です。",
    fileTooLargeFix: "サイズや画質を下げて保存し、もう一度選択してください。",
    tooManyPixels: "この画像は大きすぎます。上限は {megapixels} メガピクセルです。",
    tooManyPixelsFix: "画像編集アプリで縮小して、もう一度選択してください。",
    noTransparency:
      "この商品は生地に直接プリントするため、デザインには透明な背景が必要です。",
    noTransparencyFix: "背景を削除し、透過 PNG として保存してください。",
    outsideArea: "デザインの一部がプリント範囲からはみ出しており、切れてしまいます。",
    outsideAreaFix:
      "破線の枠内へ戻すか、{width} × {height} mm に収まるよう小さくしてください。",
    dpiTight: "この画像は {dpi} DPI でプリントされ、最低の {required} DPI をわずかに上回るだけです。",
    dpiTightFix:
      "細い線がぼやけることがあります。より大きなファイル、または少し小さめのデザインのほうが鮮明です。",
    verySmall: "デザインがプリント幅の 15% 未満しか占めていません。",
    verySmallFix: "メインのグラフィックにする場合は、サイズを大きくしてください。",
    generic: "このデザインはこの商品にプリントできません。",
    genericFix: "別のファイルをお試しください。",
  },

  payment: {
    accountNotReady:
      "このストアは Stripe アカウントの接続が完了していないため、お支払いをご利用いただけません。",
    currencyUnsupported: "{currency} はこのストアの販売通貨ではありません。",
    invalidNumber: "このカード番号は正しくありません。数字をご確認のうえ、もう一度お試しください。",
    invalidExpiry: "有効期限が過ぎているか、形式が正しくありません。MM/YY の形式でご入力ください。",
    invalidCvc: "セキュリティコードは 3 桁または 4 桁です。",
    declined: "カード発行会社により、お支払いが承認されませんでした。",
    insufficientFunds: "カードの残高が不足しています。",
    expiredCard: "カードの有効期限が切れています。",
  },

  sections: {
    viewAll: "すべて見る",
    noProducts: "このストアにはまだ公開中の商品がありません。公開すると自動的にここに表示されます。",
    previewSoon: "プレビューは近日公開",
    imagePlaceholder: "セクション設定で画像 URL を追加してください",
    newsletterEmail: "メールアドレス",
    notifyMe: "お知らせを受け取る",
    welcome: "ようこそ",
  },

  email: {
    logoAlt: "{store}",
    greeting: "{name} 様",
    footer: "このストアの販売事業者は {client} です。{store} より送信しています。",
    support: "ご不明な点は {email} までご連絡ください。",
    orderSubject: "ご注文 {code} を承りました — {store}",
    orderHeading: "ご注文ありがとうございます",
    orderBody:
      "ご注文 {code} を承り、お支払いが完了しました。下のリンクからいつでも進捗ページを開けますので、保存しておいてください。",
    orderCta: "注文を確認する",
    orderTotalLabel: "お支払い金額",
    orderDeliveryLabel: "お届け先",
    shippedSubject: "ご注文 {code} を発送しました — {store}",
    shippedHeading: "お荷物を発送しました",
    shippedBody: "ご注文 {code} を {carrier} に引き渡しました。",
    shippedTrackingLabel: "追跡番号",
    shippedCta: "配送状況を見る",
    inviteSubject: "{inviter} さんが {store} に招待しています",
    inviteHeading: "{store} に招待されました",
    inviteBody:
      "{inviter} さんが、{role} として {store} に参加するよう招待しています。下のリンクを開くとアカウントが作成され、アクセスが有効になります。リンクは一度だけ有効です。",
    inviteCta: "招待を受ける",
    approvalSubject: "ギフトキャンペーン {code} の承認をお願いします — {store}",
    approvalHeading: "承認待ちのギフトキャンペーンがあります",
    approvalBody:
      "{buyer} さんが {company} 向けに「{campaign}」を申請しました。承認されるまで請求は発生しません。",
    approvalRecipientsLabel: "受取人",
    approvalTotalLabel: "合計",
    approvalCta: "リストを確認する",
  },

  gift: {
    chromeSubtitle: "ギフトカタログ · {store}",
    private: "非公開",
    operatedBy:
      "販売事業者は {client} です。ギフトは受注後に製作し、受取人ごとに個別に発送します。",
    supportTitle: "キャンペーンに関するお問い合わせ:",
    supportPending: "{client} はまだサポート連絡先を公開していません。",
    legal: "© {year} {client}. 法人ギフトは Parcelith が提供しています。",

    closedTitle: "このカタログは閉じられています",
    closedBody:
      "{company} のギフトプログラムは一時停止中です。運営担当者が再開できます。すでに発注済みのキャンペーンには影響しません。",

    privateBadge: "非公開カタログ",
    inviteBody:
      "{company} のギフトカタログは招待された方のみご利用いただけます。招待が届いたアドレスをご確認いただければ、そのまま入れます。",
    linkOnlyBody:
      "このカタログは {company} のプログラム担当者が共有した非公開リンクから開きます。そのリンクをもう一度お使いいただくか、新しいリンクを担当者にお尋ねください。担当が変わるたびにリンクは更新されます。",
    gateEmail: "勤務先メールアドレス",
    gateEmailHint: "プログラム担当者が招待したアドレスのいずれかである必要があります。",
    gateSubmit: "カタログを開く",
    gatePending: "確認中…",

    introFallback:
      "{company} のためのギフトです。受注後に製作し、受取人ごとに個別にお届けします。",
    startOrder: "一括注文を始める",
    spendLimitLabel: "受取人ごとの上限金額",
    noLimit: "上限なし",
    approvalLabel: "承認",
    approvalRequired: "必要",
    approvalNotRequired: "不要",
    recipientsLabel: "1キャンペーンの受取人数",
    recipientsUpTo: "最大 {count} 名",
    emptyTitle: "現在ご利用いただけるギフトはありません",
    emptyBody:
      "このカタログの商品は現在製作されていません。プログラムの運営担当者が再開時期をご案内できます。",
    giftsTitle: "このカタログのギフト",
    previewSoon: "プレビューは近日公開",
    overLimit: "上限超過",
    sizes: "サイズ: {sizes}",
    oneSize: "フリーサイズ",
    overLimitTitle: "一部のギフトが上限金額を超えています",
    overLimitBody:
      "これらを指定した受取人はリスト読み込み時に除外されるため、承認を依頼する前に該当行を修正できます。",
    howItWorks: "キャンペーンの流れ",
    step1Title: "ギフトを選ぶ",
    step1Body:
      "ここにあるものはすべてこのプログラム向けに製作済みで、選べるサイズもそろっています。",
    step2Title: "受取人リストを追加する",
    step2Body:
      "表計算ソフトから貼り付けるか、CSV をアップロードしてください。氏名・住所・サイズ、任意のメッセージを入力できます。",
    step3Title: "承認",
    step3Body: "支払いの前に、リストと合計金額が承認者へ渡ります。",
    step4Title: "支払いは1回、荷物は1人に1つ",
    step4Body:
      "お支払いは一度だけです。受取人それぞれに専用の荷物と追跡番号が用意されます。",

    orderTitle: "ギフトの一括注文",
    campaignTitle: "ギフトキャンペーン",
    orderIntro:
      "送付先の住所と着用サイズを添えて、お送りする方をすべて追加してください。リストは何度でも確認できます。送信する{approval}まで何も作成されません。",
    orderIntroApproval: "（承認へ）",
    paymentPendingTitle: "このストアではまだ決済が有効になっていません",
    paymentPendingBody:
      "キャンペーンの作成と承認依頼は可能です。{client} が決済アカウントの接続を完了するまで支払いはできません。",
    yourApprover: "承認者",

    buyerTitle: "ご注文者",
    campaignName: "キャンペーン名",
    campaignNamePlaceholder: "第4四半期の顧客向けギフト",
    buyerName: "お名前",
    orderingAs:
      "{email} として注文します。次に表示されるキャンペーンのリンクを保存してください。メールは送信されず、承認と領収内容はそのページに表示されます。",
    buyerEmail: "勤務先メールアドレス",
    buyerEmailHint:
      "キャンペーンの注文者として記録されます。次に表示されるキャンペーンのリンクを保存してください。メールは送信されず、承認と領収内容はそのページに表示されます。",
    giftTitle: "ギフト",
    giftHint: "商品名が書かれていない行すべてに適用されます。",
    giftHintLimit: "受取人ごとに {amount} まで利用できます。",
    giftHintNoLimit: "このプログラムに上限金額はありません。",
    listTitle: "受取人",
    listHintLead: "1行に1名、最大 {max} 名。列:",
    listHintTail: "見出し行は自動的に判別され、{product} と {note} は任意です。",
    uploadCsv: "CSV をアップロード",
    pasteExample: "例を貼り付ける",
    fileLoaded: "{file} を読み込みました",
    fileTooLarge: "{file} は {size} KB です。受取人リストは {limit} KB 未満にしてください。",
    fileUnreadable: "このファイルは読み込めませんでした。CSV として保存し直してお試しください。",
    listLabel: "受取人リスト",
    checkList: "リストを確認",
    checkPending: "リストを読み込み中…",
    sendForApproval: "承認へ送る",
    checkAndSend: "確認して送信",
    sendPending: "処理中…",
    previewRecipients: "受取人 {count} 名",
    previewToFix: "要修正 {count} 件",
    previewTotal: "合計 {amount}",
    previewOverflow: "上限を超えた {count} 行は読み込まれませんでした",
    columnLine: "行",
    columnRecipient: "受取人",
    columnGift: "ギフト",
    columnDelivered: "お届け",
    columnDelivery: "配送先",
    columnValue: "金額",
    noName: "名前なし",
    subtotal: "ギフト",
    shipping: "送料",
    tax: "税",
    taxRow: "税 {rate}%",
    total: "合計",
    approvalNote:
      "送信すると、キャンペーンは {approver} に渡ります。承認され、お支払いいただくまで請求は発生しません。",
    noApprovalNote:
      "このプログラムに承認は不要です。リストに問題がなければそのままお支払いへ進みます。",

    linkInvalidTitle: "このキャンペーンのリンクは無効です",
    linkInvalidBody:
      "キャンペーンのリンクは個別です。注文者用と承認者用が1つずつあります。ご自身のリンクを再送してもらうか、カタログを開いて新しく注文を作成してください。",
    backToCatalogue: "カタログに戻る",
    campaignSubmitted: "受取人 {count} 名 · {buyer} が {when} に送信",
    waitingTitle: "承認待ち",
    waitingBody:
      "{approver} がリストと合計金額を確認しています。承認されればすぐにお支払いいただけます。請求はまだ発生していません。",
    decisionTitle: "ご判断を記録しました",
    decisionBody: "{who} が {when} に{decision}しました。",
    decisionCanPay: "{buyer} がお支払いに進めます。あなたへの請求はありません。",
    decisionApproved: "承認",
    decisionDeclined: "却下",
    declinedNoReason: "理由は入力されていません。",
    declinedBody: "承認者の指摘を反映して、カタログから新しい注文を作成してください。",
    orderedTitle: "支払い済み・製作中",
    orderedBody:
      "受取人ごとに {count} 件の注文を作成しました。それぞれ個別の配送と追跡が付きます。下のリンクから確認できます。",
    unpayableTitle: "承認済みですが、ストアはまだ決済を受け付けられません",
    unpayableBody:
      "{client} が決済アカウントの接続を完了していません。キャンペーンは保存されており、接続が完了すればお支払いいただけます。",
    recipientsTitle: "受取人",
    track: "{code} を追跡",
    historyTitle: "履歴",
    totalsTitle: "キャンペーン合計",
    spendLimitNote: "受取人ごとの上限は {amount} です。",
    noSpendLimitNote: "このプログラムに上限金額はありません。",
    decisionFormTitle: "ご判断",
    paymentTitle: "お支払い",
    approvalIntro:
      "このキャンペーンを支払えるようにするには {buyer} があなたの承認を必要としています。承認しても請求は発生せず、支払いは注文者が自身の画面で行います。",
    noteLabel: "メモ（却下する場合は必須）",
    notePlaceholder: "第4四半期のマーケティング予算で承認します。",
    approve: "{total} を承認",
    approvePending: "ご判断を記録中…",
    decline: "却下",
    declinePending: "記録中…",
    paymentIntro:
      "キャンペーン全体を1回のお支払いで、ストア自身の Stripe アカウント {account} を通じて決済します。その後、受取人ごとに追跡付きの注文が作成されます。",
    pay: "{total} を支払う",
    payPending: "決済処理中…",
    withdraw: "このキャンペーンを取り下げる",
    withdrawConfirm: "キャンペーンを取り下げる",
    withdrawQuestion: "リストは取り下げられ、誰にも請求されません。",
    withdrawPending: "処理中…",
    cancel: "キャンセル",

    statusAwaitingApproval: "承認待ち",
    statusApproved: "承認済み・支払い待ち",
    statusDeclined: "却下",
    statusOrdered: "注文済み",
    statusCancelled: "取り消し",

    eyebrow: "ギフトポータル",
    notFoundTitle: "そのページは見つかりません",
    notFoundBody:
      "アドレスが間違っているか、リンク送信後にそのキャンペーンまたは商品が終了した可能性があります。カタログ自体は開いています。",
    notFoundBoundaryBody:
      "リンクの有効期限が切れたか、ギフトカタログを作成した企業が閉じた可能性があります。このリンクを受け取った方は、送り主に最新のリンクをお尋ねください。",
    errorTitle: "こちら側で問題が発生しました",
    errorBody:
      "このページを読み込めませんでした。送信された内容は失われていません。もう一度お試しいただき、続くようでしたら数分後にお越しください。",
    errorRetry: "再試行",
    errorReference: "参照番号 {digest}",
    goToParcelith: "Parcelith へ",
  },

  fallback: {
    notFoundTitle: "ページが見つかりません",
    notFoundBody:
      "リンクが古いか、商品の販売が終了した可能性があります。{store} で現在お取り扱いしている商品はこちらからご覧いただけます。",
    browseProducts: "すべての商品を見る",
    errorTitle: "問題が発生しました",
    errorBody:
      "このページを読み込めませんでした。カートの中身はそのまま残っています。もう一度お試しいただき、解決しない場合は数分後にアクセスしてください。",
    errorRetry: "再試行",
    errorHome: "{store} に戻る",
    errorReference: "参照番号 {digest}",
  },
};
