import type { StorefrontCopy } from "./en";

/** Storefront copy, Japanese. */
export const ja: StorefrontCopy = {
  chrome: {
    shop: "ショップ",
    currencyLabel: "通貨",
    currencyApply: "適用",
    basket: "カート",
    basketWithCount: "カート（{count}）",
    operatedBy: "運営：{client}。受注生産で世界中へお届けします。",
    allProducts: "すべての商品",
    orderStatus: "注文状況",
    delivery: "配送",
    carriersPending: "配送業者を設定中です",
    pricesShownIn: "表示価格の通貨は {currency}{tax}。",
    taxIncluded: "（税込）",
    taxAtCheckout: "（税は購入手続きで加算されます）",
    legal:
      "© {year} {client}。本ストアの販売者は {client} です。ストアフロントの提供は Parcelith。",
  },

  meta: {
    homeTitle: "{store} — 受注生産のオリジナルグッズ",
    homeDescription:
      "{client} の公式ストア {store}。受注生産で世界中へお届けします。",
    shopTitle: "ショップ — {store}",
    shopDescription: "{store} で取り扱っているすべての商品。",
  },

  home: {
    closedTitle: "このストアは閉店しました",
    closedBody:
      "{client} は {store} をアーカイブしました。既存のご注文は引き続き出荷され、注文状況ページもご利用いただけます。",
    comingSoonTitle: "{store} はまもなく公開されます",
    comingSoonBody: "ストアフロントのレイアウトはまだ公開されていません。",
    comingSoonWithProducts: "商品は公開済みで、今すぐご覧いただけます。",
    comingSoonNoProducts: "しばらくしてからもう一度ご覧ください。",
    browseProducts: "{count} 点の商品を見る",
  },

  shop: {
    title: "ショップの全商品",
    intro: "受注生産で世界中へお届けします。価格の通貨は {currency}{tax}。",
    taxIncluded: "（税込）",
    taxAtCheckout: "（税は購入手続きで加算されます）",
    searchLabel: "検索",
    searchPlaceholder: "Tシャツ、パーカー、マグ…",
    searchSubmit: "検索",
    clear: "クリア",
    filterByTag: "タグで絞り込む",
    emptyTitle: "まだ公開された商品はありません",
    emptyBody: "このストアはまだ商品を公開していません。またのぞいてみてください。",
    noMatchTitle: "条件に一致する商品はありません",
    noMatchBody: "別のキーワードで検索するか、絞り込みを解除してください。",
    clearFilters: "絞り込みを解除",
    personalise: "カスタマイズ可",
    previewSoon: "プレビューは近日公開",
  },

  product: {
    breadcrumb: "パンくずリスト",
    breadcrumbShop: "ショップ",
    about: "この商品について",
    madeToOrder: "受注生産",
    producedBy: "{supplier} が{lead}で製作し、{carriers}で発送します。",
    defaultSupplier: "当社の製造パートナー",
    leadDays: "{from}〜{to} 日",
    leadUnknown: "数日",
    defaultCarrier: "当社の配送業者",
    carrierJoin: "または",
    printDetail: "プリント仕様",
    printDetailBody: "{area}、{width} × {height} mm、最低 {dpi} DPI でプリントします。",
    taxAndDelivery: "税と配送",
    pricesShownIn: "表示価格の通貨は {currency}{tax}。",
    taxIncluded: "（税込）",
    taxAtCheckout: "（税は購入手続きで計算されます）",
    merchantOfRecord: "このご注文の販売者は {client} です。",
  },

  purchase: {
    addToBasket: "カートに入れる",
    adding: "追加中…",
    viewBasket: "カートを見る",
    colour: "カラー",
    size: "サイズ",
    option: "オプション",
    required: "必須",
    quantity: "数量",
    lowStock: "残りわずか",
    noPreview: "プレビューはありません",
    previewAlt: "{name} のプレビュー",
    viewAlt: "{view} のビュー",
    livePreview:
      "リアルタイムのプレビューです。カートに入れると、実際の製作に合わせたプレビューが添付されます。",
    textPlaceholder: "任意",
    textCounter: "{count}/{max} 文字。デザインと一緒にプリントされます。",
    artworkLabel: "お手持ちのデザイン",
    artworkHint:
      "{width} × {height} mm にプリントするため、{dpi} DPI 以上が必要です。{formats}、{max} MB まで。",
    artworkHintSimple: "PNG、JPG、WEBP に対応しています。",
    uploading: "デザインをアップロードしています…",
    uploadFailed: "このファイルはアップロードできませんでした。",
    fileTooLarge: "このファイルは {size} MB です。上限は {limit} MB です。",
  },

  basket: {
    title: "カート",
    emptyTitle: "カートはまだ空です",
    emptyBody:
      "商品とカスタマイズを追加すると、ご注文に添付されるプレビューとともにここに表示されます。",
    browseShop: "ショップを見る",
    previewAlt: "{name} のプレビュー",
    personalisation: "カスタマイズ：",
    artwork: "デザイン：{file}",
    quantity: "数量",
    update: "更新",
    remove: "削除",
    summary: "ご注文内容",
    subtotal: "小計",
    shipping: "送料",
    taxRow: "税 {rate}%",
    taxIncludedSuffix: "（込）",
    total: "合計",
    checkout: "購入手続きへ",
    keepShopping: "買い物を続ける",
  },

  checkout: {
    title: "購入手続き",
    merchantNote: "販売者は {client} です。お支払いは {client} 自身の Stripe アカウントに入金されます。",
    unavailableTitle: "このストアはまだお支払いを受け付けられません",
    unavailableBody:
      "ストアの Stripe アカウント接続が完了していません。カートの内容は保存されています。ストアが公開されたら、あらためてお試しください。",
    backToBasket: "カートに戻る",
    summaryTitle: "ご注文内容",
    shipping: "送料",
    taxRow: "税 {rate}%",
    taxIncludedSuffix: "（込）",
    total: "合計",
    deliveryDetails: "お届け先",
    fullName: "お名前",
    email: "メールアドレス",
    emailHint: "注文確認と配送のお知らせをこちらにお送りします。",
    street: "住所",
    city: "市区町村",
    postalCode: "郵便番号",
    country: "国",
    countryHint: "入力すると国を絞り込めます。製造拠点はお届け先によって決まります。",
    countrySearchPlaceholder: "国を検索",
    countryNoMatch: "「{query}」に一致する国はありません。",
    payIn: "お支払い通貨",
    manualRoutingTitle: "{country} へのお届けは手動での手配が必要です",
    manualRoutingLine: "{supplier} は {products} を製作していますが、{country}（{region}）には配送していません。",
    productJoin: "と",
    manualRoutingBody:
      "そのままお支払いいただけますが、ご注文は担当者が別の製造パートナーへ手配するまで保留となるため、通常より日数がかかります。ご利用の製造パートナーが対応している国を選ぶと、この待ち時間を避けられます。",
    paymentTitle: "お支払い",
    paymentNote:
      "このストア自身の Stripe アカウント {account} で決済されます。カード情報がストアに保存されることはありません。",
    cardNumber: "カード番号",
    expiry: "有効期限（MM/YY）",
    securityCode: "セキュリティコード",
    testMode: "Stripe テストモード",
    submit: "支払って注文する",
    pending: "決済処理中…",
    cardSucceeds: "Visa — 成功",
    cardDeclined: "Visa — カード会社により拒否",
    cardInsufficient: "Visa — 残高不足",
  },

  order: {
    title: "注文状況",
    lookupIntro:
      "注文確認メールに記載された注文コードと、ご注文時のメールアドレスを入力してください。確認メール内のリンクからは直接ご注文を開けます。",
    gateBody:
      "お届け先とカスタマイズの内容を保護するため、注文 {code} のメールアドレスをご確認のうえ表示します。",
    confirmedTitle: "ありがとうございます — ご注文を承りました",
    confirmedBody:
      "{email} に確認メールをお送りしました。製作と配送の状況は、このページをブックマークしてご確認ください。",
    heading: "注文 {code}",
    placed: "注文日時：{when}",
    trackWith: "{carrier} で追跡する ↗",
    whatYouOrdered: "ご注文の内容",
    variantQuantity: "{variant}・数量 {count}",
    personalisation: "カスタマイズ：",
    previewAlt: "{name} のプレビュー",
    subtotal: "小計",
    shipping: "送料",
    taxRow: "税 {rate}%",
    paid: "お支払い額",
    refunded: "返金額",
    deliveringTo: "お届け先",
    payment: "お支払い",
    cardEnding: "下4桁 {last4} のカード",
    card: "カード",
    paidWord: "支払い済み",
    refundedWord: "返金済み",
    merchantOfRecord: "販売者は {client} です。",
    progress: "進捗",
    continueShopping: "買い物を続ける",
    contactStore: "ストアに問い合わせる",
    orderCode: "注文コード",
    orderCodeHint: "注文確認メールに記載されており、ORD- で始まります。",
    emailOnOrder: "ご注文時のメールアドレス",
    emailHint: "確認メールをお送りしたアドレスです。",
    lookupSubmit: "注文を表示する",
    lookupPending: "確認中…",
  },

  status: {
    awaitingPayment: "お支払い待ち",
    awaitingPaymentNote: "このご注文のお支払いはまだ確認できていません。",
    paid: "お支払いを確認しました",
    paidNote: "ご注文は製作の順番待ちです。",
    inProduction: "製作中",
    inProductionNote: "商品をプリントし、仕上げているところです。",
    shipped: "発送済み",
    shippedNote: "お荷物は配送中です。下のリンクから追跡できます。",
    delivered: "お届け済み",
    deliveredNote: "お荷物をお届けしました。どうぞお楽しみください。",
    cancelled: "キャンセル済み",
    cancelledNote: "このご注文はキャンセルされました。お支払い分は返金済みです。",
    exception: "対応が必要です",
    exceptionNote: "このご注文は保留になっています。ストアの担当者が対応し、追ってご連絡します。",
  },

  actions: {
    storeClosed: "このストアは現在ご注文を受け付けていません。",
    productGone: "この商品は現在お取り扱いがありません。",
    chooseVariant: "サイズとカラーをお選びください。",
    outOfStock: "{variant} は在庫切れです。別のオプションをお選びください。",
    noTextPersonalisation: "この商品にはテキストのカスタマイズができません。",
    textTooLong: "カスタマイズは {max} 文字以内にしてください。",
    noArtworkUpload: "この商品はデザインのアップロードに対応していません。",
    productUnavailable: "この商品は一時的にご利用いただけません。",
    fileTooLarge: "このファイルは {size} MB です。上限は {limit} MB です。",
    basketUnavailable: "カートを開けませんでした。Cookie を有効にして、もう一度お試しください。",
    addedToBasket: "{product} をカートに追加しました。",
    basketEmpty: "カートは空です。",
    enterName: "お届け先のお名前をご入力ください。",
    enterEmail: "ご注文の状況をお知らせできるよう、メールアドレスをご入力ください。",
    enterStreet: "住所をご入力ください。",
    enterCity: "市区町村をご入力ください。",
    enterPostalCode: "郵便番号をご入力ください。",
    chooseCountry: "お届け先の国を一覧からお選びください。",
    currencyNotSold: "{currency} はこのストアの販売通貨ではありません。",
    enterOrderCode: "注文コードをご入力ください。",
    enterOrderEmail: "ご注文時のメールアドレスをご入力ください。",
    lookupFailed:
      "注文コードとメールアドレスが一致しませんでした。両方をご確認のうえ、もう一度お試しください。",
  },

  artwork: {
    lowDpi: "このデザインはプリント解像度が不足しています。{dpi} DPI 以上のファイルをアップロードしてください。",
    badFormat: "{format} ファイルはこの商品では使用できません。{formats} をアップロードしてください。",
    fileTooLarge: "このファイルは {size} MB です。上限は {limit} MB です。",
    tooManyPixels:
      "この画像は大きすぎます。{megapixels} メガピクセル未満に縮小して、もう一度お試しください。",
    noTransparency:
      "この商品には背景が透明なデザインが必要です。透過 PNG として書き出してください。",
    generic: "このデザインはこの商品にプリントできません。別のファイルをお試しください。",
  },

  payment: {
    accountNotReady:
      "このストアは Stripe アカウントの接続が完了していないため、お支払いをご利用いただけません。",
    currencyUnsupported: "{currency} はこのストアの販売通貨ではありません。",
    invalidNumber: "このカード番号は正しくありません。数字をご確認のうえ、もう一度お試しください。",
    invalidExpiry: "有効期限が過ぎているか、形式が正しくありません。MM/YY の形式でご入力ください。",
    invalidCvc: "セキュリティコードは 3 桁または 4 桁です。",
    declined: "カード発行会社により、お支払いが承認されませんでした。",
    insufficientFunds: "カードの残高が不足しています。",
    expiredCard: "カードの有効期限が切れています。",
  },

  sections: {
    viewAll: "すべて見る",
    noProducts: "このストアにはまだ公開中の商品がありません。公開すると自動的にここに表示されます。",
    previewSoon: "プレビューは近日公開",
    imagePlaceholder: "セクション設定で画像 URL を追加してください",
    newsletterEmail: "メールアドレス",
    notifyMe: "お知らせを受け取る",
    welcome: "ようこそ",
  },

  fallback: {
    notFoundTitle: "ページが見つかりません",
    notFoundBody:
      "リンクが古いか、商品の販売が終了した可能性があります。{store} で現在お取り扱いしている商品はこちらからご覧いただけます。",
    browseProducts: "すべての商品を見る",
    errorTitle: "問題が発生しました",
    errorBody:
      "このページを読み込めませんでした。カートの中身はそのまま残っています。もう一度お試しいただき、解決しない場合は数分後にアクセスしてください。",
    errorRetry: "再試行",
    errorHome: "{store} に戻る",
    errorReference: "参照番号 {digest}",
  },
};
