import type { StorefrontCopy } from "./en";

/** Storefront copy, Dutch. */
export const nl: StorefrontCopy = {
  chrome: {
    shop: "Shop",
    currencyLabel: "Valuta",
    currencyApply: "Toepassen",
    basket: "Winkelmand",
    basketWithCount: "Winkelmand ({count})",
    basketClose: "Winkelmand sluiten",
    operatedBy: "Beheerd door {client}. Op bestelling gemaakt en wereldwijd verzonden.",
    allProducts: "Alle producten",
    orderStatus: "Bestelstatus",
    delivery: "Verzending",
    help: "Hulp",
    supportEmailLabel: "E-mail",
    supportPhoneLabel: "Telefoon",
    supportPending: "Contactgegevens voor vragen zijn nog niet gepubliceerd.",
    carriersPending: "Vervoerders worden nog ingesteld",
    pricesShownIn: "Prijzen in {currency}{tax}.",
    taxIncluded: ", inclusief btw",
    taxAtCheckout: ", btw wordt bij het afrekenen toegevoegd",
    legal:
      "© {year} {client}. {client} is de verkoper van deze winkel. Storefront mogelijk gemaakt door Parcelith.",
  },

  meta: {
    homeTitle: "{store} — merch op bestelling",
    homeDescription:
      "Shop bij {store}, de officiële winkel van {client}. Op bestelling gedrukt en wereldwijd verzonden.",
    taglineDescription:
      "{tagline} Shop bij {store}, de officiële winkel van {client}.",
    shopTitle: "Shop",
    shopDescription: "Alle producten die {store} aanbiedt.",
  },

  home: {
    closedTitle: "Deze winkel is gesloten",
    closedBody:
      "{client} heeft {store} gearchiveerd. Bestaande bestellingen worden nog geleverd en hun statuspagina’s blijven bereikbaar.",
    comingSoonTitle: "{store} is bijna klaar",
    comingSoonBody: "De indeling van de winkel is nog niet gepubliceerd.",
    comingSoonWithProducts: "De producten staan al online en zijn nu al te bekijken.",
    comingSoonNoProducts: "Kom binnenkort nog eens terug.",
    browseProducts: "Bekijk {count} producten",
  },

  shop: {
    title: "Alles in de shop",
    intro: "Op bestelling gemaakt en wereldwijd verzonden. Prijzen in {currency}{tax}.",
    taxIncluded: ", inclusief btw",
    taxAtCheckout: "; btw wordt bij het afrekenen toegevoegd",
    searchLabel: "Zoeken",
    searchPlaceholder: "T-shirt, hoodie, mok…",
    searchSubmit: "Zoeken",
    clear: "Wissen",
    filterByTag: "Filteren op label",
    emptyTitle: "Nog niets gepubliceerd",
    emptyBody: "Deze winkel heeft nog geen producten gepubliceerd. Kom snel terug.",
    noMatchTitle: "Geen producten gevonden voor deze zoekopdracht",
    noMatchBody: "Probeer een andere zoekterm of wis de filters.",
    clearFilters: "Filters wissen",
    personalise: "Personaliseerbaar",
    previewSoon: "Voorbeeld volgt binnenkort",
  },

  product: {
    breadcrumb: "Kruimelpad",
    breadcrumbShop: "Shop",
    about: "Over dit product",
    madeToOrder: "Op bestelling gemaakt",
    producedBy: "Gemaakt door {supplier} in {lead} en daarna verzonden met {carriers}.",
    defaultSupplier: "onze productiepartner",
    leadDays: "{from}–{to} dagen",
    leadUnknown: "een paar dagen",
    defaultCarrier: "onze vervoerder",
    carrierJoin: "of",
    printDetail: "Drukdetails",
    printDetailBody: "{area}, {width} × {height} mm, gedrukt op minimaal {dpi} DPI.",
    taxAndDelivery: "Btw en verzending",
    pricesShownIn: "Prijzen in {currency}{tax}.",
    taxIncluded: " inclusief btw",
    taxAtCheckout: "; btw wordt bij het afrekenen berekend",
    merchantOfRecord: "{client} is de verkoper van deze bestelling.",
  },

  purchase: {
    addToBasket: "In de winkelmand",
    adding: "Toevoegen…",
    viewBasket: "Winkelmand bekijken",
    colour: "Kleur",
    size: "Maat",
    option: "Optie",
    required: "Verplicht",
    quantity: "Aantal",
    lowStock: "bijna op",
    noPreview: "Geen voorbeeld beschikbaar",
    previewAlt: "Voorbeeld van {name}",
    viewAlt: "Aanzicht {view}",
    livePreview:
      "Live voorbeeld. Zodra je dit in de winkelmand legt, wordt een productiegetrouwe versie meegestuurd.",
    textPlaceholder: "Optioneel",
    textCounter: "{count}/{max} tekens. Wordt met het ontwerp meegedrukt.",
    artworkLabel: "Je eigen ontwerp",
    artworkHint:
      "Gedrukt op {width} × {height} mm, dus we hebben minimaal {dpi} DPI nodig. {formats} tot {max} MB.",
    artworkHintSimple: "PNG, JPG of WEBP.",
    uploading: "Je ontwerp wordt geüpload…",
    uploadFailed: "Dit bestand kon niet worden geüpload.",
    fileTooLarge: "Dit bestand is {size} MB. De limiet is {limit} MB.",
    artworkPlacementTitle: "Plaats je ontwerp",
    artworkPlacementHelp:
      "Sleep het ontwerp op de voorvertoning of gebruik de schuifregelaars hieronder. De voorvertoning en de drukresolutie volgen elke wijziging.",
    artworkGrabLabel:
      "Positie van {file}. Sleep om te verplaatsen of gebruik de pijltoetsen; + en − passen de grootte aan.",
    artworkSize: "Grootte",
    artworkRotation: "Rotatie",
    artworkResolution: "Drukresolutie",
    artworkRecentre: "Opnieuw centreren",
    artworkRemove: "Ontwerp verwijderen",
    artworkChecksPass: "Dit ontwerp kan op deze grootte worden gedrukt.",
    artworkChecksFail: "Los dit op voordat je het in je mandje legt",
    artworkWhatToDo: "Wat te doen: {fix}",
    artworkBlocked:
      "Los het ontwerp hierboven op, of verwijder het, om dit artikel in je mandje te leggen.",
  },

  basket: {
    title: "Je winkelmand",
    emptyTitle: "Nog niets in de winkelmand",
    emptyBody:
      "Voeg een product met eventuele personalisatie toe: het verschijnt hier met het voorbeeld dat bij je bestelling gaat.",
    browseShop: "Naar de shop",
    previewAlt: "Voorbeeld van {name}",
    personalisation: "Personalisatie:",
    artwork: "Ontwerp: {file}",
    quantity: "Aantal",
    update: "Bijwerken",
    remove: "Verwijderen",
    summary: "Overzicht",
    subtotal: "Subtotaal",
    shipping: "Verzending",
    taxRow: "Btw {rate}%",
    taxIncludedSuffix: "inbegrepen",
    total: "Totaal",
    checkout: "Afrekenen",
    keepShopping: "Verder winkelen",
  },

  discount: {
    title: "Kortingscode",
    label: "Code",
    placeholder: "SPRING10",
    apply: "Toepassen",
    applying: "Toepassen…",
    remove: "Verwijderen",
    row: "Korting ({code})",
    applied: "Code {code} toegepast — {amount} korting.",
    removed: "De kortingscode is verwijderd.",
    enterCode: "Vul een kortingscode in.",
    unknown: "We kennen deze code niet.",
    inactive: "Deze code is niet meer actief.",
    expired: "Deze code is verlopen.",
    limitReached: "Deze code is al het maximale aantal keren gebruikt.",
    belowMinimum: "Deze code vraagt een winkelmand van minstens {amount}.",
    dropped:
      "De code {code} geldt niet meer voor deze winkelmand en is verwijderd. Controleer je totaal voordat je betaalt.",
  },

  checkout: {
    title: "Afrekenen",
    merchantNote:
      "{client} is de verkoper. De betaling komt binnen op hun eigen Stripe-account.",
    unavailableTitle: "Deze winkel kan nog geen betalingen aannemen",
    unavailableBody:
      "De winkel heeft het koppelen van haar Stripe-account nog niet afgerond. Je winkelmand blijft bewaard — probeer het opnieuw zodra de winkel live is.",
    backToBasket: "Terug naar de winkelmand",
    summaryTitle: "Besteloverzicht",
    shipping: "Verzending",
    taxRow: "Btw {rate}%",
    taxIncludedSuffix: "inbegrepen",
    total: "Totaal",
    deliveryDetails: "Bezorggegevens",
    fullName: "Volledige naam",
    email: "E-mail",
    emailHint: "Met dit adres en je bestelcode open je later de pagina van je bestelling.",
    street: "Straat en huisnummer",
    city: "Plaats",
    postalCode: "Postcode",
    country: "Land",
    countryHint: "Begin te typen om je land te vinden. De productie wordt op bestemming gekozen.",
    countrySearchPlaceholder: "Landen zoeken",
    countryNoMatch: "Geen land komt overeen met “{query}”.",
    payIn: "Betalen in",
    manualRoutingTitle: "Bezorging naar {country} vraagt om handmatige toewijzing",
    manualRoutingLine: "{supplier} maakt {products} en levert niet aan {country} ({region}).",
    productJoin: "en",
    manualRoutingBody:
      "Je kunt gewoon betalen, maar de bestelling wordt vastgehouden totdat iemand die bij een andere productiepartner plaatst — dat duurt langer dan de gebruikelijke levertijd. Een bezorgland dat je leverancier wel dekt, voorkomt dit wachten.",
    paymentTitle: "Betaling",
    paymentNote:
      "Afgeschreven via het eigen Stripe-account van deze winkel {account}. Kaartgegevens worden nooit door de winkel bewaard.",
    cardNumber: "Kaartnummer",
    expiry: "Vervaldatum (MM/JJ)",
    securityCode: "Beveiligingscode",
    testMode: "Stripe-testmodus",
    submit: "Betalen en bestellen",
    pending: "Betaling wordt verwerkt…",
    cardSucceeds: "Visa — geslaagd",
    cardDeclined: "Visa — geweigerd door de bank",
    cardInsufficient: "Visa — onvoldoende saldo",
  },

  order: {
    title: "Bestelstatus",
    lookupIntro:
      "Vul je bestelcode in samen met het e-mailadres dat je bij het afrekenen hebt opgegeven. De link die je bij het bestellen hebt bewaard, opent de bestelling direct.",
    gateBody:
      "Om bezorg- en personalisatiegegevens te beschermen, bevestig eerst het e-mailadres bij bestelling {code} voordat we die tonen.",
    confirmedTitle: "Bedankt — je bestelling is bevestigd",
    confirmedBody:
      "Bewaar deze pagina of sla haar op als bladwijzer — hier zie je hoe je bestelling vordert. Er is een bevestigingsmail met deze link naar je onderweg.",
    confirmedFindAgain:
      "Je vindt haar ook terug via “Bestelstatus” met bestelcode {code} en het e-mailadres {email}.",
    heading: "Bestelling {code}",
    placed: "Geplaatst op {when}",
    trackWith: "Volgen met {carrier} ↗",
    whatYouOrdered: "Wat je hebt besteld",
    variantQuantity: "{variant} · aantal {count}",
    personalisation: "Personalisatie:",
    previewAlt: "Voorbeeld van {name}",
    subtotal: "Subtotaal",
    shipping: "Verzending",
    taxRow: "Btw {rate}%",
    paid: "Betaald",
    refunded: "Terugbetaald",
    deliveringTo: "Bezorgen aan",
    payment: "Betaling",
    cardEnding: "Kaart eindigend op {last4}",
    card: "Kaart",
    paidWord: "betaald",
    refundedWord: "terugbetaald",
    merchantOfRecord: "{client} is de verkoper.",
    progress: "Voortgang",
    supportTitle: "Vragen over deze bestelling",
    contactSubject: "Bestelling {code}",
    continueShopping: "Verder winkelen",
    contactStore: "Contact met de winkel",
    orderCode: "Bestelcode",
    orderCodeHint: "Begint met ORD- en staat bovenaan de pagina van je bestelling.",
    emailOnOrder: "E-mailadres van de bestelling",
    emailHint: "Het adres dat je bij het afrekenen hebt opgegeven.",
    lookupSubmit: "Toon mijn bestelling",
    lookupPending: "Bezig met controleren…",
  },

  status: {
    awaitingPayment: "Wacht op betaling",
    awaitingPaymentNote: "We hebben nog geen betaling voor deze bestelling ontvangen.",
    paid: "Betaling ontvangen",
    paidNote: "Je bestelling staat in de wachtrij voor productie.",
    inProduction: "In productie",
    inProductionNote: "Je artikel wordt gedrukt en afgewerkt.",
    shipped: "Verzonden",
    shippedNote: "Je pakket is onderweg. Volg het via de link hieronder.",
    delivered: "Bezorgd",
    deliveredNote: "Je pakket is bezorgd. Veel plezier ermee.",
    cancelled: "Geannuleerd",
    cancelledNote: "Deze bestelling is geannuleerd. Een eventuele betaling is terugbetaald.",
    exception: "Vraagt aandacht",
    exceptionNote:
      "Deze bestelling staat even stil. Het team van de winkel is ermee bezig en neemt contact op.",
  },

  actions: {
    storeClosed: "Deze winkel neemt op dit moment geen bestellingen aan.",
    productGone: "Dat product is niet meer beschikbaar.",
    chooseVariant: "Kies een maat en kleur.",
    outOfStock: "{variant} is uitverkocht. Kies een andere optie.",
    noTextPersonalisation: "Dit product kan niet met tekst worden gepersonaliseerd.",
    textTooLong: "Houd de personalisatie op {max} tekens of minder.",
    noArtworkUpload: "Dit product accepteert geen geüpload ontwerp.",
    productUnavailable: "Dit product is tijdelijk niet beschikbaar.",
    fileTooLarge: "Dit bestand is {size} MB. De limiet is {limit} MB.",
    basketUnavailable: "Je winkelmand kon niet worden geopend. Sta cookies toe en probeer het opnieuw.",
    addedToBasket: "{product} is aan je winkelmand toegevoegd.",
    basketEmpty: "Je winkelmand is leeg.",
    enterName: "Vul de naam voor de bezorging in.",
    enterEmail: "Vul een e-mailadres in — daarmee open je later je bestelling.",
    enterStreet: "Vul straat en huisnummer in.",
    enterCity: "Vul de plaats in.",
    enterPostalCode: "Vul de postcode in.",
    chooseCountry: "Kies je bezorgland uit de lijst.",
    currencyNotSold: "{currency} is geen verkoopvaluta van deze winkel.",
    enterOrderCode: "Vul je bestelcode in.",
    enterOrderEmail: "Vul het e-mailadres van de bestelling in.",
    lookupFailed:
      "We konden die bestelcode en dat e-mailadres niet aan elkaar koppelen. Controleer beide en probeer het opnieuw.",
  },

  artwork: {
    lowDpi: "Deze afbeelding wordt gedrukt op {dpi} DPI, onder de {required} DPI die dit product nodig heeft.",
    lowDpiFix:
      "Upload er een van minstens {pixels} pixels breed, of maak het ontwerp kleiner — dit bestand blijft scherp tot {width} mm breed.",
    badFormat: "{format}-bestanden worden voor dit product niet geaccepteerd.",
    badFormatFix: "Sla het ontwerp op als {formats} en kies het opnieuw.",
    unreadableFormat: "{format}-bestanden kunnen hier niet worden gemeten of getoond.",
    unreadableFormatFix: "Sla het ontwerp op als {formats} en kies het opnieuw.",
    fileTooLarge: "Dit bestand is {size} MB. De limiet is {limit} MB.",
    fileTooLargeFix: "Sla het kleiner of met lagere kwaliteit op en kies het opnieuw.",
    tooManyPixels: "Deze afbeelding is te groot. De limiet is {megapixels} megapixel.",
    tooManyPixelsFix: "Verklein hem in je fotobewerker en kies hem opnieuw.",
    noTransparency:
      "Dit product wordt rechtstreeks op de stof gedrukt, dus het ontwerp heeft een transparante achtergrond nodig.",
    noTransparencyFix: "Verwijder de achtergrond en sla het op als PNG met transparantie.",
    outsideArea: "Een deel van het ontwerp valt buiten het drukvlak en zou worden afgesneden.",
    outsideAreaFix:
      "Sleep het terug binnen de stippellijn, of maak het kleiner zodat het in {width} × {height} mm past.",
    dpiTight: "Deze afbeelding wordt gedrukt op {dpi} DPI, net boven het minimum van {required} DPI.",
    dpiTightFix:
      "Dunne lijnen kunnen zacht ogen. Een groter bestand, of een iets kleiner ontwerp, drukt scherper.",
    verySmall: "Het ontwerp beslaat minder dan 15% van de drukbreedte.",
    verySmallFix: "Schuif de grootte omhoog als dit de hoofdafbeelding moet zijn.",
    generic: "Dit ontwerp kan niet op dit product worden gedrukt.",
    genericFix: "Probeer een ander bestand.",
  },

  payment: {
    accountNotReady:
      "Deze winkel heeft het koppelen van haar Stripe-account nog niet afgerond, dus betalen kan nog niet.",
    currencyUnsupported: "{currency} is geen verkoopvaluta van deze winkel.",
    invalidNumber: "Dit kaartnummer is niet geldig. Controleer de cijfers en probeer het opnieuw.",
    invalidExpiry: "De vervaldatum ligt in het verleden of heeft een verkeerde notatie. Gebruik MM/JJ.",
    invalidCvc: "De beveiligingscode moet 3 of 4 cijfers hebben.",
    declined: "Je kaart is geweigerd door de uitgevende bank.",
    insufficientFunds: "Je kaart heeft onvoldoende saldo.",
    expiredCard: "Je kaart is verlopen.",
  },

  sections: {
    viewAll: "Alles bekijken",
    noProducts:
      "In deze winkel zijn nog geen producten gepubliceerd. Gepubliceerde producten verschijnen hier automatisch.",
    previewSoon: "Voorbeeld volgt binnenkort",
    imagePlaceholder: "Voeg in de sectie-instellingen een afbeeldings-URL toe",
    newsletterEmail: "E-mailadres",
    notifyMe: "Houd me op de hoogte",
    welcome: "Welkom",
  },

  email: {
    logoAlt: "{store}",
    greeting: "Hallo {name},",
    footer: "{client} is de verkoper van deze winkel. Verzonden door {store}.",
    support: "Vragen? Mail ons op {email}.",
    orderSubject: "Bestelling {code} is bevestigd — {store}",
    orderHeading: "Bedankt voor je bestelling",
    orderBody:
      "We hebben je bestelling {code} ontvangen en de betaling is gelukt. De link hieronder opent de statuspagina wanneer je maar wilt — bewaar hem goed.",
    orderCta: "Bekijk je bestelling",
    orderTotalLabel: "Totaal betaald",
    orderDeliveryLabel: "Bezorgen aan",
    shippedSubject: "Bestelling {code} is onderweg — {store}",
    shippedHeading: "Je pakket is onderweg",
    shippedBody: "Bestelling {code} is overgedragen aan {carrier}.",
    shippedTrackingLabel: "Trackingnummer",
    shippedCta: "Volg je pakket",
    inviteSubject: "{inviter} heeft je uitgenodigd voor {store}",
    inviteHeading: "Je bent uitgenodigd voor {store}",
    inviteBody:
      "{inviter} nodigt je uit om als {role} aan {store} te werken. Met de link hieronder wordt je account aangemaakt en je toegang geactiveerd. Hij werkt één keer.",
    inviteCta: "Uitnodiging accepteren",
    approvalSubject: "Geschenkcampagne {code} wacht op jouw goedkeuring — {store}",
    approvalHeading: "Een geschenkcampagne wacht op jouw goedkeuring",
    approvalBody:
      "{buyer} heeft “{campaign}” voor {company} ingediend. Er wordt niets afgeschreven voordat jij de lijst goedkeurt.",
    approvalRecipientsLabel: "Ontvangers",
    approvalTotalLabel: "Totaal",
    approvalCta: "Bekijk de lijst",
  },

  gift: {
    chromeSubtitle: "Cadeaucatalogus · {store}",
    private: "Privé",
    operatedBy:
      "Beheerd door {client}, die de verkopende partij is. Cadeaus worden op bestelling gemaakt en afzonderlijk naar elke ontvanger verzonden.",
    supportTitle: "Vragen over een campagne:",
    supportPending: "{client} heeft nog geen contactgegevens voor support gepubliceerd.",
    legal: "© {year} {client}. Zakelijke cadeaus mogelijk gemaakt door Parcelith.",

    closedTitle: "Deze catalogus is gesloten",
    closedBody:
      "Het cadeauprogramma van {company} staat op pauze. Degene die het voor u beheert kan het heropenen — al geplaatste campagnes blijven ongemoeid.",

    privateBadge: "Privécatalogus",
    inviteBody:
      "De cadeaucatalogus van {company} staat open voor uitgenodigde collega’s. Bevestig het adres waarnaar de uitnodiging is gestuurd en u komt er direct in.",
    linkOnlyBody:
      "Deze catalogus opent met de privélink die de beheerder van het programma van {company} heeft gedeeld. Gebruik die link opnieuw of vraag om een nieuwe — links worden vernieuwd zodra het programma in andere handen komt.",
    gateEmail: "Werk-e-mail",
    gateEmailHint: "Het moet een van de adressen zijn die uw programmabeheerder heeft uitgenodigd.",
    gateSubmit: "Catalogus openen",
    gatePending: "Controleren…",

    introFallback:
      "Cadeaus voor {company}, op bestelling gemaakt en afzonderlijk bij elke ontvanger bezorgd.",
    startOrder: "Bulkorder starten",
    spendLimitLabel: "Budget per ontvanger",
    noLimit: "Geen limiet",
    approvalLabel: "Goedkeuring",
    approvalRequired: "Vereist",
    approvalNotRequired: "Niet vereist",
    recipientsLabel: "Ontvangers per campagne",
    recipientsUpTo: "Tot {count}",
    emptyTitle: "Er zijn nu geen cadeaus beschikbaar",
    emptyBody:
      "Niets in deze catalogus is momenteel in productie. Degene die het programma voor u beheert weet wanneer het terug is.",
    giftsTitle: "Cadeaus in deze catalogus",
    previewSoon: "Voorbeeld volgt binnenkort",
    overLimit: "Boven het budget",
    sizes: "Maten: {sizes}",
    oneSize: "Eén maat",
    overLimitTitle: "Sommige cadeaus liggen boven uw budget",
    overLimitBody:
      "Een ontvanger die aan zo’n cadeau is gekoppeld wordt bij het inlezen van de lijst geweigerd, zodat de regel kan worden aangepast voordat iemand om goedkeuring wordt gevraagd.",
    howItWorks: "Zo werkt een campagne",
    step1Title: "Kies het cadeau",
    step1Body:
      "Alles hier wordt al voor dit programma geproduceerd, in de maten waaruit uw mensen kunnen kiezen.",
    step2Title: "Voeg uw ontvangerslijst toe",
    step2Body:
      "Plak die uit een spreadsheet of upload een CSV — namen, adressen, maten en een optioneel bericht.",
    step3Title: "Goedkeuring",
    step3Body:
      "De lijst gaat met het totaal naar uw goedkeurder voordat er iets wordt betaald.",
    step4Title: "Eén betaling, voor ieder een pakket",
    step4Body:
      "U betaalt één keer. Elke ontvanger krijgt zijn eigen pakket en zijn eigen tracking.",

    orderTitle: "Bulkorder cadeaus",
    campaignTitle: "Cadeaucampagne",
    orderIntro:
      "Voeg iedereen toe naar wie u verzendt, met het bezorgadres en de maat die ze dragen. Controleer de lijst zo vaak u wilt — er wordt niets aangemaakt totdat u de lijst verstuurt{approval}.",
    orderIntroApproval: " ter goedkeuring",
    paymentPendingTitle: "Betalingen staan voor deze winkel nog niet aan",
    paymentPendingBody:
      "U kunt een campagne wel opstellen en ter goedkeuring versturen. Betalen kan pas als {client} het betaalaccount volledig heeft gekoppeld.",
    yourApprover: "uw goedkeurder",

    buyerTitle: "Wie bestelt",
    campaignName: "Naam van de campagne",
    campaignNamePlaceholder: "Relatiegeschenken Q4",
    buyerName: "Uw naam",
    orderingAs:
      "U bestelt als {email}. Bewaar de campagnelink waarop u straks terechtkomt — er wordt geen e-mail verzonden, en op die pagina verschijnen de goedkeuring en de bon.",
    buyerEmail: "Uw werk-e-mail",
    buyerEmailHint:
      "Wordt op de campagne vastgelegd als besteller. Bewaar de campagnelink waarop u straks terechtkomt — er wordt geen e-mail verzonden, en op die pagina verschijnen de goedkeuring en de bon.",
    giftTitle: "Het cadeau",
    giftHint: "Geldt voor elke regel die geen eigen product noemt.",
    giftHintLimit: "Per ontvanger mag tot {amount} worden besteed.",
    giftHintNoLimit: "Dit programma heeft geen budgetlimiet.",
    listTitle: "Ontvangers",
    listHintLead: "Eén persoon per regel, tot {max}. Kolommen:",
    listHintTail:
      "Een kopregel wordt automatisch herkend, en {product} en {note} zijn optioneel.",
    uploadCsv: "CSV uploaden",
    pasteExample: "Voorbeeld plakken",
    fileLoaded: "{file} geladen",
    fileTooLarge: "{file} is {size} KB. Ontvangerslijsten blijven onder {limit} KB.",
    fileUnreadable: "Dat bestand kon niet worden gelezen. Sla het op als CSV en probeer het opnieuw.",
    listLabel: "Ontvangerslijst",
    checkList: "Lijst controleren",
    checkPending: "Lijst wordt gelezen…",
    sendForApproval: "Ter goedkeuring versturen",
    checkAndSend: "Controleren en versturen",
    sendPending: "Bezig…",
    previewRecipients: "{count} ontvangers",
    previewToFix: "{count} te herstellen",
    previewTotal: "{amount} in totaal",
    previewOverflow: "{count} regels boven de limiet zijn niet gelezen",
    columnLine: "Regel",
    columnRecipient: "Ontvanger",
    columnGift: "Cadeau",
    columnDelivered: "Bezorgd",
    columnDelivery: "Bezorging",
    columnValue: "Waarde",
    noName: "Geen naam",
    subtotal: "Cadeaus",
    shipping: "Verzending",
    tax: "Btw",
    taxRow: "Btw {rate}%",
    total: "Totaal",
    approvalNote:
      "Na het versturen ligt de campagne bij {approver}. Er wordt niets afgeschreven tot die is goedgekeurd en u betaalt.",
    noApprovalNote:
      "Dit programma heeft geen goedkeuring nodig, dus u gaat direct naar de betaling zodra de lijst klopt.",

    linkInvalidTitle: "Deze campagnelink is niet geldig",
    linkInvalidBody:
      "Campagnelinks zijn persoonlijk: één voor de besteller, één voor de goedkeurder. Vraag of de uwe opnieuw wordt verstuurd, of open de catalogus en begin een nieuwe order.",
    backToCatalogue: "Terug naar de catalogus",
    campaignSubmitted: "{count} ontvangers · ingediend door {buyer} op {when}",
    waitingTitle: "Wacht op goedkeuring",
    waitingBody:
      "{approver} heeft de lijst en het totaal. U kunt betalen zodra die is goedgekeurd — er is nog niets afgeschreven.",
    decisionTitle: "Uw beslissing is vastgelegd",
    decisionBody: "{decision} door {who} op {when}.",
    decisionCanPay: "{buyer} kan nu betalen — u is niets afgeschreven.",
    decisionApproved: "Goedgekeurd",
    decisionDeclined: "Afgewezen",
    declinedNoReason: "Er is geen reden opgegeven.",
    declinedBody:
      "Begin een nieuwe order vanuit de catalogus met de wijzigingen waar uw goedkeurder om vroeg.",
    orderedTitle: "Betaald en in productie",
    orderedBody:
      "Er zijn {count} orders aangemaakt, één per ontvanger, elk met eigen bezorging en tracking. Volg ze hieronder.",
    unpayableTitle: "Goedgekeurd, maar de winkel kan nog niet afrekenen",
    unpayableBody:
      "{client} heeft het betaalaccount nog niet volledig gekoppeld. Uw campagne is bewaard en kan worden betaald zodra dat is gebeurd.",
    recipientsTitle: "Ontvangers",
    track: "{code} volgen",
    historyTitle: "Geschiedenis",
    totalsTitle: "Campagnetotaal",
    spendLimitNote: "Budget {amount} per ontvanger.",
    noSpendLimitNote: "Dit programma heeft geen budgetlimiet.",
    decisionFormTitle: "Uw beslissing",
    paymentTitle: "Betaling",
    approvalIntro:
      "{buyer} heeft uw fiat nodig voordat deze campagne kan worden betaald. Goedkeuren kost niets — de besteller betaalt op zijn eigen scherm.",
    noteLabel: "Opmerking (verplicht bij afwijzen)",
    notePlaceholder: "Goedgekeurd ten laste van het marketingbudget Q4.",
    approve: "{total} goedkeuren",
    approvePending: "Beslissing wordt vastgelegd…",
    decline: "Afwijzen",
    declinePending: "Vastleggen…",
    paymentIntro:
      "Eén betaling voor de hele campagne, afgeschreven via het eigen Stripe-account van de winkel {account}. Elke ontvanger wordt daarna een eigen order met eigen tracking.",
    pay: "{total} betalen",
    payPending: "Betaling wordt verwerkt…",
    withdraw: "Deze campagne terugtrekken",
    withdrawConfirm: "Campagne terugtrekken",
    withdrawQuestion: "De lijst wordt teruggetrokken en niemand wordt afgeschreven.",
    withdrawPending: "Bezig…",
    cancel: "Annuleren",

    statusAwaitingApproval: "Wacht op goedkeuring",
    statusApproved: "Goedgekeurd, wacht op betaling",
    statusDeclined: "Afgewezen",
    statusOrdered: "Besteld",
    statusCancelled: "Geannuleerd",

    eyebrow: "Cadeauportaal",
    notFoundTitle: "We kunnen die pagina niet vinden",
    notFoundBody:
      "Het adres is misschien verkeerd getypt, of de campagne of het product waarnaar het verwees is gesloten sinds de link is verstuurd. De catalogus zelf is nog open.",
    notFoundBoundaryBody:
      "De link is misschien verlopen, of de cadeaucatalogus is gesloten door het bedrijf dat hem heeft opgezet. Als iemand u deze link heeft gestuurd, vraag dan om een actuele.",
    errorTitle: "Er is iets misgegaan aan onze kant",
    errorBody:
      "Deze pagina kon niet worden geladen. Niets van wat u hebt verstuurd is verloren — probeer het opnieuw en kom over een paar minuten terug als het blijft gebeuren.",
    errorRetry: "Opnieuw proberen",
    errorReference: "Referentie {digest}",
    goToParcelith: "Naar Parcelith",
  },

  fallback: {
    notFoundTitle: "Deze pagina kunnen we niet vinden",
    notFoundBody:
      "De link is mogelijk verouderd of het product wordt niet meer verkocht. Alles wat {store} vandaag verkoopt, is één klik verderop.",
    browseProducts: "Bekijk alle producten",
    errorTitle: "Er ging iets mis aan onze kant",
    errorBody:
      "Deze pagina kon niet worden geladen. Je winkelmand is ongewijzigd — probeer het opnieuw en kom over een paar minuten terug als het blijft misgaan.",
    errorRetry: "Opnieuw proberen",
    errorHome: "Terug naar {store}",
    errorReference: "Referentie {digest}",
  },
};
