import type { StorefrontCopy } from "./en";

/** Storefront copy, Dutch. */
export const nl: StorefrontCopy = {
  chrome: {
    shop: "Shop",
    currencyLabel: "Valuta",
    currencyApply: "Toepassen",
    basket: "Winkelmand",
    basketWithCount: "Winkelmand ({count})",
    operatedBy: "Beheerd door {client}. Op bestelling gemaakt en wereldwijd verzonden.",
    allProducts: "Alle producten",
    orderStatus: "Bestelstatus",
    delivery: "Verzending",
    help: "Hulp",
    supportEmailLabel: "E-mail",
    supportPhoneLabel: "Telefoon",
    supportPending: "Contactgegevens voor vragen zijn nog niet gepubliceerd.",
    carriersPending: "Vervoerders worden nog ingesteld",
    pricesShownIn: "Prijzen in {currency}{tax}.",
    taxIncluded: ", inclusief btw",
    taxAtCheckout: ", btw wordt bij het afrekenen toegevoegd",
    legal:
      "© {year} {client}. {client} is de verkoper van deze winkel. Storefront mogelijk gemaakt door Parcelith.",
  },

  meta: {
    homeTitle: "{store} — merch op bestelling",
    homeDescription:
      "Shop bij {store}, de officiële winkel van {client}. Op bestelling gedrukt en wereldwijd verzonden.",
    shopTitle: "Shop — {store}",
    shopDescription: "Alle producten die {store} aanbiedt.",
  },

  home: {
    closedTitle: "Deze winkel is gesloten",
    closedBody:
      "{client} heeft {store} gearchiveerd. Bestaande bestellingen worden nog geleverd en hun statuspagina’s blijven bereikbaar.",
    comingSoonTitle: "{store} is bijna klaar",
    comingSoonBody: "De indeling van de winkel is nog niet gepubliceerd.",
    comingSoonWithProducts: "De producten staan al online en zijn nu al te bekijken.",
    comingSoonNoProducts: "Kom binnenkort nog eens terug.",
    browseProducts: "Bekijk {count} producten",
  },

  shop: {
    title: "Alles in de shop",
    intro: "Op bestelling gemaakt en wereldwijd verzonden. Prijzen in {currency}{tax}.",
    taxIncluded: ", inclusief btw",
    taxAtCheckout: "; btw wordt bij het afrekenen toegevoegd",
    searchLabel: "Zoeken",
    searchPlaceholder: "T-shirt, hoodie, mok…",
    searchSubmit: "Zoeken",
    clear: "Wissen",
    filterByTag: "Filteren op label",
    emptyTitle: "Nog niets gepubliceerd",
    emptyBody: "Deze winkel heeft nog geen producten gepubliceerd. Kom snel terug.",
    noMatchTitle: "Geen producten gevonden voor deze zoekopdracht",
    noMatchBody: "Probeer een andere zoekterm of wis de filters.",
    clearFilters: "Filters wissen",
    personalise: "Personaliseerbaar",
    previewSoon: "Voorbeeld volgt binnenkort",
  },

  product: {
    breadcrumb: "Kruimelpad",
    breadcrumbShop: "Shop",
    about: "Over dit product",
    madeToOrder: "Op bestelling gemaakt",
    producedBy: "Gemaakt door {supplier} in {lead} en daarna verzonden met {carriers}.",
    defaultSupplier: "onze productiepartner",
    leadDays: "{from}–{to} dagen",
    leadUnknown: "een paar dagen",
    defaultCarrier: "onze vervoerder",
    carrierJoin: "of",
    printDetail: "Drukdetails",
    printDetailBody: "{area}, {width} × {height} mm, gedrukt op minimaal {dpi} DPI.",
    taxAndDelivery: "Btw en verzending",
    pricesShownIn: "Prijzen in {currency}{tax}.",
    taxIncluded: " inclusief btw",
    taxAtCheckout: "; btw wordt bij het afrekenen berekend",
    merchantOfRecord: "{client} is de verkoper van deze bestelling.",
  },

  purchase: {
    addToBasket: "In de winkelmand",
    adding: "Toevoegen…",
    viewBasket: "Winkelmand bekijken",
    colour: "Kleur",
    size: "Maat",
    option: "Optie",
    required: "Verplicht",
    quantity: "Aantal",
    lowStock: "bijna op",
    noPreview: "Geen voorbeeld beschikbaar",
    previewAlt: "Voorbeeld van {name}",
    viewAlt: "Aanzicht {view}",
    livePreview:
      "Live voorbeeld. Zodra je dit in de winkelmand legt, wordt een productiegetrouwe versie meegestuurd.",
    textPlaceholder: "Optioneel",
    textCounter: "{count}/{max} tekens. Wordt met het ontwerp meegedrukt.",
    artworkLabel: "Je eigen ontwerp",
    artworkHint:
      "Gedrukt op {width} × {height} mm, dus we hebben minimaal {dpi} DPI nodig. {formats} tot {max} MB.",
    artworkHintSimple: "PNG, JPG of WEBP.",
    uploading: "Je ontwerp wordt geüpload…",
    uploadFailed: "Dit bestand kon niet worden geüpload.",
    fileTooLarge: "Dit bestand is {size} MB. De limiet is {limit} MB.",
    artworkPlacementTitle: "Plaats je ontwerp",
    artworkPlacementHelp:
      "Sleep het ontwerp op de voorvertoning of gebruik de schuifregelaars hieronder. De voorvertoning en de drukresolutie volgen elke wijziging.",
    artworkGrabLabel:
      "Positie van {file}. Sleep om te verplaatsen of gebruik de pijltoetsen; + en − passen de grootte aan.",
    artworkSize: "Grootte",
    artworkRotation: "Rotatie",
    artworkResolution: "Drukresolutie",
    artworkRecentre: "Opnieuw centreren",
    artworkRemove: "Ontwerp verwijderen",
    artworkChecksPass: "Dit ontwerp kan op deze grootte worden gedrukt.",
    artworkChecksFail: "Los dit op voordat je het in je mandje legt",
    artworkWhatToDo: "Wat te doen: {fix}",
    artworkBlocked:
      "Los het ontwerp hierboven op, of verwijder het, om dit artikel in je mandje te leggen.",
  },

  basket: {
    title: "Je winkelmand",
    emptyTitle: "Nog niets in de winkelmand",
    emptyBody:
      "Voeg een product met eventuele personalisatie toe: het verschijnt hier met het voorbeeld dat bij je bestelling gaat.",
    browseShop: "Naar de shop",
    previewAlt: "Voorbeeld van {name}",
    personalisation: "Personalisatie:",
    artwork: "Ontwerp: {file}",
    quantity: "Aantal",
    update: "Bijwerken",
    remove: "Verwijderen",
    summary: "Overzicht",
    subtotal: "Subtotaal",
    shipping: "Verzending",
    taxRow: "Btw {rate}%",
    taxIncludedSuffix: "inbegrepen",
    total: "Totaal",
    checkout: "Afrekenen",
    keepShopping: "Verder winkelen",
  },

  checkout: {
    title: "Afrekenen",
    merchantNote:
      "{client} is de verkoper. De betaling komt binnen op hun eigen Stripe-account.",
    unavailableTitle: "Deze winkel kan nog geen betalingen aannemen",
    unavailableBody:
      "De winkel heeft het koppelen van haar Stripe-account nog niet afgerond. Je winkelmand blijft bewaard — probeer het opnieuw zodra de winkel live is.",
    backToBasket: "Terug naar de winkelmand",
    summaryTitle: "Besteloverzicht",
    shipping: "Verzending",
    taxRow: "Btw {rate}%",
    taxIncludedSuffix: "inbegrepen",
    total: "Totaal",
    deliveryDetails: "Bezorggegevens",
    fullName: "Volledige naam",
    email: "E-mail",
    emailHint: "Met dit adres en je bestelcode open je later de pagina van je bestelling.",
    street: "Straat en huisnummer",
    city: "Plaats",
    postalCode: "Postcode",
    country: "Land",
    countryHint: "Begin te typen om je land te vinden. De productie wordt op bestemming gekozen.",
    countrySearchPlaceholder: "Landen zoeken",
    countryNoMatch: "Geen land komt overeen met “{query}”.",
    payIn: "Betalen in",
    manualRoutingTitle: "Bezorging naar {country} vraagt om handmatige toewijzing",
    manualRoutingLine: "{supplier} maakt {products} en levert niet aan {country} ({region}).",
    productJoin: "en",
    manualRoutingBody:
      "Je kunt gewoon betalen, maar de bestelling wordt vastgehouden totdat iemand die bij een andere productiepartner plaatst — dat duurt langer dan de gebruikelijke levertijd. Een bezorgland dat je leverancier wel dekt, voorkomt dit wachten.",
    paymentTitle: "Betaling",
    paymentNote:
      "Afgeschreven via het eigen Stripe-account van deze winkel {account}. Kaartgegevens worden nooit door de winkel bewaard.",
    cardNumber: "Kaartnummer",
    expiry: "Vervaldatum (MM/JJ)",
    securityCode: "Beveiligingscode",
    testMode: "Stripe-testmodus",
    submit: "Betalen en bestellen",
    pending: "Betaling wordt verwerkt…",
    cardSucceeds: "Visa — geslaagd",
    cardDeclined: "Visa — geweigerd door de bank",
    cardInsufficient: "Visa — onvoldoende saldo",
  },

  order: {
    title: "Bestelstatus",
    lookupIntro:
      "Vul je bestelcode in samen met het e-mailadres dat je bij het afrekenen hebt opgegeven. De link die je bij het bestellen hebt bewaard, opent de bestelling direct.",
    gateBody:
      "Om bezorg- en personalisatiegegevens te beschermen, bevestig eerst het e-mailadres bij bestelling {code} voordat we die tonen.",
    confirmedTitle: "Bedankt — je bestelling is bevestigd",
    confirmedBody:
      "Bewaar deze pagina of sla haar op als bladwijzer — hier zie je hoe je bestelling vordert. De winkel stuurt nog geen bevestigingsmails.",
    confirmedFindAgain:
      "Je vindt haar ook terug via “Bestelstatus” met bestelcode {code} en het e-mailadres {email}.",
    heading: "Bestelling {code}",
    placed: "Geplaatst op {when}",
    trackWith: "Volgen met {carrier} ↗",
    whatYouOrdered: "Wat je hebt besteld",
    variantQuantity: "{variant} · aantal {count}",
    personalisation: "Personalisatie:",
    previewAlt: "Voorbeeld van {name}",
    subtotal: "Subtotaal",
    shipping: "Verzending",
    taxRow: "Btw {rate}%",
    paid: "Betaald",
    refunded: "Terugbetaald",
    deliveringTo: "Bezorgen aan",
    payment: "Betaling",
    cardEnding: "Kaart eindigend op {last4}",
    card: "Kaart",
    paidWord: "betaald",
    refundedWord: "terugbetaald",
    merchantOfRecord: "{client} is de verkoper.",
    progress: "Voortgang",
    supportTitle: "Vragen over deze bestelling",
    contactSubject: "Bestelling {code}",
    continueShopping: "Verder winkelen",
    contactStore: "Contact met de winkel",
    orderCode: "Bestelcode",
    orderCodeHint: "Begint met ORD- en staat bovenaan de pagina van je bestelling.",
    emailOnOrder: "E-mailadres van de bestelling",
    emailHint: "Het adres dat je bij het afrekenen hebt opgegeven.",
    lookupSubmit: "Toon mijn bestelling",
    lookupPending: "Bezig met controleren…",
  },

  status: {
    awaitingPayment: "Wacht op betaling",
    awaitingPaymentNote: "We hebben nog geen betaling voor deze bestelling ontvangen.",
    paid: "Betaling ontvangen",
    paidNote: "Je bestelling staat in de wachtrij voor productie.",
    inProduction: "In productie",
    inProductionNote: "Je artikel wordt gedrukt en afgewerkt.",
    shipped: "Verzonden",
    shippedNote: "Je pakket is onderweg. Volg het via de link hieronder.",
    delivered: "Bezorgd",
    deliveredNote: "Je pakket is bezorgd. Veel plezier ermee.",
    cancelled: "Geannuleerd",
    cancelledNote: "Deze bestelling is geannuleerd. Een eventuele betaling is terugbetaald.",
    exception: "Vraagt aandacht",
    exceptionNote:
      "Deze bestelling staat even stil. Het team van de winkel is ermee bezig en neemt contact op.",
  },

  actions: {
    storeClosed: "Deze winkel neemt op dit moment geen bestellingen aan.",
    productGone: "Dat product is niet meer beschikbaar.",
    chooseVariant: "Kies een maat en kleur.",
    outOfStock: "{variant} is uitverkocht. Kies een andere optie.",
    noTextPersonalisation: "Dit product kan niet met tekst worden gepersonaliseerd.",
    textTooLong: "Houd de personalisatie op {max} tekens of minder.",
    noArtworkUpload: "Dit product accepteert geen geüpload ontwerp.",
    productUnavailable: "Dit product is tijdelijk niet beschikbaar.",
    fileTooLarge: "Dit bestand is {size} MB. De limiet is {limit} MB.",
    basketUnavailable: "Je winkelmand kon niet worden geopend. Sta cookies toe en probeer het opnieuw.",
    addedToBasket: "{product} is aan je winkelmand toegevoegd.",
    basketEmpty: "Je winkelmand is leeg.",
    enterName: "Vul de naam voor de bezorging in.",
    enterEmail: "Vul een e-mailadres in — daarmee open je later je bestelling.",
    enterStreet: "Vul straat en huisnummer in.",
    enterCity: "Vul de plaats in.",
    enterPostalCode: "Vul de postcode in.",
    chooseCountry: "Kies je bezorgland uit de lijst.",
    currencyNotSold: "{currency} is geen verkoopvaluta van deze winkel.",
    enterOrderCode: "Vul je bestelcode in.",
    enterOrderEmail: "Vul het e-mailadres van de bestelling in.",
    lookupFailed:
      "We konden die bestelcode en dat e-mailadres niet aan elkaar koppelen. Controleer beide en probeer het opnieuw.",
  },

  artwork: {
    lowDpi: "Deze afbeelding wordt gedrukt op {dpi} DPI, onder de {required} DPI die dit product nodig heeft.",
    lowDpiFix:
      "Upload er een van minstens {pixels} pixels breed, of maak het ontwerp kleiner — dit bestand blijft scherp tot {width} mm breed.",
    badFormat: "{format}-bestanden worden voor dit product niet geaccepteerd.",
    badFormatFix: "Sla het ontwerp op als {formats} en kies het opnieuw.",
    unreadableFormat: "{format}-bestanden kunnen hier niet worden gemeten of getoond.",
    unreadableFormatFix: "Sla het ontwerp op als {formats} en kies het opnieuw.",
    fileTooLarge: "Dit bestand is {size} MB. De limiet is {limit} MB.",
    fileTooLargeFix: "Sla het kleiner of met lagere kwaliteit op en kies het opnieuw.",
    tooManyPixels: "Deze afbeelding is te groot. De limiet is {megapixels} megapixel.",
    tooManyPixelsFix: "Verklein hem in je fotobewerker en kies hem opnieuw.",
    noTransparency:
      "Dit product wordt rechtstreeks op de stof gedrukt, dus het ontwerp heeft een transparante achtergrond nodig.",
    noTransparencyFix: "Verwijder de achtergrond en sla het op als PNG met transparantie.",
    outsideArea: "Een deel van het ontwerp valt buiten het drukvlak en zou worden afgesneden.",
    outsideAreaFix:
      "Sleep het terug binnen de stippellijn, of maak het kleiner zodat het in {width} × {height} mm past.",
    dpiTight: "Deze afbeelding wordt gedrukt op {dpi} DPI, net boven het minimum van {required} DPI.",
    dpiTightFix:
      "Dunne lijnen kunnen zacht ogen. Een groter bestand, of een iets kleiner ontwerp, drukt scherper.",
    verySmall: "Het ontwerp beslaat minder dan 15% van de drukbreedte.",
    verySmallFix: "Schuif de grootte omhoog als dit de hoofdafbeelding moet zijn.",
    generic: "Dit ontwerp kan niet op dit product worden gedrukt.",
    genericFix: "Probeer een ander bestand.",
  },

  payment: {
    accountNotReady:
      "Deze winkel heeft het koppelen van haar Stripe-account nog niet afgerond, dus betalen kan nog niet.",
    currencyUnsupported: "{currency} is geen verkoopvaluta van deze winkel.",
    invalidNumber: "Dit kaartnummer is niet geldig. Controleer de cijfers en probeer het opnieuw.",
    invalidExpiry: "De vervaldatum ligt in het verleden of heeft een verkeerde notatie. Gebruik MM/JJ.",
    invalidCvc: "De beveiligingscode moet 3 of 4 cijfers hebben.",
    declined: "Je kaart is geweigerd door de uitgevende bank.",
    insufficientFunds: "Je kaart heeft onvoldoende saldo.",
    expiredCard: "Je kaart is verlopen.",
  },

  sections: {
    viewAll: "Alles bekijken",
    noProducts:
      "In deze winkel zijn nog geen producten gepubliceerd. Gepubliceerde producten verschijnen hier automatisch.",
    previewSoon: "Voorbeeld volgt binnenkort",
    imagePlaceholder: "Voeg in de sectie-instellingen een afbeeldings-URL toe",
    newsletterEmail: "E-mailadres",
    notifyMe: "Houd me op de hoogte",
    welcome: "Welkom",
  },

  fallback: {
    notFoundTitle: "Deze pagina kunnen we niet vinden",
    notFoundBody:
      "De link is mogelijk verouderd of het product wordt niet meer verkocht. Alles wat {store} vandaag verkoopt, is één klik verderop.",
    browseProducts: "Bekijk alle producten",
    errorTitle: "Er ging iets mis aan onze kant",
    errorBody:
      "Deze pagina kon niet worden geladen. Je winkelmand is ongewijzigd — probeer het opnieuw en kom over een paar minuten terug als het blijft misgaan.",
    errorRetry: "Opnieuw proberen",
    errorHome: "Terug naar {store}",
    errorReference: "Referentie {digest}",
  },
};
