import type { StorefrontCopy } from "./en";

/** Storefront copy, Portuguese. */
export const pt: StorefrontCopy = {
  chrome: {
    shop: "Loja",
    currencyLabel: "Moeda",
    currencyApply: "Aplicar",
    basket: "Cesto",
    basketWithCount: "Cesto ({count})",
    operatedBy: "Gerida por {client}. Produzido por encomenda e enviado para todo o mundo.",
    allProducts: "Todos os produtos",
    orderStatus: "Estado da encomenda",
    delivery: "Envio",
    carriersPending: "Configuração das transportadoras em curso",
    pricesShownIn: "Preços em {currency}{tax}.",
    taxIncluded: ", impostos incluídos",
    taxAtCheckout: ", impostos adicionados no pagamento",
    legal:
      "© {year} {client}. {client} é o vendedor desta loja. Loja criada com o Parcelith.",
  },

  meta: {
    homeTitle: "{store} — artigos produzidos por encomenda",
    homeDescription:
      "Compre na {store}, a loja oficial de {client}. Impresso por encomenda e enviado para todo o mundo.",
    shopTitle: "Loja — {store}",
    shopDescription: "Todos os produtos disponíveis na {store}.",
  },

  home: {
    closedTitle: "Esta loja está encerrada",
    closedBody:
      "{client} arquivou {store}. As encomendas existentes continuam a ser satisfeitas e as respetivas páginas de estado permanecem disponíveis.",
    comingSoonTitle: "{store} está quase pronta",
    comingSoonBody: "O layout da loja ainda não foi publicado.",
    comingSoonWithProducts: "Os produtos já estão online e podem ser vistos entretanto.",
    comingSoonNoProducts: "Volte dentro de pouco tempo.",
    browseProducts: "Ver {count} produtos",
  },

  shop: {
    title: "Tudo na loja",
    intro: "Produzido por encomenda e enviado para todo o mundo. Preços em {currency}{tax}.",
    taxIncluded: ", impostos incluídos",
    taxAtCheckout: "; os impostos são adicionados no pagamento",
    searchLabel: "Pesquisar",
    searchPlaceholder: "T-shirt, sweat, caneca…",
    searchSubmit: "Pesquisar",
    clear: "Limpar",
    filterByTag: "Filtrar por etiqueta",
    emptyTitle: "Ainda não há nada publicado",
    emptyBody: "Esta loja ainda não publicou produtos. Volte em breve.",
    noMatchTitle: "Nenhum produto corresponde a essa pesquisa",
    noMatchBody: "Experimente outro termo de pesquisa ou limpe os filtros.",
    clearFilters: "Limpar filtros",
    personalise: "Personalizável",
    previewSoon: "Pré-visualização em breve",
  },

  product: {
    breadcrumb: "Trilho de navegação",
    breadcrumbShop: "Loja",
    about: "Sobre este produto",
    madeToOrder: "Produzido por encomenda",
    producedBy: "Produzido por {supplier} em {lead} e depois enviado com {carriers}.",
    defaultSupplier: "o nosso parceiro de produção",
    leadDays: "{from}–{to} dias",
    leadUnknown: "poucos dias",
    defaultCarrier: "a nossa transportadora",
    carrierJoin: "ou",
    printDetail: "Detalhe de impressão",
    printDetailBody: "{area}, {width} × {height} mm, impresso a um mínimo de {dpi} DPI.",
    taxAndDelivery: "Impostos e envio",
    pricesShownIn: "Preços em {currency}{tax}.",
    taxIncluded: " com impostos incluídos",
    taxAtCheckout: "; os impostos são calculados no pagamento",
    merchantOfRecord: "{client} é o vendedor desta encomenda.",
  },

  purchase: {
    addToBasket: "Adicionar ao cesto",
    adding: "A adicionar…",
    viewBasket: "Ver o cesto",
    colour: "Cor",
    size: "Tamanho",
    option: "Opção",
    required: "Obrigatório",
    quantity: "Quantidade",
    lowStock: "poucas",
    noPreview: "Sem pré-visualização disponível",
    previewAlt: "Pré-visualização de {name}",
    viewAlt: "Vista {view}",
    livePreview:
      "Pré-visualização ao vivo. Ao adicionar ao cesto é anexada uma versão fiel à produção.",
    textPlaceholder: "Opcional",
    textCounter: "{count}/{max} caracteres. Impressos junto com o design.",
    artworkLabel: "O seu próprio design",
    artworkHint:
      "Impresso a {width} × {height} mm, por isso são necessários pelo menos {dpi} DPI. {formats} até {max} MB.",
    artworkHintSimple: "PNG, JPG ou WEBP.",
    uploading: "A carregar o seu design…",
    uploadFailed: "Não foi possível carregar esse ficheiro.",
    fileTooLarge: "Esse ficheiro tem {size} MB. O limite é de {limit} MB.",
  },

  basket: {
    title: "O seu cesto",
    emptyTitle: "Ainda não há nada no cesto",
    emptyBody:
      "Adicione um produto com a respetiva personalização: aparecerá aqui com a pré-visualização que acompanha a sua encomenda.",
    browseShop: "Ir para a loja",
    previewAlt: "Pré-visualização de {name}",
    personalisation: "Personalização:",
    artwork: "Design: {file}",
    quantity: "Quantidade",
    update: "Atualizar",
    remove: "Remover",
    summary: "Resumo",
    subtotal: "Subtotal",
    shipping: "Envio",
    taxRow: "Impostos {rate} %",
    taxIncludedSuffix: "incluídos",
    total: "Total",
    checkout: "Finalizar compra",
    keepShopping: "Continuar a comprar",
  },

  checkout: {
    title: "Pagamento",
    merchantNote:
      "{client} é o vendedor. O pagamento é liquidado na sua própria conta Stripe.",
    unavailableTitle: "Esta loja ainda não pode aceitar pagamentos",
    unavailableBody:
      "A loja ainda não concluiu a ligação da sua conta Stripe. O seu cesto fica guardado — tente novamente assim que a loja estiver ativa.",
    backToBasket: "Voltar ao cesto",
    summaryTitle: "Resumo da encomenda",
    shipping: "Envio",
    taxRow: "Impostos {rate} %",
    taxIncludedSuffix: "incluídos",
    total: "Total",
    deliveryDetails: "Dados de entrega",
    fullName: "Nome completo",
    email: "E-mail",
    emailHint: "A confirmação da encomenda e as atualizações de entrega são enviadas para aqui.",
    street: "Morada",
    city: "Localidade",
    postalCode: "Código postal",
    country: "País",
    countryHint: "Comece a escrever para encontrar o seu país. A produção é atribuída pelo destino.",
    countrySearchPlaceholder: "Procurar países",
    countryNoMatch: "Nenhum país corresponde a «{query}».",
    payIn: "Pagar em",
    manualRoutingTitle: "A entrega em {country} exige atribuição manual",
    manualRoutingLine: "{supplier} produz {products} e não entrega em {country} ({region}).",
    productJoin: "e",
    manualRoutingBody:
      "Pode pagar na mesma, mas a encomenda ficará retida até que alguém a coloque junto de outro parceiro de produção, pelo que demorará mais do que o prazo habitual. Escolher um país de entrega coberto pelo seu fornecedor evita a espera.",
    paymentTitle: "Pagamento",
    paymentNote:
      "Cobrado através da conta Stripe desta loja {account}. Os dados do cartão nunca são guardados pela loja.",
    cardNumber: "Número do cartão",
    expiry: "Validade (MM/AA)",
    securityCode: "Código de segurança",
    testMode: "Modo de teste do Stripe",
    submit: "Pagar e encomendar",
    pending: "A processar o pagamento…",
    cardSucceeds: "Visa — aceite",
    cardDeclined: "Visa — recusado pelo banco",
    cardInsufficient: "Visa — saldo insuficiente",
  },

  order: {
    title: "Estado da encomenda",
    lookupIntro:
      "Introduza o código da encomenda que consta da confirmação e o e-mail associado. A ligação da confirmação abre a encomenda diretamente.",
    gateBody:
      "Para proteger os dados de entrega e personalização, confirme o e-mail da encomenda {code} antes de a mostrarmos.",
    confirmedTitle: "Obrigado — a sua encomenda está confirmada",
    confirmedBody:
      "Enviámos uma confirmação para {email}. Guarde esta página nos favoritos para acompanhar a produção e a entrega.",
    heading: "Encomenda {code}",
    placed: "Efetuada a {when}",
    trackWith: "Seguir com {carrier} ↗",
    whatYouOrdered: "A sua encomenda",
    variantQuantity: "{variant} · quantidade {count}",
    personalisation: "Personalização:",
    previewAlt: "Pré-visualização de {name}",
    subtotal: "Subtotal",
    shipping: "Envio",
    taxRow: "Impostos {rate} %",
    paid: "Pago",
    refunded: "Reembolsado",
    deliveringTo: "Entrega a",
    payment: "Pagamento",
    cardEnding: "Cartão terminado em {last4}",
    card: "Cartão",
    paidWord: "pago",
    refundedWord: "reembolsado",
    merchantOfRecord: "{client} é o vendedor.",
    progress: "Progresso",
    continueShopping: "Continuar a comprar",
    contactStore: "Contactar a loja",
    orderCode: "Código da encomenda",
    orderCodeHint: "Consta da confirmação da encomenda e começa por ORD-.",
    emailOnOrder: "E-mail da encomenda",
    emailHint: "O endereço para onde a confirmação foi enviada.",
    lookupSubmit: "Mostrar a minha encomenda",
    lookupPending: "A verificar…",
  },

  status: {
    awaitingPayment: "A aguardar pagamento",
    awaitingPaymentNote: "Ainda não recebemos o pagamento desta encomenda.",
    paid: "Pagamento recebido",
    paidNote: "A sua encomenda está em fila para produção.",
    inProduction: "Em produção",
    inProductionNote: "O seu artigo está a ser impresso e acabado.",
    shipped: "Enviada",
    shippedNote: "A sua encomenda está a caminho. Siga-a através da ligação abaixo.",
    delivered: "Entregue",
    deliveredNote: "A sua encomenda foi entregue. Aproveite.",
    cancelled: "Cancelada",
    cancelledNote: "Esta encomenda foi cancelada. Qualquer pagamento foi reembolsado.",
    exception: "Precisa de atenção",
    exceptionNote:
      "Esta encomenda está retida. A equipa da loja está a tratar do assunto e entrará em contacto.",
  },

  actions: {
    storeClosed: "Esta loja não está a aceitar encomendas de momento.",
    productGone: "Esse produto já não está disponível.",
    chooseVariant: "Escolha um tamanho e uma cor.",
    outOfStock: "{variant} está esgotado. Escolha outra opção.",
    noTextPersonalisation: "Este produto não pode ser personalizado com texto.",
    textTooLong: "Limite a personalização a {max} caracteres.",
    noArtworkUpload: "Este produto não aceita designs carregados.",
    productUnavailable: "Este produto está temporariamente indisponível.",
    fileTooLarge: "Esse ficheiro tem {size} MB. O limite é de {limit} MB.",
    basketUnavailable: "Não foi possível abrir o seu cesto. Ative os cookies e tente novamente.",
    addedToBasket: "{product} foi adicionado ao seu cesto.",
    basketEmpty: "O seu cesto está vazio.",
    enterName: "Indique o nome para a entrega.",
    enterEmail: "Indique um e-mail para lhe podermos enviar atualizações da encomenda.",
    enterStreet: "Indique a morada.",
    enterCity: "Indique a localidade.",
    enterPostalCode: "Indique o código postal.",
    chooseCountry: "Escolha o seu país de entrega na lista.",
    currencyNotSold: "{currency} não é uma das moedas de venda desta loja.",
    enterOrderCode: "Introduza o código da encomenda.",
    enterOrderEmail: "Introduza o e-mail da encomenda.",
    lookupFailed:
      "Não conseguimos associar esse código de encomenda a esse e-mail. Verifique ambos e tente novamente.",
  },

  artwork: {
    lowDpi:
      "Esse design é impresso com resolução demasiado baixa. Carregue um ficheiro com pelo menos {dpi} DPI.",
    badFormat: "Os ficheiros {format} não são aceites neste produto. Carregue {formats}.",
    fileTooLarge: "Esse ficheiro tem {size} MB. O limite é de {limit} MB.",
    tooManyPixels:
      "Essa imagem é demasiado grande. Reduza-a para menos de {megapixels} megapíxeis e tente novamente.",
    noTransparency:
      "Este produto precisa de um design com fundo transparente. Exporte-o como PNG com transparência.",
    generic: "Esse design não pode ser impresso neste produto. Experimente outro ficheiro.",
  },

  payment: {
    accountNotReady:
      "Esta loja ainda não concluiu a ligação da sua conta Stripe, pelo que os pagamentos não estão disponíveis.",
    currencyUnsupported: "{currency} não é uma das moedas de venda desta loja.",
    invalidNumber: "Esse número de cartão não é válido. Verifique os dígitos e tente novamente.",
    invalidExpiry: "A data de validade já passou ou está mal formatada. Use MM/AA.",
    invalidCvc: "O código de segurança tem de ter 3 ou 4 dígitos.",
    declined: "O seu cartão foi recusado pelo banco emissor.",
    insufficientFunds: "O seu cartão não tem saldo suficiente.",
    expiredCard: "O seu cartão expirou.",
  },

  sections: {
    viewAll: "Ver tudo",
    noProducts:
      "Ainda não há produtos publicados nesta loja. Os produtos publicados aparecem aqui automaticamente.",
    previewSoon: "Pré-visualização em breve",
    imagePlaceholder: "Adicione o URL de uma imagem nas definições da secção",
    newsletterEmail: "Endereço de e-mail",
    notifyMe: "Avisem-me",
    welcome: "Bem-vindo",
  },

  fallback: {
    notFoundTitle: "Não encontrámos esta página",
    notFoundBody:
      "A ligação pode estar desatualizada ou o produto já não está à venda. Tudo o que a {store} vende hoje continua à distância de um clique.",
    browseProducts: "Ver todos os produtos",
    errorTitle: "Algo correu mal do nosso lado",
    errorBody:
      "Não foi possível carregar esta página. O seu cesto está intacto — tente novamente e, se continuar, volte dentro de alguns minutos.",
    errorRetry: "Tentar novamente",
    errorHome: "Voltar à {store}",
    errorReference: "Referência {digest}",
  },
};
