import type { StorefrontCopy } from "./en";

/** Storefront copy, Swedish. */
export const sv: StorefrontCopy = {
  chrome: {
    shop: "Butik",
    currencyLabel: "Valuta",
    currencyApply: "Använd",
    basket: "Varukorg",
    basketWithCount: "Varukorg ({count})",
    operatedBy: "Drivs av {client}. Tillverkas på beställning och skickas över hela världen.",
    allProducts: "Alla produkter",
    orderStatus: "Orderstatus",
    delivery: "Frakt",
    help: "Hjälp",
    supportEmailLabel: "E-post",
    supportPhoneLabel: "Telefon",
    supportPending: "Kontaktuppgifter till kundtjänst är ännu inte publicerade.",
    carriersPending: "Fraktbolag håller på att ställas in",
    pricesShownIn: "Priser i {currency}{tax}.",
    taxIncluded: ", inklusive moms",
    taxAtCheckout: ", moms tillkommer i kassan",
    legal:
      "© {year} {client}. {client} är säljare i den här butiken. Butiken drivs med Parcelith.",
  },

  meta: {
    homeTitle: "{store} — merch tillverkad på beställning",
    homeDescription:
      "Handla hos {store}, den officiella butiken för {client}. Tryckt på beställning och skickad över hela världen.",
    shopTitle: "Butik — {store}",
    shopDescription: "Alla produkter som finns hos {store}.",
  },

  home: {
    closedTitle: "Den här butiken är stängd",
    closedBody:
      "{client} har arkiverat {store}. Befintliga ordrar levereras fortfarande och deras statussidor finns kvar.",
    comingSoonTitle: "{store} är nästan klar",
    comingSoonBody: "Butikens layout har inte publicerats än.",
    comingSoonWithProducts: "Produkterna är redan publicerade och går att titta på under tiden.",
    comingSoonNoProducts: "Titta in igen snart.",
    browseProducts: "Se {count} produkter",
  },

  shop: {
    title: "Allt i butiken",
    intro: "Tillverkas på beställning och skickas över hela världen. Priser i {currency}{tax}.",
    taxIncluded: ", inklusive moms",
    taxAtCheckout: "; moms tillkommer i kassan",
    searchLabel: "Sök",
    searchPlaceholder: "T-shirt, hoodie, mugg…",
    searchSubmit: "Sök",
    clear: "Rensa",
    filterByTag: "Filtrera på tagg",
    emptyTitle: "Inget publicerat än",
    emptyBody: "Den här butiken har inte publicerat några produkter än. Titta in igen snart.",
    noMatchTitle: "Inga produkter matchar sökningen",
    noMatchBody: "Prova ett annat sökord eller rensa filtren.",
    clearFilters: "Rensa filter",
    personalise: "Kan personaliseras",
    previewSoon: "Förhandsvisning kommer snart",
  },

  product: {
    breadcrumb: "Brödsmulor",
    breadcrumbShop: "Butik",
    about: "Om produkten",
    madeToOrder: "Tillverkas på beställning",
    producedBy: "Tillverkas av {supplier} på {lead} och skickas sedan med {carriers}.",
    defaultSupplier: "vår produktionspartner",
    leadDays: "{from}–{to} dagar",
    leadUnknown: "några dagar",
    defaultCarrier: "vårt fraktbolag",
    carrierJoin: "eller",
    printDetail: "Tryckdetaljer",
    printDetailBody: "{area}, {width} × {height} mm, tryckt i minst {dpi} DPI.",
    taxAndDelivery: "Moms och frakt",
    pricesShownIn: "Priser i {currency}{tax}.",
    taxIncluded: " inklusive moms",
    taxAtCheckout: "; moms räknas ut i kassan",
    merchantOfRecord: "{client} är säljare för den här ordern.",
  },

  purchase: {
    addToBasket: "Lägg i varukorgen",
    adding: "Lägger till…",
    viewBasket: "Visa varukorgen",
    colour: "Färg",
    size: "Storlek",
    option: "Variant",
    required: "Obligatoriskt",
    quantity: "Antal",
    lowStock: "få kvar",
    noPreview: "Ingen förhandsvisning tillgänglig",
    previewAlt: "Förhandsvisning av {name}",
    viewAlt: "Vy {view}",
    livePreview:
      "Live-förhandsvisning. En produktionstrogen version bifogas när du lägger varan i varukorgen.",
    textPlaceholder: "Valfritt",
    textCounter: "{count}/{max} tecken. Trycks tillsammans med designen.",
    artworkLabel: "Din egen design",
    artworkHint:
      "Trycks i {width} × {height} mm, så vi behöver minst {dpi} DPI. {formats} upp till {max} MB.",
    artworkHintSimple: "PNG, JPG eller WEBP.",
    uploading: "Laddar upp din design…",
    uploadFailed: "Filen kunde inte laddas upp.",
    fileTooLarge: "Filen är {size} MB. Gränsen är {limit} MB.",
  },

  basket: {
    title: "Din varukorg",
    emptyTitle: "Inget i varukorgen än",
    emptyBody:
      "Lägg till en produkt med eventuell personalisering, så visas den här med förhandsvisningen som följer med din order.",
    browseShop: "Till butiken",
    previewAlt: "Förhandsvisning av {name}",
    personalisation: "Personalisering:",
    artwork: "Design: {file}",
    quantity: "Antal",
    update: "Uppdatera",
    remove: "Ta bort",
    summary: "Sammanfattning",
    subtotal: "Delsumma",
    shipping: "Frakt",
    taxRow: "Moms {rate} %",
    taxIncludedSuffix: "ingår",
    total: "Totalt",
    checkout: "Till kassan",
    keepShopping: "Fortsätt handla",
  },

  checkout: {
    title: "Kassa",
    merchantNote: "{client} är säljare. Betalningen går in på deras eget Stripe-konto.",
    unavailableTitle: "Den här butiken kan inte ta emot betalningar än",
    unavailableBody:
      "Butiken har inte kopplat klart sitt Stripe-konto. Din varukorg sparas — försök igen när butiken är i drift.",
    backToBasket: "Tillbaka till varukorgen",
    summaryTitle: "Ordersammanfattning",
    shipping: "Frakt",
    taxRow: "Moms {rate} %",
    taxIncludedSuffix: "ingår",
    total: "Totalt",
    deliveryDetails: "Leveransuppgifter",
    fullName: "Fullständigt namn",
    email: "E-post",
    emailHint: "Med den här adressen och din orderkod öppnar du ordersidan igen senare.",
    street: "Gatuadress",
    city: "Postort",
    postalCode: "Postnummer",
    country: "Land",
    countryHint: "Börja skriva för att hitta ditt land. Produktionen styrs av destinationen.",
    countrySearchPlaceholder: "Sök länder",
    countryNoMatch: "Inget land matchar ”{query}”.",
    payIn: "Betala i",
    manualRoutingTitle: "Leverans till {country} kräver manuell hantering",
    manualRoutingLine: "{supplier} tillverkar {products} och levererar inte till {country} ({region}).",
    productJoin: "och",
    manualRoutingBody:
      "Du kan betala ändå, men ordern hålls kvar tills någon lägger den hos en annan produktionspartner, så den tar längre tid än den vanliga ledtiden. Väljer du ett leveransland som din leverantör täcker slipper du väntan.",
    paymentTitle: "Betalning",
    paymentNote:
      "Dras via butikens eget Stripe-konto {account}. Kortuppgifter sparas aldrig av butiken.",
    cardNumber: "Kortnummer",
    expiry: "Giltigt t.o.m. (MM/ÅÅ)",
    securityCode: "Säkerhetskod",
    testMode: "Stripe testläge",
    submit: "Betala och lägg order",
    pending: "Genomför betalning…",
    cardSucceeds: "Visa — godkänns",
    cardDeclined: "Visa — nekas av banken",
    cardInsufficient: "Visa — otillräckliga medel",
  },

  order: {
    title: "Orderstatus",
    lookupIntro:
      "Ange din orderkod och e-postadressen du angav i kassan. Länken du sparade när du lade ordern öppnar den direkt.",
    gateBody:
      "För att skydda leverans- och personaliseringsuppgifter behöver du bekräfta e-postadressen på order {code} innan vi visar den.",
    confirmedTitle: "Tack — din order är bekräftad",
    confirmedBody:
      "Spara den här sidan eller lägg den som bokmärke — det är här din order följs. Butiken skickar ännu inga bekräftelsemejl.",
    confirmedFindAgain:
      "Du hittar den också via ”Orderstatus” med orderkoden {code} och e-postadressen {email}.",
    heading: "Order {code}",
    placed: "Lagd {when}",
    trackWith: "Spåra med {carrier} ↗",
    whatYouOrdered: "Det du beställde",
    variantQuantity: "{variant} · antal {count}",
    personalisation: "Personalisering:",
    previewAlt: "Förhandsvisning av {name}",
    subtotal: "Delsumma",
    shipping: "Frakt",
    taxRow: "Moms {rate} %",
    paid: "Betalt",
    refunded: "Återbetalt",
    deliveringTo: "Levereras till",
    payment: "Betalning",
    cardEnding: "Kort som slutar på {last4}",
    card: "Kort",
    paidWord: "betald",
    refundedWord: "återbetald",
    merchantOfRecord: "{client} är säljare.",
    progress: "Förlopp",
    supportTitle: "Frågor om den här ordern",
    contactSubject: "Order {code}",
    continueShopping: "Fortsätt handla",
    contactStore: "Kontakta butiken",
    orderCode: "Orderkod",
    orderCodeHint: "Börjar med ORD- och står högst upp på din ordersida.",
    emailOnOrder: "E-postadress på ordern",
    emailHint: "Adressen du angav i kassan.",
    lookupSubmit: "Visa min order",
    lookupPending: "Kontrollerar…",
  },

  status: {
    awaitingPayment: "Väntar på betalning",
    awaitingPaymentNote: "Vi har ännu inte fått någon betalning för den här ordern.",
    paid: "Betalning mottagen",
    paidNote: "Din order står i kö för produktion.",
    inProduction: "I produktion",
    inProductionNote: "Din vara trycks och färdigställs.",
    shipped: "Skickad",
    shippedNote: "Ditt paket är på väg. Spåra det via länken nedan.",
    delivered: "Levererad",
    deliveredNote: "Ditt paket har levererats. Hoppas du blir nöjd.",
    cancelled: "Avbruten",
    cancelledNote: "Den här ordern avbröts. Eventuell betalning har återbetalats.",
    exception: "Kräver åtgärd",
    exceptionNote:
      "Den här ordern är pausad. Butikens team arbetar med den och hör av sig.",
  },

  actions: {
    storeClosed: "Den här butiken tar inte emot ordrar just nu.",
    productGone: "Produkten är inte längre tillgänglig.",
    chooseVariant: "Välj storlek och färg.",
    outOfStock: "{variant} är slut i lager. Välj ett annat alternativ.",
    noTextPersonalisation: "Den här produkten kan inte personaliseras med text.",
    textTooLong: "Håll personaliseringen till högst {max} tecken.",
    noArtworkUpload: "Den här produkten tar inte emot uppladdad design.",
    productUnavailable: "Den här produkten är tillfälligt otillgänglig.",
    fileTooLarge: "Filen är {size} MB. Gränsen är {limit} MB.",
    basketUnavailable: "Din varukorg kunde inte öppnas. Tillåt cookies och försök igen.",
    addedToBasket: "{product} lades i din varukorg.",
    basketEmpty: "Din varukorg är tom.",
    enterName: "Ange namnet för leveransen.",
    enterEmail: "Ange en e-postadress — det är med den du öppnar din order senare.",
    enterStreet: "Ange gatuadressen.",
    enterCity: "Ange postorten.",
    enterPostalCode: "Ange postnumret.",
    chooseCountry: "Välj ditt leveransland i listan.",
    currencyNotSold: "{currency} är inte någon av butikens försäljningsvalutor.",
    enterOrderCode: "Ange din orderkod.",
    enterOrderEmail: "Ange e-postadressen på ordern.",
    lookupFailed:
      "Vi kunde inte matcha orderkoden med e-postadressen. Kontrollera båda och försök igen.",
  },

  artwork: {
    lowDpi: "Designen trycks i för låg upplösning. Ladda upp en fil med minst {dpi} DPI.",
    badFormat: "{format}-filer accepteras inte för den här produkten. Ladda upp {formats}.",
    fileTooLarge: "Filen är {size} MB. Gränsen är {limit} MB.",
    tooManyPixels:
      "Bilden är för stor. Minska den till under {megapixels} megapixlar och försök igen.",
    noTransparency:
      "Den här produkten kräver en design med transparent bakgrund. Exportera den som PNG med transparens.",
    generic: "Designen går inte att trycka på den här produkten. Prova en annan fil.",
  },

  payment: {
    accountNotReady:
      "Den här butiken har inte kopplat klart sitt Stripe-konto, så betalningar är inte möjliga.",
    currencyUnsupported: "{currency} är inte någon av butikens försäljningsvalutor.",
    invalidNumber: "Kortnumret är inte giltigt. Kontrollera siffrorna och försök igen.",
    invalidExpiry: "Giltighetsdatumet har passerat eller har fel format. Använd MM/ÅÅ.",
    invalidCvc: "Säkerhetskoden måste ha 3 eller 4 siffror.",
    declined: "Ditt kort nekades av den utfärdande banken.",
    insufficientFunds: "Ditt kort har otillräckliga medel.",
    expiredCard: "Ditt kort har gått ut.",
  },

  sections: {
    viewAll: "Visa alla",
    noProducts:
      "Inga produkter är publicerade i den här butiken än. Publicerade produkter dyker upp här automatiskt.",
    previewSoon: "Förhandsvisning kommer snart",
    imagePlaceholder: "Lägg till en bild-URL i sektionens inställningar",
    newsletterEmail: "E-postadress",
    notifyMe: "Meddela mig",
    welcome: "Välkommen",
  },

  fallback: {
    notFoundTitle: "Vi hittar inte den sidan",
    notFoundBody:
      "Länken kan vara inaktuell eller så säljs produkten inte längre. Allt som {store} säljer i dag finns kvar ett klick bort.",
    browseProducts: "Se alla produkter",
    errorTitle: "Något gick fel hos oss",
    errorBody:
      "Sidan kunde inte laddas. Din varukorg är orörd – försök igen och kom tillbaka om några minuter om det fortsätter.",
    errorRetry: "Försök igen",
    errorHome: "Tillbaka till {store}",
    errorReference: "Referens {digest}",
  },
};
