import type { StorefrontCopy } from "./en";

/** Storefront copy, Swedish. */
export const sv: StorefrontCopy = {
  chrome: {
    shop: "Butik",
    currencyLabel: "Valuta",
    currencyApply: "Använd",
    basket: "Varukorg",
    basketWithCount: "Varukorg ({count})",
    operatedBy: "Drivs av {client}. Tillverkas på beställning och skickas över hela världen.",
    allProducts: "Alla produkter",
    orderStatus: "Orderstatus",
    delivery: "Frakt",
    help: "Hjälp",
    supportEmailLabel: "E-post",
    supportPhoneLabel: "Telefon",
    supportPending: "Kontaktuppgifter till kundtjänst är ännu inte publicerade.",
    carriersPending: "Fraktbolag håller på att ställas in",
    pricesShownIn: "Priser i {currency}{tax}.",
    taxIncluded: ", inklusive moms",
    taxAtCheckout: ", moms tillkommer i kassan",
    legal:
      "© {year} {client}. {client} är säljare i den här butiken. Butiken drivs med Parcelith.",
  },

  meta: {
    homeTitle: "{store} — merch tillverkad på beställning",
    homeDescription:
      "Handla hos {store}, den officiella butiken för {client}. Tryckt på beställning och skickad över hela världen.",
    taglineDescription:
      "{tagline} Handla hos {store}, den officiella butiken för {client}.",
    shopTitle: "Butik",
    shopDescription: "Alla produkter som finns hos {store}.",
  },

  home: {
    closedTitle: "Den här butiken är stängd",
    closedBody:
      "{client} har arkiverat {store}. Befintliga ordrar levereras fortfarande och deras statussidor finns kvar.",
    comingSoonTitle: "{store} är nästan klar",
    comingSoonBody: "Butikens layout har inte publicerats än.",
    comingSoonWithProducts: "Produkterna är redan publicerade och går att titta på under tiden.",
    comingSoonNoProducts: "Titta in igen snart.",
    browseProducts: "Se {count} produkter",
  },

  shop: {
    title: "Allt i butiken",
    intro: "Tillverkas på beställning och skickas över hela världen. Priser i {currency}{tax}.",
    taxIncluded: ", inklusive moms",
    taxAtCheckout: "; moms tillkommer i kassan",
    searchLabel: "Sök",
    searchPlaceholder: "T-shirt, hoodie, mugg…",
    searchSubmit: "Sök",
    clear: "Rensa",
    filterByTag: "Filtrera på tagg",
    emptyTitle: "Inget publicerat än",
    emptyBody: "Den här butiken har inte publicerat några produkter än. Titta in igen snart.",
    noMatchTitle: "Inga produkter matchar sökningen",
    noMatchBody: "Prova ett annat sökord eller rensa filtren.",
    clearFilters: "Rensa filter",
    personalise: "Kan personaliseras",
    previewSoon: "Förhandsvisning kommer snart",
  },

  product: {
    breadcrumb: "Brödsmulor",
    breadcrumbShop: "Butik",
    about: "Om produkten",
    madeToOrder: "Tillverkas på beställning",
    producedBy: "Tillverkas av {supplier} på {lead} och skickas sedan med {carriers}.",
    defaultSupplier: "vår produktionspartner",
    leadDays: "{from}–{to} dagar",
    leadUnknown: "några dagar",
    defaultCarrier: "vårt fraktbolag",
    carrierJoin: "eller",
    printDetail: "Tryckdetaljer",
    printDetailBody: "{area}, {width} × {height} mm, tryckt i minst {dpi} DPI.",
    taxAndDelivery: "Moms och frakt",
    pricesShownIn: "Priser i {currency}{tax}.",
    taxIncluded: " inklusive moms",
    taxAtCheckout: "; moms räknas ut i kassan",
    merchantOfRecord: "{client} är säljare för den här ordern.",
  },

  purchase: {
    addToBasket: "Lägg i varukorgen",
    adding: "Lägger till…",
    viewBasket: "Visa varukorgen",
    colour: "Färg",
    size: "Storlek",
    option: "Variant",
    required: "Obligatoriskt",
    quantity: "Antal",
    lowStock: "få kvar",
    noPreview: "Ingen förhandsvisning tillgänglig",
    previewAlt: "Förhandsvisning av {name}",
    viewAlt: "Vy {view}",
    livePreview:
      "Live-förhandsvisning. En produktionstrogen version bifogas när du lägger varan i varukorgen.",
    textPlaceholder: "Valfritt",
    textCounter: "{count}/{max} tecken. Trycks tillsammans med designen.",
    artworkLabel: "Din egen design",
    artworkHint:
      "Trycks i {width} × {height} mm, så vi behöver minst {dpi} DPI. {formats} upp till {max} MB.",
    artworkHintSimple: "PNG, JPG eller WEBP.",
    uploading: "Laddar upp din design…",
    uploadFailed: "Filen kunde inte laddas upp.",
    fileTooLarge: "Filen är {size} MB. Gränsen är {limit} MB.",
    artworkPlacementTitle: "Placera din design",
    artworkPlacementHelp:
      "Dra designen i förhandsvisningen eller använd reglagen nedan. Förhandsvisningen och tryckupplösningen uppdateras direkt.",
    artworkGrabLabel:
      "Placering av {file}. Dra för att flytta eller använd piltangenterna; + och − ändrar storleken.",
    artworkSize: "Storlek",
    artworkRotation: "Rotation",
    artworkResolution: "Tryckupplösning",
    artworkRecentre: "Centrera igen",
    artworkRemove: "Ta bort designen",
    artworkChecksPass: "Designen är redo att tryckas i den här storleken.",
    artworkChecksFail: "Åtgärda det här innan du lägger den i varukorgen",
    artworkWhatToDo: "Gör så här: {fix}",
    artworkBlocked: "Åtgärda designen ovan, eller ta bort den, för att lägga varan i varukorgen.",
  },

  basket: {
    title: "Din varukorg",
    emptyTitle: "Inget i varukorgen än",
    emptyBody:
      "Lägg till en produkt med eventuell personalisering, så visas den här med förhandsvisningen som följer med din order.",
    browseShop: "Till butiken",
    previewAlt: "Förhandsvisning av {name}",
    personalisation: "Personalisering:",
    artwork: "Design: {file}",
    quantity: "Antal",
    update: "Uppdatera",
    remove: "Ta bort",
    summary: "Sammanfattning",
    subtotal: "Delsumma",
    shipping: "Frakt",
    taxRow: "Moms {rate} %",
    taxIncludedSuffix: "ingår",
    total: "Totalt",
    checkout: "Till kassan",
    keepShopping: "Fortsätt handla",
    viewBasket: "Visa varukorgen",
    drawerIntro: "En snabb titt i varukorgen. Antal och rabattkoder finns på den fullständiga varukorgssidan.",
  },

  discount: {
    title: "Rabattkod",
    label: "Kod",
    placeholder: "SPRING10",
    apply: "Använd",
    applying: "Använder…",
    remove: "Ta bort",
    row: "Rabatt ({code})",
    applied: "Koden {code} är använd — {amount} rabatt.",
    removed: "Rabattkoden togs bort.",
    enterCode: "Ange en rabattkod.",
    unknown: "Vi känner inte igen den koden.",
    inactive: "Koden är inte längre aktiv.",
    expired: "Koden har gått ut.",
    limitReached: "Koden har redan använts det högsta antalet gånger.",
    belowMinimum: "Koden kräver en varukorg på minst {amount}.",
    dropped:
      "Koden {code} gäller inte längre för den här varukorgen och togs bort. Kontrollera summan innan du betalar.",
  },

  checkout: {
    title: "Kassa",
    merchantNote: "{client} är säljare. Betalningen går in på deras eget Stripe-konto.",
    unavailableTitle: "Den här butiken kan inte ta emot betalningar än",
    unavailableBody:
      "Butiken har inte kopplat klart sitt Stripe-konto. Din varukorg sparas — försök igen när butiken är i drift.",
    backToBasket: "Tillbaka till varukorgen",
    summaryTitle: "Ordersammanfattning",
    shipping: "Frakt",
    taxRow: "Moms {rate} %",
    taxIncludedSuffix: "ingår",
    total: "Totalt",
    deliveryDetails: "Leveransuppgifter",
    fullName: "Fullständigt namn",
    email: "E-post",
    emailHint: "Med den här adressen och din orderkod öppnar du ordersidan igen senare.",
    street: "Gatuadress",
    city: "Postort",
    postalCode: "Postnummer",
    country: "Land",
    countryHint: "Börja skriva för att hitta ditt land. Produktionen styrs av destinationen.",
    countrySearchPlaceholder: "Sök länder",
    countryNoMatch: "Inget land matchar ”{query}”.",
    payIn: "Betala i",
    manualRoutingTitle: "Leverans till {country} kräver manuell hantering",
    manualRoutingLine: "{supplier} tillverkar {products} och levererar inte till {country} ({region}).",
    productJoin: "och",
    manualRoutingBody:
      "Du kan betala ändå, men ordern hålls kvar tills någon lägger den hos en annan produktionspartner, så den tar längre tid än den vanliga ledtiden. Väljer du ett leveransland som din leverantör täcker slipper du väntan.",
    paymentTitle: "Betalning",
    paymentNote:
      "Dras via butikens eget Stripe-konto {account}. Kortuppgifter sparas aldrig av butiken.",
    cardNumber: "Kortnummer",
    expiry: "Giltigt t.o.m. (MM/ÅÅ)",
    securityCode: "Säkerhetskod",
    testMode: "Stripe testläge",
    submit: "Betala och lägg order",
    pending: "Genomför betalning…",
    cardSucceeds: "Visa — godkänns",
    cardDeclined: "Visa — nekas av banken",
    cardInsufficient: "Visa — otillräckliga medel",
  },

  order: {
    title: "Orderstatus",
    lookupIntro:
      "Ange din orderkod och e-postadressen du angav i kassan. Länken du sparade när du lade ordern öppnar den direkt.",
    gateBody:
      "För att skydda leverans- och personaliseringsuppgifter behöver du bekräfta e-postadressen på order {code} innan vi visar den.",
    confirmedTitle: "Tack — din order är bekräftad",
    confirmedBody:
      "Spara den här sidan eller lägg den som bokmärke — det är här din order följs. Ett bekräftelsemejl med den här länken är på väg till dig.",
    confirmedFindAgain:
      "Du hittar den också via ”Orderstatus” med orderkoden {code} och e-postadressen {email}.",
    heading: "Order {code}",
    placed: "Lagd {when}",
    trackWith: "Spåra med {carrier} ↗",
    whatYouOrdered: "Det du beställde",
    variantQuantity: "{variant} · antal {count}",
    personalisation: "Personalisering:",
    previewAlt: "Förhandsvisning av {name}",
    subtotal: "Delsumma",
    shipping: "Frakt",
    taxRow: "Moms {rate} %",
    paid: "Betalt",
    refunded: "Återbetalt",
    deliveringTo: "Levereras till",
    payment: "Betalning",
    cardEnding: "Kort som slutar på {last4}",
    card: "Kort",
    paidWord: "betald",
    refundedWord: "återbetald",
    merchantOfRecord: "{client} är säljare.",
    progress: "Förlopp",
    supportTitle: "Frågor om den här ordern",
    contactSubject: "Order {code}",
    continueShopping: "Fortsätt handla",
    contactStore: "Kontakta butiken",
    orderCode: "Orderkod",
    orderCodeHint: "Börjar med ORD- och står högst upp på din ordersida.",
    emailOnOrder: "E-postadress på ordern",
    emailHint: "Adressen du angav i kassan.",
    lookupSubmit: "Visa min order",
    lookupPending: "Kontrollerar…",
  },

  status: {
    awaitingPayment: "Väntar på betalning",
    awaitingPaymentNote: "Vi har ännu inte fått någon betalning för den här ordern.",
    paid: "Betalning mottagen",
    paidNote: "Din order står i kö för produktion.",
    inProduction: "I produktion",
    inProductionNote: "Din vara trycks och färdigställs.",
    shipped: "Skickad",
    shippedNote: "Ditt paket är på väg. Spåra det via länken nedan.",
    delivered: "Levererad",
    deliveredNote: "Ditt paket har levererats. Hoppas du blir nöjd.",
    cancelled: "Avbruten",
    cancelledNote: "Den här ordern avbröts. Eventuell betalning har återbetalats.",
    exception: "Kräver åtgärd",
    exceptionNote:
      "Den här ordern är pausad. Butikens team arbetar med den och hör av sig.",
  },

  actions: {
    storeClosed: "Den här butiken tar inte emot ordrar just nu.",
    productGone: "Produkten är inte längre tillgänglig.",
    chooseVariant: "Välj storlek och färg.",
    outOfStock: "{variant} är slut i lager. Välj ett annat alternativ.",
    noTextPersonalisation: "Den här produkten kan inte personaliseras med text.",
    textTooLong: "Håll personaliseringen till högst {max} tecken.",
    noArtworkUpload: "Den här produkten tar inte emot uppladdad design.",
    productUnavailable: "Den här produkten är tillfälligt otillgänglig.",
    fileTooLarge: "Filen är {size} MB. Gränsen är {limit} MB.",
    basketUnavailable: "Din varukorg kunde inte öppnas. Tillåt cookies och försök igen.",
    addedToBasket: "{product} lades i din varukorg.",
    basketEmpty: "Din varukorg är tom.",
    enterName: "Ange namnet för leveransen.",
    enterEmail: "Ange en e-postadress — det är med den du öppnar din order senare.",
    enterStreet: "Ange gatuadressen.",
    enterCity: "Ange postorten.",
    enterPostalCode: "Ange postnumret.",
    chooseCountry: "Välj ditt leveransland i listan.",
    currencyNotSold: "{currency} är inte någon av butikens försäljningsvalutor.",
    enterOrderCode: "Ange din orderkod.",
    enterOrderEmail: "Ange e-postadressen på ordern.",
    lookupFailed:
      "Vi kunde inte matcha orderkoden med e-postadressen. Kontrollera båda och försök igen.",
  },

  artwork: {
    lowDpi: "Bilden trycks i {dpi} DPI, under de {required} DPI som produkten kräver.",
    lowDpiFix:
      "Ladda upp en som är minst {pixels} pixlar bred, eller gör designen mindre — filen är skarp upp till {width} mm bred.",
    badFormat: "{format}-filer accepteras inte för den här produkten.",
    badFormatFix: "Spara designen som {formats} och välj den igen.",
    unreadableFormat: "{format}-filer går inte att mäta eller förhandsvisa här.",
    unreadableFormatFix: "Spara designen som {formats} och välj den igen.",
    fileTooLarge: "Filen är {size} MB. Gränsen är {limit} MB.",
    fileTooLargeFix: "Spara den i mindre storlek eller lägre kvalitet och välj den igen.",
    tooManyPixels: "Bilden är för stor. Gränsen är {megapixels} megapixlar.",
    tooManyPixelsFix: "Ändra storlek i ditt bildprogram och välj den igen.",
    noTransparency:
      "Den här produkten trycks direkt på tyget, så designen behöver en transparent bakgrund.",
    noTransparencyFix: "Ta bort bakgrunden och spara den som PNG med transparens.",
    outsideArea: "En del av designen hamnar utanför tryckytan och skulle skäras bort.",
    outsideAreaFix:
      "Dra tillbaka den innanför den streckade ramen, eller gör den mindre så att den ryms på {width} × {height} mm.",
    dpiTight: "Bilden trycks i {dpi} DPI, precis över minimigränsen på {required} DPI.",
    dpiTightFix:
      "Tunna linjer kan se mjuka ut. En större fil, eller en något mindre design, trycks skarpare.",
    verySmall: "Designen täcker mindre än 15 % av tryckbredden.",
    verySmallFix: "Dra upp storleken om den ska vara huvudmotivet.",
    generic: "Designen går inte att trycka på den här produkten.",
    genericFix: "Prova en annan fil.",
  },

  payment: {
    accountNotReady:
      "Den här butiken har inte kopplat klart sitt Stripe-konto, så betalningar är inte möjliga.",
    currencyUnsupported: "{currency} är inte någon av butikens försäljningsvalutor.",
    invalidNumber: "Kortnumret är inte giltigt. Kontrollera siffrorna och försök igen.",
    invalidExpiry: "Giltighetsdatumet har passerat eller har fel format. Använd MM/ÅÅ.",
    invalidCvc: "Säkerhetskoden måste ha 3 eller 4 siffror.",
    declined: "Ditt kort nekades av den utfärdande banken.",
    insufficientFunds: "Ditt kort har otillräckliga medel.",
    expiredCard: "Ditt kort har gått ut.",
  },

  sections: {
    viewAll: "Visa alla",
    noProducts:
      "Inga produkter är publicerade i den här butiken än. Publicerade produkter dyker upp här automatiskt.",
    previewSoon: "Förhandsvisning kommer snart",
    imagePlaceholder: "Lägg till en bild-URL i sektionens inställningar",
    newsletterEmail: "E-postadress",
    notifyMe: "Meddela mig",
    welcome: "Välkommen",
  },

  email: {
    logoAlt: "{store}",
    greeting: "Hej {name},",
    footer: "{client} är säljare i den här butiken. Skickat av {store}.",
    support: "Frågor? Mejla oss på {email}.",
    orderSubject: "Order {code} är bekräftad — {store}",
    orderHeading: "Tack för din beställning",
    orderBody:
      "Vi har tagit emot order {code} och betalningen gick igenom. Länken nedan öppnar orderns statussida när som helst — spara den gärna.",
    orderCta: "Visa din order",
    orderTotalLabel: "Totalt betalt",
    orderDeliveryLabel: "Levereras till",
    shippedSubject: "Order {code} är på väg — {store}",
    shippedHeading: "Ditt paket är på väg",
    shippedBody: "Order {code} har lämnats till {carrier}.",
    shippedTrackingLabel: "Kolli-id",
    shippedCta: "Spåra paketet",
    inviteSubject: "{inviter} har bjudit in dig till {store}",
    inviteHeading: "Du har blivit inbjuden till {store}",
    inviteBody:
      "{inviter} bjuder in dig att arbeta med {store} som {role}. Länken nedan skapar ditt konto och aktiverar din åtkomst. Den fungerar en gång.",
    inviteCta: "Tacka ja till inbjudan",
    approvalSubject: "Gåvokampanj {code} väntar på ditt godkännande — {store}",
    approvalHeading: "En gåvokampanj väntar på ditt godkännande",
    approvalBody:
      "{buyer} har skickat in ”{campaign}” för {company}. Ingenting debiteras förrän du godkänner listan.",
    approvalRecipientsLabel: "Mottagare",
    approvalTotalLabel: "Totalt",
    approvalCta: "Granska listan",
  },

  gift: {
    chromeSubtitle: "Gåvokatalog · {store}",
    private: "Privat",
    operatedBy:
      "Drivs av {client}, som är säljare. Gåvorna tillverkas på beställning och skickas separat till varje mottagare.",
    supportTitle: "Frågor om en kampanj:",
    supportPending: "{client} har ännu inte publicerat några kontaktuppgifter för support.",
    legal: "© {year} {client}. Företagsgåvor drivs av Parcelith.",

    closedTitle: "Den här katalogen är stängd",
    closedBody:
      "Gåvoprogrammet för {company} är pausat. Den som sköter det åt er kan öppna det igen — kampanjer som redan lagts påverkas inte.",

    privateBadge: "Privat katalog",
    inviteBody:
      "Gåvokatalogen för {company} är öppen för inbjudna kollegor. Bekräfta adressen som inbjudan skickades till, så släpps du in direkt.",
    linkOnlyBody:
      "Den här katalogen öppnas med den privata länk som programansvarig hos {company} delade. Använd länken igen eller be om en ny — länkarna byts ut så snart programmet byter ansvarig.",
    gateEmail: "Jobbmejl",
    gateEmailHint: "Det måste vara en av adresserna som er programansvariga bjöd in.",
    gateSubmit: "Öppna katalogen",
    gatePending: "Kontrollerar…",

    introFallback:
      "Gåvor för {company}, tillverkade på beställning och levererade separat till varje mottagare.",
    startOrder: "Starta en massbeställning",
    spendLimitLabel: "Beloppsgräns per mottagare",
    noLimit: "Ingen gräns",
    approvalLabel: "Godkännande",
    approvalRequired: "Krävs",
    approvalNotRequired: "Krävs inte",
    recipientsLabel: "Mottagare per kampanj",
    recipientsUpTo: "Upp till {count}",
    emptyTitle: "Inga gåvor är tillgängliga just nu",
    emptyBody:
      "Inget i den här katalogen är i produktion för tillfället. Den som sköter programmet åt er vet när det är tillbaka.",
    giftsTitle: "Gåvor i den här katalogen",
    previewSoon: "Förhandsvisning kommer snart",
    overLimit: "Över gränsen",
    sizes: "Storlekar: {sizes}",
    oneSize: "En storlek",
    overLimitTitle: "Några gåvor ligger över er beloppsgräns",
    overLimitBody:
      "En mottagare som kopplas till någon av dem avvisas när listan läses in, så att raden kan ändras innan någon ombeds godkänna den.",
    howItWorks: "Så fungerar en kampanj",
    step1Title: "Välj gåvan",
    step1Body:
      "Allt här produceras redan för det här programmet, i de storlekar era medarbetare kan välja mellan.",
    step2Title: "Lägg till er mottagarlista",
    step2Body:
      "Klistra in den från ett kalkylblad eller ladda upp en CSV — namn, adresser, storlekar och ett valfritt meddelande.",
    step3Title: "Godkännande",
    step3Body:
      "Listan går med sin totalsumma till den som godkänner innan något betalas.",
    step4Title: "En betalning, ett paket var",
    step4Body:
      "Ni betalar en gång. Varje mottagare får sitt eget paket och sin egen spårning.",

    orderTitle: "Massbeställning av gåvor",
    campaignTitle: "Gåvokampanj",
    orderIntro:
      "Lägg till alla ni skickar till, med adressen paketet ska nå och storleken de bär. Kontrollera listan hur ofta ni vill — inget skapas förrän ni skickar in den{approval}.",
    orderIntroApproval: " för godkännande",
    paymentPendingTitle: "Betalningar är ännu inte påslagna för den här butiken",
    paymentPendingBody:
      "Ni kan ändå bygga en kampanj och skicka den för godkännande. Den kan inte betalas förrän {client} har kopplat sitt betalkonto färdigt.",
    yourApprover: "den som godkänner",

    buyerTitle: "Vem beställer",
    campaignName: "Kampanjens namn",
    campaignNamePlaceholder: "Kundgåvor Q4",
    buyerName: "Ditt namn",
    orderingAs:
      "Du beställer som {email}. Spara kampanjlänken du landar på härnäst — inget mejl skickas, och det är på den sidan godkännandet och kvittot visas.",
    buyerEmail: "Ditt jobbmejl",
    buyerEmailHint:
      "Registreras på kampanjen som beställare. Spara kampanjlänken du landar på härnäst — inget mejl skickas, och det är på den sidan godkännandet och kvittot visas.",
    giftTitle: "Gåvan",
    giftHint: "Används för varje rad som inte anger en egen produkt.",
    giftHintLimit: "Per mottagare får upp till {amount} användas.",
    giftHintNoLimit: "Det här programmet har ingen beloppsgräns.",
    listTitle: "Mottagare",
    listHintLead: "En person per rad, upp till {max}. Kolumner:",
    listHintTail:
      "En rubrikrad känns igen automatiskt, och {product} och {note} är valfria.",
    uploadCsv: "Ladda upp en CSV",
    pasteExample: "Klistra in exemplet",
    fileLoaded: "{file} inläst",
    fileTooLarge: "{file} är {size} KB. Mottagarlistor ligger under {limit} KB.",
    fileUnreadable: "Filen kunde inte läsas. Spara den som CSV och försök igen.",
    listLabel: "Mottagarlista",
    checkList: "Kontrollera listan",
    checkPending: "Läser listan…",
    sendForApproval: "Skicka för godkännande",
    checkAndSend: "Kontrollera och skicka",
    sendPending: "Arbetar…",
    previewRecipients: "{count} mottagare",
    previewToFix: "{count} att rätta",
    previewTotal: "{amount} totalt",
    previewOverflow: "{count} rader över gränsen lästes inte",
    columnLine: "Rad",
    columnRecipient: "Mottagare",
    columnGift: "Gåva",
    columnDelivered: "Levererat",
    columnDelivery: "Leverans",
    columnValue: "Värde",
    noName: "Inget namn",
    subtotal: "Gåvor",
    shipping: "Frakt",
    tax: "Moms",
    taxRow: "Moms {rate} %",
    total: "Totalt",
    approvalNote:
      "När ni skickar in hamnar kampanjen hos {approver}. Inget debiteras förrän den är godkänd och ni betalar.",
    noApprovalNote:
      "Det här programmet behöver inget godkännande, så ni går direkt till betalning när listan är ren.",

    linkInvalidTitle: "Den här kampanjlänken är inte giltig",
    linkInvalidBody:
      "Kampanjlänkar är personliga: en för beställaren, en för den som godkänner. Be att din skickas igen, eller öppna katalogen och börja en ny beställning.",
    backToCatalogue: "Tillbaka till katalogen",
    campaignSubmitted: "{count} mottagare · skickad av {buyer} den {when}",
    waitingTitle: "Väntar på godkännande",
    waitingBody:
      "{approver} har listan och dess totalsumma. Ni kan betala så snart den är godkänd — inget har debiterats.",
    decisionTitle: "Ditt beslut är registrerat",
    decisionBody: "{decision} av {who} den {when}.",
    decisionCanPay: "{buyer} kan nu betala den — inget har debiterats dig.",
    decisionApproved: "Godkänd",
    decisionDeclined: "Avslagen",
    declinedNoReason: "Ingen anledning angavs.",
    declinedBody:
      "Börja en ny beställning från katalogen med de ändringar den som godkänner bad om.",
    orderedTitle: "Betald och i produktion",
    orderedBody:
      "{count} beställningar skapades, en per mottagare, var och en med egen leverans och spårning. Följ dem nedan.",
    unpayableTitle: "Godkänd, men butiken kan inte ta betalt ännu",
    unpayableBody:
      "{client} har inte kopplat sitt betalkonto färdigt. Er kampanj är sparad och kan betalas så snart det är klart.",
    recipientsTitle: "Mottagare",
    track: "Spåra {code}",
    historyTitle: "Historik",
    totalsTitle: "Kampanjens totalsumma",
    spendLimitNote: "Beloppsgräns {amount} per mottagare.",
    noSpendLimitNote: "Ingen beloppsgräns i det här programmet.",
    decisionFormTitle: "Ditt beslut",
    paymentTitle: "Betalning",
    approvalIntro:
      "{buyer} behöver ditt godkännande innan kampanjen kan betalas. Att godkänna kostar ingenting — beställaren betalar på sin egen skärm.",
    noteLabel: "Notering (krävs för avslag)",
    notePlaceholder: "Godkänd mot marknadsbudgeten för Q4.",
    approve: "Godkänn {total}",
    approvePending: "Registrerar ditt beslut…",
    decline: "Avslå",
    declinePending: "Registrerar…",
    paymentIntro:
      "En betalning för hela kampanjen, dragen via butikens eget Stripe-konto {account}. Varje mottagare blir sedan en egen beställning med egen spårning.",
    pay: "Betala {total}",
    payPending: "Genomför betalningen…",
    withdraw: "Dra tillbaka kampanjen",
    withdrawConfirm: "Dra tillbaka kampanjen",
    withdrawQuestion: "Listan dras tillbaka och ingen debiteras.",
    withdrawPending: "Arbetar…",
    cancel: "Avbryt",

    statusAwaitingApproval: "Väntar på godkännande",
    statusApproved: "Godkänd, väntar på betalning",
    statusDeclined: "Avslagen",
    statusOrdered: "Beställd",
    statusCancelled: "Avbruten",

    eyebrow: "Gåvoportal",
    notFoundTitle: "Vi hittar inte den sidan",
    notFoundBody:
      "Adressen kan vara felstavad, eller kampanjen eller produkten den pekade på kan ha stängts sedan länken skickades. Själva katalogen är fortfarande öppen.",
    notFoundBoundaryBody:
      "Länken kan ha gått ut, eller gåvokatalogen kan ha stängts av företaget som skapade den. Om någon skickade dig länken, be om en aktuell.",
    errorTitle: "Något gick fel hos oss",
    errorBody:
      "Sidan kunde inte laddas. Inget av det du skickat in har förlorats — försök igen, och kom tillbaka om några minuter om det fortsätter.",
    errorRetry: "Försök igen",
    errorReference: "Referens {digest}",
    goToParcelith: "Till Parcelith",
  },

  fallback: {
    notFoundTitle: "Vi hittar inte den sidan",
    notFoundBody:
      "Länken kan vara inaktuell eller så säljs produkten inte längre. Allt som {store} säljer i dag finns kvar ett klick bort.",
    browseProducts: "Se alla produkter",
    errorTitle: "Något gick fel hos oss",
    errorBody:
      "Sidan kunde inte laddas. Din varukorg är orörd – försök igen och kom tillbaka om några minuter om det fortsätter.",
    errorRetry: "Försök igen",
    errorHome: "Tillbaka till {store}",
    errorReference: "Referens {digest}",
  },
};
